/* Drawing — objects/vehicles/symbols */
addWords("drawing", [
  ["objects", 1, "Chair", "Стул", "draw"],
  ["objects", 1, "Table", "Стол", "draw"],
  ["objects", 1, "Ball", "Мяч", "draw"],
  ["objects", 1, "Cup", "Кружка", "draw"],
  ["objects", 1, "Key", "Ключ", "draw"],
  ["objects", 1, "Book", "Книга", "draw"],
  ["objects", 1, "Clock", "Часы", "draw"],
  ["objects", 1, "Umbrella", "Зонт", "draw"],
  ["objects", 1, "Hat", "Шляпа", "draw"],
  ["objects", 1, "Shoe", "Ботинок", "draw"],
  ["objects", 1, "Glasses", "Очки", "draw"],
  ["objects", 1, "Scissors", "Ножницы", "draw"],
  ["objects", 1, "Spoon", "Ложка", "draw"],
  ["objects", 1, "Fork", "Вилка", "draw"],
  ["objects", 1, "Knife", "Нож", "draw"],
  ["objects", 1, "Candle", "Свеча", "draw"],
  ["objects", 1, "Bottle", "Бутылка", "draw"],
  ["objects", 1, "Box", "Коробка", "draw"],
  ["objects", 1, "Balloon", "Шарик", "draw"],
  ["objects", 1, "Kite", "Воздушный змей", "draw"],
  ["objects", 1, "Drum", "Барабан", "draw"],
  ["objects", 1, "Guitar", "Гитара", "draw"],
  ["objects", 1, "Ladder", "Лестница", "draw"],
  ["objects", 1, "Broom", "Метла", "draw"],
  ["objects", 1, "Bucket", "Ведро", "draw"],
  ["objects", 1, "Hammer", "Молоток", "draw"],
  ["objects", 1, "Brush", "Кисть", "draw"],
  ["objects", 1, "Pencil", "Карандаш", "draw"],
  ["objects", 1, "Phone", "Телефон", "draw"],
  ["objects", 1, "Lamp", "Лампа", "draw"],
  ["objects", 1, "Door", "Дверь", "draw"],
  ["objects", 1, "Window", "Окно", "draw"],
  ["objects", 1, "Flag", "Флаг", "draw"],
  ["objects", 1, "Crown", "Корона", "draw"],
  ["objects", 1, "Ring", "Кольцо", "draw"],
  ["objects", 1, "Bell", "Колокол", "draw"],
  ["objects", 1, "Anchor", "Якорь", "draw"],
  ["objects", 1, "Hook", "Крюк", "draw"],
  ["objects", 1, "Sword", "Меч", "draw"],
  ["objects", 1, "Shield", "Щит", "draw"],
  ["vehicles", 1, "Plane", "Самолёт", "draw"],
  ["vehicles", 1, "Ship", "Корабль", "draw"],
  ["vehicles", 1, "Boat", "Лодка", "draw"],
  ["vehicles", 1, "Car", "Машина", "draw"],
  ["vehicles", 1, "Bus", "Автобус", "draw"],
  ["vehicles", 1, "Train", "Поезд", "draw"],
  ["vehicles", 1, "Bicycle", "Велосипед", "draw"],
  ["vehicles", 1, "Motorcycle", "Мотоцикл", "draw"],
  ["vehicles", 1, "Truck", "Грузовик", "draw"],
  ["vehicles", 1, "Rocket", "Ракета", "draw"],
  ["vehicles", 1, "Helicopter", "Вертолёт", "draw"],
  ["vehicles", 1, "Submarine", "Подводная лодка", "draw"],
  ["vehicles", 1, "Hot Air Balloon", "Воздушный шар", "draw"],
  ["vehicles", 1, "Tractor", "Трактор", "draw"],
  ["vehicles", 1, "Scooter", "Самокат", "draw"],
  ["vehicles", 1, "Sailboat", "Парусник", "draw"],
  ["vehicles", 1, "Canoe", "Каноэ", "draw"],
  ["vehicles", 1, "Ambulance", "Скорая помощь", "draw"],
  ["vehicles", 1, "Fire Truck", "Пожарная машина", "draw"],
  ["vehicles", 1, "Tank", "Танк", "draw"],
  ["vehicles", 1, "Van", "Фургон", "draw"],
  ["vehicles", 1, "Taxi", "Такси", "draw"],
  ["vehicles", 2, "Jet", "Реактивный самолёт", "draw"],
  ["vehicles", 1, "Skateboard", "Скейтборд", "draw"],
  ["vehicles", 2, "Wheelbarrow", "Тачка", "draw"],
  ["vehicles", 1, "Sled", "Санки", "draw"],
  ["vehicles", 1, "Surfboard", "Доска для сёрфинга", "draw"],
  ["vehicles", 2, "Blimp", "Дирижабль", "draw"],
  ["vehicles", 2, "Kayak", "Каяк", "draw"],
  ["vehicles", 1, "Roller Skates", "Роликовые коньки", "draw"],
  ["symbols", 1, "Star", "Звезда", "draw"],
  ["symbols", 1, "Heart", "Сердце", "draw"],
  ["symbols", 1, "Arrow", "Стрелка", "draw"],
  ["symbols", 1, "Circle", "Круг", "draw"],
  ["symbols", 1, "Square", "Квадрат", "draw"],
  ["symbols", 1, "Triangle", "Треугольник", "draw"],
  ["symbols", 1, "Smiley Face", "Смайлик", "draw"],
  ["symbols", 1, "Lightning Bolt", "Молния", "draw"],
  ["symbols", 1, "Snowflake", "Снежинка", "draw"],
  ["symbols", 1, "Sun", "Солнце", "draw"],
  ["symbols", 1, "Moon", "Луна", "draw"],
  ["symbols", 1, "Cross", "Крест", "draw"],
  ["symbols", 1, "Diamond", "Ромб", "draw"],
  ["symbols", 2, "Spiral", "Спираль", "draw"],
  ["symbols", 1, "Question Mark", "Вопросительный знак", "draw"],
  ["symbols", 1, "Exclamation Mark", "Восклицательный знак", "draw"],
  ["symbols", 1, "Music Note", "Нота", "draw"],
  ["symbols", 2, "Peace Sign", "Знак мира", "draw"],
  ["symbols", 2, "Infinity", "Бесконечность", "draw"],
  ["symbols", 2, "Yin Yang", "Инь-ян", "draw"],
  ["symbols", 2, "Gear", "Шестерёнка", "draw"],
  ["symbols", 1, "Light Bulb", "Лампочка", "draw"],
  ["symbols", 1, "Footprint", "След", "draw"],
  ["symbols", 1, "Target", "Мишень", "draw"],
  ["symbols", 1, "Hashtag", "Решётка", "draw"],
  ["symbols", 1, "Dollar Sign", "Знак доллара", "draw"],
  ["symbols", 1, "Cloud", "Облако", "draw"],
  ["symbols", 1, "Eye", "Глаз", "draw"],
  ["symbols", 1, "Crown", "Корона", "draw"],
]);
