/* Video Games — Modern characters */
addWords("games", [
  ["overwatch", 1, "Tracer", "Трейсер", "draw"],
  ["overwatch", 1, "Genji", "Гэндзи", "draw"],
  ["overwatch", 1, "Hanzo", "Хандзо", "draw"],
  ["overwatch", 1, "D.Va", "Д.Ва", "draw"],
  ["overwatch", 1, "Reinhardt", "Райнхардт", "draw"],
  ["overwatch", 1, "Mercy", "Мерси", "draw"],
  ["overwatch", 1, "Widowmaker", "Вдовица", "draw"],
  ["overwatch", 1, "Reaper", "Жнец", "draw"],
  ["overwatch", 1, "Soldier 76", "Солдат 76", "draw"],
  ["overwatch", 2, "Mei", "Мэй", "draw"],
  ["overwatch", 2, "Winston", "Уинстон", "draw"],
  ["overwatch", 2, "Zarya", "Заря", "draw"],
  ["overwatch", 2, "Sombra", "Сомбра", "draw"],
  ["overwatch", 2, "Lucio", "Лусио", "draw"],
  ["overwatch", 2, "Ana", "Ана", "draw"],
  ["overwatch", 2, "Junkrat", "Крысавчик", "draw"],
  ["overwatch", 2, "Roadhog", "Боров", "draw"],
  ["overwatch", 3, "Moira", "Мойра", "draw"],

  ["genshin", 1, "Paimon", "Паймон", "draw"],
  ["genshin", 1, "Zhongli", "Чжун Ли", "draw"],
  ["genshin", 1, "Venti", "Венти", "draw"],
  ["genshin", 1, "Raiden Shogun", "Райдэн Сёгун", "draw"],
  ["genshin", 1, "Hu Tao", "Ху Тао", "draw"],
  ["genshin", 1, "Klee", "Кли", "draw"],
  ["genshin", 1, "Ganyu", "Гань Юй", "draw"],
  ["genshin", 1, "Diluc", "Дилюк", "draw"],
  ["genshin", 2, "Aether", "Итэр", "draw"],
  ["genshin", 2, "Lumine", "Люмин", "draw"],
  ["genshin", 2, "Kazuha", "Кадзуха", "draw"],
  ["genshin", 2, "Ayaka", "Аяка", "draw"],
  ["genshin", 2, "Nahida", "Нахида", "draw"],
  ["genshin", 2, "Furina", "Фурина", "draw"],
  ["genshin", 2, "Xiao", "Сяо", "draw"],
  ["genshin", 3, "Yae Miko", "Яэ Мико", "draw"],
  ["genshin", 3, "Childe", "Тартаглья", "draw"],

  ["valorant", 1, "Jett", "Джетт"],
  ["valorant", 1, "Sage", "Сейдж"],
  ["valorant", 1, "Reyna", "Рейна"],
  ["valorant", 1, "Phoenix", "Феникс"],
  ["valorant", 1, "Sova", "Сова"],
  ["valorant", 2, "Cypher", "Шифр"],
  ["valorant", 2, "Killjoy", "Киллджой"],
  ["valorant", 2, "Raze", "Рейз"],
  ["valorant", 2, "Omen", "Омен"],
  ["valorant", 2, "Brimstone", "Бримстоун"],
  ["valorant", 2, "Viper", "Вайпер"],
  ["valorant", 2, "Chamber", "Чемпион"],
  ["valorant", 2, "Neon", "Неон"],
  ["valorant", 3, "Fade", "Фейд"],
  ["valorant", 3, "Breach", "Брич"],
  ["valorant", 3, "Skye", "Скай"],
]);
