/* Video Games — Titles */
addWords("games", [
  // [ subgroupId, difficulty(1-3), "EN title", "RU title" ]

  // t_shooter
  ["t_shooter", 1, "Call of Duty", "Call of Duty"],
  ["t_shooter", 1, "Counter-Strike", "Counter-Strike"],
  ["t_shooter", 1, "Fortnite", "Fortnite"],
  ["t_shooter", 1, "PUBG", "PUBG"],
  ["t_shooter", 1, "Overwatch", "Overwatch"],
  ["t_shooter", 1, "Battlefield", "Battlefield"],
  ["t_shooter", 2, "Valorant", "Valorant"],
  ["t_shooter", 2, "Apex Legends", "Apex Legends"],
  ["t_shooter", 2, "Rainbow Six Siege", "Rainbow Six Siege"],
  ["t_shooter", 2, "Halo", "Halo"],
  ["t_shooter", 2, "Doom", "Doom"],
  ["t_shooter", 2, "Destiny", "Destiny"],
  ["t_shooter", 2, "Far Cry", "Far Cry"],
  ["t_shooter", 2, "Borderlands", "Borderlands"],
  ["t_shooter", 3, "Titanfall", "Titanfall"],
  ["t_shooter", 3, "Left 4 Dead", "Left 4 Dead"],
  ["t_shooter", 3, "Team Fortress 2", "Team Fortress 2"],
  ["t_shooter", 3, "Escape from Tarkov", "Escape from Tarkov"],

  // t_action
  ["t_action", 1, "Grand Theft Auto", "Grand Theft Auto"],
  ["t_action", 1, "Red Dead Redemption", "Red Dead Redemption"],
  ["t_action", 1, "Cyberpunk 2077", "Cyberpunk 2077"],
  ["t_action", 1, "Assassin's Creed", "Assassin's Creed"],
  ["t_action", 1, "The Last of Us", "The Last of Us"],
  ["t_action", 1, "God of War", "God of War"],
  ["t_action", 2, "Spider-Man", "Spider-Man"],
  ["t_action", 2, "Uncharted", "Uncharted"],
  ["t_action", 2, "Ghost of Tsushima", "Ghost of Tsushima"],
  ["t_action", 2, "Horizon Zero Dawn", "Horizon Zero Dawn"],
  ["t_action", 2, "Sekiro", "Sekiro"],
  ["t_action", 2, "Tomb Raider", "Tomb Raider"],
  ["t_action", 2, "Watch Dogs", "Watch Dogs"],
  ["t_action", 2, "Hitman", "Hitman"],
  ["t_action", 2, "Mafia", "Mafia"],
  ["t_action", 3, "Metal Gear Solid", "Metal Gear Solid"],
  ["t_action", 3, "Max Payne", "Max Payne"],
  ["t_action", 3, "Control", "Control"],

  // t_rpg
  ["t_rpg", 1, "Minecraft", "Minecraft"],
  ["t_rpg", 1, "The Witcher 3", "Ведьмак 3"],
  ["t_rpg", 1, "Skyrim", "Skyrim"],
  ["t_rpg", 1, "Elden Ring", "Elden Ring"],
  ["t_rpg", 1, "Genshin Impact", "Genshin Impact"],
  ["t_rpg", 1, "Diablo", "Diablo"],
  ["t_rpg", 2, "Final Fantasy", "Final Fantasy"],
  ["t_rpg", 2, "Baldur's Gate 3", "Baldur's Gate 3"],
  ["t_rpg", 2, "Mass Effect", "Mass Effect"],
  ["t_rpg", 2, "Fallout", "Fallout"],
  ["t_rpg", 2, "Dark Souls", "Dark Souls"],
  ["t_rpg", 2, "Dragon Age", "Dragon Age"],
  ["t_rpg", 2, "Kingdom Hearts", "Kingdom Hearts"],
  ["t_rpg", 2, "Monster Hunter", "Monster Hunter"],
  ["t_rpg", 2, "Bloodborne", "Bloodborne"],
  ["t_rpg", 3, "Persona", "Persona"],
  ["t_rpg", 3, "Path of Exile", "Path of Exile"],
  ["t_rpg", 3, "Divinity: Original Sin", "Divinity: Original Sin"],

  // t_sports
  ["t_sports", 1, "EA Sports FC", "EA Sports FC"],
  ["t_sports", 1, "NBA 2K", "NBA 2K"],
  ["t_sports", 1, "Rocket League", "Rocket League"],
  ["t_sports", 1, "Mario Kart", "Mario Kart"],
  ["t_sports", 1, "Need for Speed", "Need for Speed"],
  ["t_sports", 1, "Wii Sports", "Wii Sports"],
  ["t_sports", 2, "Madden NFL", "Madden NFL"],
  ["t_sports", 2, "Forza Horizon", "Forza Horizon"],
  ["t_sports", 2, "Gran Turismo", "Gran Turismo"],
  ["t_sports", 2, "F1", "F1"],
  ["t_sports", 2, "NHL", "NHL"],
  ["t_sports", 2, "WWE 2K", "WWE 2K"],
  ["t_sports", 2, "Tony Hawk's Pro Skater", "Tony Hawk's Pro Skater"],
  ["t_sports", 3, "PGA Tour", "PGA Tour"],
  ["t_sports", 3, "SSX", "SSX"],
  ["t_sports", 3, "Virtua Tennis", "Virtua Tennis"],

  // t_online
  ["t_online", 1, "Minecraft", "Minecraft"],
  ["t_online", 1, "Roblox", "Roblox"],
  ["t_online", 1, "Among Us", "Among Us"],
  ["t_online", 1, "Candy Crush", "Candy Crush"],
  ["t_online", 1, "Clash of Clans", "Clash of Clans"],
  ["t_online", 1, "The Sims", "The Sims"],
  ["t_online", 2, "League of Legends", "League of Legends"],
  ["t_online", 2, "Dota 2", "Dota 2"],
  ["t_online", 2, "Fall Guys", "Fall Guys"],
  ["t_online", 2, "Stardew Valley", "Stardew Valley"],
  ["t_online", 2, "Animal Crossing", "Animal Crossing"],
  ["t_online", 2, "World of Warcraft", "World of Warcraft"],
  ["t_online", 2, "Sea of Thieves", "Sea of Thieves"],
  ["t_online", 2, "Terraria", "Terraria"],
  ["t_online", 3, "Rust", "Rust"],
  ["t_online", 3, "Garry's Mod", "Garry's Mod"],
  ["t_online", 3, "DayZ", "DayZ"],

  // t_classic
  ["t_classic", 1, "Tetris", "Тетрис"],
  ["t_classic", 1, "Pac-Man", "Pac-Man"],
  ["t_classic", 1, "Super Mario Bros", "Super Mario Bros"],
  ["t_classic", 1, "Angry Birds", "Angry Birds"],
  ["t_classic", 1, "Sonic the Hedgehog", "Sonic the Hedgehog"],
  ["t_classic", 1, "Street Fighter", "Street Fighter"],
  ["t_classic", 1, "Mortal Kombat", "Mortal Kombat"],
  ["t_classic", 2, "Space Invaders", "Space Invaders"],
  ["t_classic", 2, "Donkey Kong", "Donkey Kong"],
  ["t_classic", 2, "Pong", "Pong"],
  ["t_classic", 2, "Frogger", "Frogger"],
  ["t_classic", 2, "Galaga", "Galaga"],
  ["t_classic", 2, "Hollow Knight", "Hollow Knight"],
  ["t_classic", 2, "Cuphead", "Cuphead"],
  ["t_classic", 2, "Celeste", "Celeste"],
  ["t_classic", 2, "Undertale", "Undertale"],
  ["t_classic", 3, "Contra", "Контра"],
  ["t_classic", 3, "Castlevania", "Castlevania"],
  ["t_classic", 3, "Mega Man", "Mega Man"],
]);
