/* Animals */
addWords("animals", [
  ["pets", 1, "Dog", "Собака", "draw"],
  ["pets", 1, "Cat", "Кошка", "draw"],
  ["pets", 1, "Horse", "Лошадь", "draw"],
  ["pets", 1, "Cow", "Корова", "draw"],
  ["pets", 1, "Pig", "Свинья", "draw"],
  ["pets", 1, "Chicken", "Курица", "draw"],
  ["pets", 1, "Rabbit", "Кролик", "draw"],
  ["pets", 1, "Sheep", "Овца", "draw"],
  ["pets", 1, "Duck", "Утка", "draw"],
  ["pets", 1, "Goat", "Коза", "draw"],
  ["pets", 2, "Hamster", "Хомяк", "draw"],
  ["pets", 2, "Donkey", "Осёл", "draw"],
  ["pets", 2, "Turkey", "Индейка", "draw"],
  ["pets", 2, "Parrot", "Попугай", "draw"],
  ["pets", 2, "Goldfish", "Золотая рыбка", "draw"],
  ["pets", 2, "Pony", "Пони", "draw"],
  ["pets", 2, "Llama", "Лама", "draw"],
  ["pets", 2, "Guinea Pig", "Морская свинка", "draw"],
  ["pets", 3, "Ferret", "Хорёк", "draw"],
  ["pets", 3, "Gerbil", "Песчанка", "draw"],
  ["pets", 3, "Mouse", "Мышь", "draw"],
  ["pets", 3, "Alpaca", "Альпака", "draw"],

  ["wild", 1, "Lion", "Лев", "draw"],
  ["wild", 1, "Tiger", "Тигр", "draw"],
  ["wild", 1, "Elephant", "Слон", "draw"],
  ["wild", 1, "Giraffe", "Жираф", "draw"],
  ["wild", 1, "Bear", "Медведь", "draw"],
  ["wild", 1, "Wolf", "Волк", "draw"],
  ["wild", 1, "Zebra", "Зебра", "draw"],
  ["wild", 1, "Kangaroo", "Кенгуру", "draw"],
  ["wild", 1, "Panda", "Панда", "draw"],
  ["wild", 1, "Monkey", "Обезьяна", "draw"],
  ["wild", 2, "Rhino", "Носорог", "draw"],
  ["wild", 2, "Hippo", "Бегемот", "draw"],
  ["wild", 2, "Gorilla", "Горилла", "draw"],
  ["wild", 2, "Leopard", "Леопард", "draw"],
  ["wild", 2, "Cheetah", "Гепард", "draw"],
  ["wild", 2, "Fox", "Лиса", "draw"],
  ["wild", 2, "Deer", "Олень", "draw"],
  ["wild", 2, "Camel", "Верблюд", "draw"],
  ["wild", 2, "Koala", "Коала", "draw"],
  ["wild", 2, "Sloth", "Ленивец", "draw"],
  ["wild", 2, "Raccoon", "Енот", "draw"],
  ["wild", 2, "Squirrel", "Белка", "draw"],
  ["wild", 2, "Otter", "Выдра", "draw"],
  ["wild", 2, "Bison", "Бизон", "draw"],
  ["wild", 2, "Moose", "Лось", "draw"],
  ["wild", 3, "Hyena", "Гиена", "draw"],
  ["wild", 3, "Badger", "Барсук", "draw"],
  ["wild", 3, "Gazelle", "Газель", "draw"],
  ["wild", 3, "Meerkat", "Сурикат", "draw"],
  ["wild", 3, "Lemur", "Лемур", "draw"],
  ["wild", 3, "Anteater", "Муравьед", "draw"],
  ["wild", 3, "Armadillo", "Броненосец", "draw"],

  ["sea", 1, "Shark", "Акула", "draw"],
  ["sea", 1, "Dolphin", "Дельфин", "draw"],
  ["sea", 1, "Octopus", "Осьминог", "draw"],
  ["sea", 1, "Whale", "Кит", "draw"],
  ["sea", 1, "Crab", "Краб", "draw"],
  ["sea", 1, "Turtle", "Черепаха", "draw"],
  ["sea", 2, "Jellyfish", "Медуза", "draw"],
  ["sea", 2, "Seahorse", "Морской конёк", "draw"],
  ["sea", 2, "Stingray", "Скат", "draw"],
  ["sea", 2, "Starfish", "Морская звезда", "draw"],
  ["sea", 2, "Lobster", "Лобстер", "draw"],
  ["sea", 2, "Seal", "Тюлень", "draw"],
  ["sea", 2, "Walrus", "Морж", "draw"],
  ["sea", 2, "Squid", "Кальмар", "draw"],
  ["sea", 2, "Clownfish", "Рыба-клоун", "draw"],
  ["sea", 2, "Eel", "Угорь", "draw"],
  ["sea", 2, "Swordfish", "Меч-рыба", "draw"],
  ["sea", 2, "Orca", "Косатка", "draw"],
  ["sea", 2, "Narwhal", "Нарвал", "draw"],
  ["sea", 3, "Pufferfish", "Рыба-шар", "draw"],
  ["sea", 3, "Manta Ray", "Манта", "draw"],
  ["sea", 3, "Anglerfish", "Удильщик", "draw"],
  ["sea", 3, "Sea Otter", "Морская выдра", "draw"],
  ["sea", 3, "Sea Urchin", "Морской ёж", "draw"],
  ["sea", 3, "Barracuda", "Барракуда", "draw"],
  ["sea", 3, "Clam", "Моллюск", "draw"],

  ["birds", 1, "Eagle", "Орёл", "draw"],
  ["birds", 1, "Owl", "Сова", "draw"],
  ["birds", 1, "Penguin", "Пингвин", "draw"],
  ["birds", 1, "Flamingo", "Фламинго", "draw"],
  ["birds", 1, "Peacock", "Павлин", "draw"],
  ["birds", 1, "Ostrich", "Страус", "draw"],
  ["birds", 2, "Toucan", "Тукан", "draw"],
  ["birds", 2, "Woodpecker", "Дятел", "draw"],
  ["birds", 2, "Swan", "Лебедь", "draw"],
  ["birds", 2, "Crow", "Ворона", "draw"],
  ["birds", 2, "Pigeon", "Голубь", "draw"],
  ["birds", 2, "Hawk", "Ястреб", "draw"],
  ["birds", 2, "Robin", "Малиновка", "draw"],
  ["birds", 2, "Hummingbird", "Колибри", "draw"],
  ["birds", 2, "Pelican", "Пеликан", "draw"],
  ["birds", 2, "Seagull", "Чайка", "draw"],
  ["birds", 2, "Falcon", "Сокол", "draw"],
  ["birds", 2, "Stork", "Аист", "draw"],
  ["birds", 3, "Vulture", "Гриф", "draw"],
  ["birds", 3, "Kingfisher", "Зимородок", "draw"],
  ["birds", 3, "Puffin", "Тупик", "draw"],
  ["birds", 3, "Cardinal", "Кардинал", "draw"],
  ["birds", 3, "Crane", "Журавль", "draw"],
  ["birds", 3, "Parrot", "Попугай", "draw"],

  ["bugs", 1, "Ant", "Муравей", "draw"],
  ["bugs", 1, "Bee", "Пчела", "draw"],
  ["bugs", 1, "Butterfly", "Бабочка", "draw"],
  ["bugs", 1, "Spider", "Паук", "draw"],
  ["bugs", 1, "Ladybug", "Божья коровка", "draw"],
  ["bugs", 1, "Grasshopper", "Кузнечик", "draw"],
  ["bugs", 2, "Beetle", "Жук", "draw"],
  ["bugs", 2, "Dragonfly", "Стрекоза", "draw"],
  ["bugs", 2, "Mantis", "Богомол", "draw"],
  ["bugs", 2, "Mosquito", "Комар", "draw"],
  ["bugs", 2, "Fly", "Муха", "draw"],
  ["bugs", 2, "Caterpillar", "Гусеница", "draw"],
  ["bugs", 2, "Cockroach", "Таракан", "draw"],
  ["bugs", 2, "Scorpion", "Скорпион", "draw"],
  ["bugs", 2, "Snail", "Улитка", "draw"],
  ["bugs", 2, "Wasp", "Оса", "draw"],
  ["bugs", 2, "Moth", "Мотылёк", "draw"],
  ["bugs", 3, "Centipede", "Сороконожка", "draw"],
  ["bugs", 3, "Cricket", "Сверчок", "draw"],
  ["bugs", 3, "Firefly", "Светлячок", "draw"],
  ["bugs", 3, "Tick", "Клещ", "draw"],
  ["bugs", 3, "Termite", "Термит", "draw"],

  ["dinosaurs", 1, "T-Rex", "Ти-Рекс", "draw"],
  ["dinosaurs", 1, "Triceratops", "Трицератопс", "draw"],
  ["dinosaurs", 1, "Velociraptor", "Велоцираптор", "draw"],
  ["dinosaurs", 1, "Stegosaurus", "Стегозавр", "draw"],
  ["dinosaurs", 2, "Brachiosaurus", "Брахиозавр", "draw"],
  ["dinosaurs", 2, "Pterodactyl", "Птеродактиль", "draw"],
  ["dinosaurs", 2, "Spinosaurus", "Спинозавр", "draw"],
  ["dinosaurs", 2, "Ankylosaurus", "Анкилозавр", "draw"],
  ["dinosaurs", 2, "Diplodocus", "Диплодок", "draw"],
  ["dinosaurs", 2, "Allosaurus", "Аллозавр", "draw"],
  ["dinosaurs", 3, "Brontosaurus", "Бронтозавр", "draw"],
  ["dinosaurs", 3, "Pteranodon", "Птеранодон", "draw"],
  ["dinosaurs", 3, "Iguanodon", "Игуанодон", "draw"],
  ["dinosaurs", 3, "Parasaurolophus", "Паразауролоф", "draw"],

  ["mythical", 1, "Dragon", "Дракон", "draw"],
  ["mythical", 1, "Unicorn", "Единорог", "draw"],
  ["mythical", 1, "Mermaid", "Русалка", "draw"],
  ["mythical", 1, "Phoenix", "Феникс", "draw"],
  ["mythical", 2, "Griffin", "Грифон", "draw"],
  ["mythical", 2, "Centaur", "Кентавр", "draw"],
  ["mythical", 2, "Kraken", "Кракен", "draw"],
  ["mythical", 2, "Werewolf", "Оборотень", "draw"],
  ["mythical", 2, "Yeti", "Йети", "draw"],
  ["mythical", 2, "Pegasus", "Пегас", "draw"],
  ["mythical", 2, "Fairy", "Фея", "draw"],
  ["mythical", 3, "Troll", "Тролль", "draw"],
  ["mythical", 3, "Minotaur", "Минотавр", "draw"],
  ["mythical", 3, "Hydra", "Гидра", "draw"],
  ["mythical", 3, "Cyclops", "Циклоп", "draw"],
  ["mythical", 3, "Chimera", "Химера", "draw"],
]);
