/* Boxing */
addWords("boxing", [
  ["current", 1, "Canelo Álvarez", "Сауль Альварес"],
  ["current", 1, "Oleksandr Usyk", "Александр Усик"],
  ["current", 1, "Tyson Fury", "Тайсон Фьюри"],
  ["current", 1, "Terence Crawford", "Теренс Кроуфорд"],
  ["current", 1, "Artur Beterbiev", "Артур Бетербиев"],
  ["current", 1, "Naoya Inoue", "Наоя Иноуэ"],
  ["current", 1, "Anthony Joshua", "Энтони Джошуа"],
  ["current", 1, "Gervonta Davis", "Джервонта Дэвис"],
  ["current", 1, "Ryan Garcia", "Райан Гарсия"],
  ["current", 1, "Devin Haney", "Девин Хейни"],
  ["current", 1, "Dmitry Bivol", "Дмитрий Бивол"],
  ["current", 1, "Deontay Wilder", "Деонтей Уайлдер"],
  ["current", 1, "Jake Paul", "Джейк Пол"],
  ["current", 2, "Shakur Stevenson", "Шакур Стивенсон"],
  ["current", 2, "Teofimo Lopez", "Теофимо Лопес"],
  ["current", 2, "Errol Spence Jr", "Эррол Спенс мл."],
  ["current", 2, "Jaron Ennis", "Джарон Эннис"],
  ["current", 2, "David Benavidez", "Дэвид Бенавидес"],
  ["current", 2, "Jesse Rodriguez", "Джесси Родригес"],
  ["current", 2, "Vasiliy Lomachenko", "Василий Ломаченко"],
  ["current", 2, "Andy Ruiz Jr", "Энди Руис мл."],
  ["current", 2, "Daniel Dubois", "Дэниэл Дюбуа"],
  ["current", 2, "Chris Eubank Jr", "Крис Юбэнк мл."],
  ["current", 2, "Vergil Ortiz Jr", "Вергил Ортис мл."],
  ["current", 2, "Regis Prograis", "Реджис Прогрей"],
  ["current", 2, "Jermell Charlo", "Джермелл Чарло"],
  ["current", 2, "Emanuel Navarrete", "Эмануэль Наваррете"],
  ["current", 3, "Jose Ramirez", "Хосе Рамирес"],
  ["current", 3, "Isaac Cruz", "Исаак Крус"],
  ["current", 3, "Robeisy Ramírez", "Робейси Рамирес"],
  ["current", 3, "Zhilei Zhang", "Чжилэй Чжан"],
  ["current", 3, "Junto Nakatani", "Дзюнто Накатани"],
  ["current", 3, "Nick Ball", "Ник Болл"],
  ["current", 3, "Josh Taylor", "Джош Тейлор"],
  ["current", 3, "Stephen Fulton", "Стивен Фултон"],
  ["current", 3, "Lawrence Okolie", "Лоуренс Околие"],
  ["current", 3, "Nonito Donaire", "Нонито Донэйр"],
  ["current", 3, "Leigh Wood", "Ли Вуд"],
  ["current", 3, "Gary Russell Jr", "Гэри Расселл мл."],
  ["current", 3, "Luis Ortiz", "Луис Ортис"],

  ["legends", 1, "Muhammad Ali", "Мохаммед Али"],
  ["legends", 1, "Mike Tyson", "Майк Тайсон"],
  ["legends", 1, "Floyd Mayweather Jr", "Флойд Мейуэзер мл."],
  ["legends", 1, "Manny Pacquiao", "Мэнни Пакьяо"],
  ["legends", 1, "George Foreman", "Джордж Форман"],
  ["legends", 1, "Joe Frazier", "Джо Фрейзер"],
  ["legends", 1, "Evander Holyfield", "Эвандер Холифилд"],
  ["legends", 1, "Lennox Lewis", "Леннокс Льюис"],
  ["legends", 1, "Rocky Marciano", "Рокки Марчиано"],
  ["legends", 1, "Sugar Ray Robinson", "Шугар Рэй Робинсон"],
  ["legends", 1, "Sugar Ray Leonard", "Шугар Рэй Леонард"],
  ["legends", 1, "Marvin Hagler", "Марвин Хаглер"],
  ["legends", 1, "Roy Jones Jr", "Рой Джонс мл."],
  ["legends", 1, "Oscar De La Hoya", "Оскар Де Ла Хойя"],
  ["legends", 1, "Roberto Durán", "Роберто Дюран"],
  ["legends", 2, "Joe Louis", "Джо Луис"],
  ["legends", 2, "Jack Dempsey", "Джек Демпси"],
  ["legends", 2, "Tommy Hearns", "Томми Хёрнс"],
  ["legends", 2, "Larry Holmes", "Ларри Холмс"],
  ["legends", 2, "Bernard Hopkins", "Бернард Хопкинс"],
  ["legends", 2, "Julio César Chávez", "Хулио Сесар Чавес"],
  ["legends", 2, "Vitali Klitschko", "Виталий Кличко"],
  ["legends", 2, "Wladimir Klitschko", "Владимир Кличко"],
  ["legends", 2, "Felix Trinidad", "Феликс Тринидад"],
  ["legends", 2, "Arturo Gatti", "Артуро Гатти"],
  ["legends", 2, "Ricky Hatton", "Рики Хаттон"],
  ["legends", 2, "Joe Calzaghe", "Джо Кальцаге"],
  ["legends", 2, "Pernell Whitaker", "Пернелл Уитакер"],
  ["legends", 2, "Carlos Monzón", "Карлос Монсон"],
  ["legends", 2, "Riddick Bowe", "Риддик Боу"],
  ["legends", 2, "Erik Morales", "Эрик Моралес"],
  ["legends", 2, "Marco Antonio Barrera", "Марко Антонио Баррера"],
  ["legends", 3, "Archie Moore", "Арчи Мур"],
  ["legends", 3, "Sonny Liston", "Сонни Листон"],
  ["legends", 3, "Jake LaMotta", "Джейк ЛаМотта"],
  ["legends", 3, "Floyd Patterson", "Флойд Паттерсон"],
  ["legends", 3, "Henry Armstrong", "Генри Армстронг"],
  ["legends", 3, "Salvador Sánchez", "Сальвадор Санчес"],
  ["legends", 3, "Alexis Argüello", "Алексис Аргельо"],
  ["legends", 3, "Aaron Pryor", "Аарон Прайор"],
  ["legends", 3, "Wilfredo Gómez", "Вильфредо Гомес"],
  ["legends", 3, "Azumah Nelson", "Азума Нельсон"],
  ["legends", 3, "Carlos Zárate", "Карлос Сарате"],
  ["legends", 3, "Éder Jofre", "Эдер Жофре"],
  ["legends", 3, "Pernell Whitaker", "Пернелл Уитакер"],

]);
