/* Car Brands */
addWords("cars", [
  ["luxury", 1, "Mercedes-Benz", "Мерседес", "draw"],
  ["luxury", 1, "BMW", "БМВ", "draw"],
  ["luxury", 1, "Audi", "Ауди", "draw"],
  ["luxury", 1, "Lexus", "Лексус", "draw"],
  ["luxury", 1, "Cadillac", "Кадиллак", "draw"],
  ["luxury", 1, "Lincoln", "Линкольн", "draw"],
  ["luxury", 2, "Bentley", "Бентли", "draw"],
  ["luxury", 2, "Rolls-Royce", "Роллс-Ройс", "draw"],
  ["luxury", 2, "Jaguar", "Ягуар", "draw"],
  ["luxury", 2, "Land Rover", "Лэнд Ровер", "draw"],
  ["luxury", 2, "Range Rover", "Рейндж Ровер", "draw"],
  ["luxury", 2, "Volvo", "Вольво", "draw"],
  ["luxury", 2, "Acura", "Акура", "draw"],
  ["luxury", 2, "Infiniti", "Инфинити", "draw"],
  ["luxury", 2, "Genesis", "Дженезис", "draw"],
  ["luxury", 3, "Maserati", "Мазерати", "draw"],
  ["luxury", 3, "Maybach", "Майбах", "draw"],
  ["luxury", 3, "Alfa Romeo", "Альфа Ромео", "draw"],
  ["luxury", 3, "DS Automobiles", "ДС Отомобиль", "draw"],
  ["luxury", 3, "Lancia", "Ланча", "draw"],

  ["sports", 1, "Ferrari", "Феррари", "draw"],
  ["sports", 1, "Lamborghini", "Ламборгини", "draw"],
  ["sports", 1, "Porsche", "Порше", "draw"],
  ["sports", 1, "Corvette", "Корвет", "draw"],
  ["sports", 2, "McLaren", "Макларен", "draw"],
  ["sports", 2, "Bugatti", "Бугатти", "draw"],
  ["sports", 2, "Aston Martin", "Астон Мартин", "draw"],
  ["sports", 2, "Lotus", "Лотус", "draw"],
  ["sports", 2, "Alpine", "Альпин", "draw"],
  ["sports", 2, "Shelby", "Шелби", "draw"],
  ["sports", 2, "Dodge Viper", "Додж Вайпер", "draw"],
  ["sports", 3, "Koenigsegg", "Кёнигсегг", "draw"],
  ["sports", 3, "Pagani", "Пагани", "draw"],
  ["sports", 3, "Rimac", "Римак", "draw"],
  ["sports", 3, "Hennessey", "Хеннесси", "draw"],
  ["sports", 3, "Ariel", "Ариэль", "draw"],
  ["sports", 3, "BAC Mono", "БАК Моно", "draw"],
  ["sports", 3, "SSC", "ССК", "draw"],
  ["sports", 3, "Radical", "Рэдикал", "draw"],

  ["everyday", 1, "Toyota", "Тойота", "draw"],
  ["everyday", 1, "Honda", "Хонда", "draw"],
  ["everyday", 1, "Ford", "Форд", "draw"],
  ["everyday", 1, "Volkswagen", "Фольксваген", "draw"],
  ["everyday", 1, "Hyundai", "Хёндай", "draw"],
  ["everyday", 1, "Kia", "Киа", "draw"],
  ["everyday", 1, "Nissan", "Ниссан", "draw"],
  ["everyday", 1, "Chevrolet", "Шевроле", "draw"],
  ["everyday", 1, "Mazda", "Мазда", "draw"],
  ["everyday", 1, "Subaru", "Субару", "draw"],
  ["everyday", 1, "Jeep", "Джип", "draw"],
  ["everyday", 1, "Mini", "Мини", "draw"],
  ["everyday", 2, "Renault", "Рено", "draw"],
  ["everyday", 2, "Peugeot", "Пежо", "draw"],
  ["everyday", 2, "Skoda", "Шкода", "draw"],
  ["everyday", 2, "Fiat", "Фиат", "draw"],
  ["everyday", 2, "Suzuki", "Судзуки", "draw"],
  ["everyday", 2, "Mitsubishi", "Мицубиси", "draw"],
  ["everyday", 2, "Opel", "Опель", "draw"],
  ["everyday", 2, "Citroën", "Ситроен", "draw"],
  ["everyday", 2, "Seat", "Сеат", "draw"],
  ["everyday", 2, "Chrysler", "Крайслер", "draw"],
  ["everyday", 3, "Dacia", "Дачия", "draw"],
  ["everyday", 3, "Lada", "Лада", "draw"],

  ["ev", 1, "Tesla", "Тесла", "draw"],
  ["ev", 2, "Rivian", "Ривиан", "draw"],
  ["ev", 2, "Lucid", "Лусид", "draw"],
  ["ev", 2, "BYD", "БИД", "draw"],
  ["ev", 2, "Polestar", "Полстар", "draw"],
  ["ev", 2, "NIO", "Нио", "draw"],
  ["ev", 2, "Xpeng", "Сяопэн", "draw"],
  ["ev", 2, "Li Auto", "Ли Ауто", "draw"],
  ["ev", 3, "Fisker", "Фискер", "draw"],
  ["ev", 3, "Zeekr", "Зикр", "draw"],
  ["ev", 3, "VinFast", "ВинФаст", "draw"],
  ["ev", 3, "Canoo", "Кану", "draw"],
  ["ev", 3, "Arrival", "Эрривал", "draw"],
  ["ev", 3, "Faraday Future", "Фарадей Фьючер", "draw"],
  ["ev", 3, "Lightyear", "Лайтиер", "draw"],

  ["classic", 1, "Pontiac", "Понтиак", "draw"],
  ["classic", 1, "Dodge", "Додж", "draw"],
  ["classic", 1, "Buick", "Бьюик", "draw"],
  ["classic", 1, "Hummer", "Хаммер", "draw"],
  ["classic", 2, "Oldsmobile", "Олдсмобиль", "draw"],
  ["classic", 2, "Plymouth", "Плимут", "draw"],
  ["classic", 2, "Saab", "Сааб", "draw"],
  ["classic", 2, "DeLorean", "ДеЛориан", "draw"],
  ["classic", 2, "Datsun", "Датсун", "draw"],
  ["classic", 2, "AMC", "АМС", "draw"],
  ["classic", 2, "De Tomaso", "Де Томасо", "draw"],
  ["classic", 3, "Studebaker", "Студебекер", "draw"],
  ["classic", 3, "Trabant", "Трабант", "draw"],
  ["classic", 3, "Packard", "Паккард", "draw"],
  ["classic", 3, "Hudson", "Хадсон", "draw"],
  ["classic", 3, "Nash", "Нэш", "draw"],
  ["classic", 3, "Kaiser", "Кайзер", "draw"],
  ["classic", 3, "Cord", "Корд", "draw"],
]);
