/* Famous People (easy-heavy) */
addWords("famous", [
  ["actors", 1, "Leonardo DiCaprio", "Леонардо ДиКаприо"],
  ["actors", 1, "Tom Hanks", "Том Хэнкс"],
  ["actors", 1, "Tom Cruise", "Том Круз"],
  ["actors", 1, "Brad Pitt", "Брэд Питт"],
  ["actors", 1, "Will Smith", "Уилл Смит"],
  ["actors", 1, "Scarlett Johansson", "Скарлетт Йоханссон"],
  ["actors", 1, "Angelina Jolie", "Анджелина Джоли"],
  ["actors", 1, "Johnny Depp", "Джонни Депп"],
  ["actors", 1, "Morgan Freeman", "Морган Фриман"],
  ["actors", 1, "Robert Downey Jr", "Роберт Дауни мл."],
  ["actors", 1, "Dwayne Johnson", "Дуэйн Джонсон"],
  ["actors", 1, "Arnold Schwarzenegger", "Арнольд Шварценеггер"],
  ["actors", 1, "Sylvester Stallone", "Сильвестр Сталлоне"],
  ["actors", 1, "Denzel Washington", "Дензел Вашингтон"],
  ["actors", 1, "Keanu Reeves", "Киану Ривз"],
  ["actors", 1, "Meryl Streep", "Мерил Стрип"],
  ["actors", 1, "Jackie Chan", "Джеки Чан"],
  ["actors", 1, "Jim Carrey", "Джим Керри"],
  ["actors", 1, "Hugh Jackman", "Хью Джекман"],
  ["actors", 1, "Natalie Portman", "Натали Портман"],
  ["actors", 1, "Anne Hathaway", "Энн Хэтэуэй"],
  ["actors", 1, "Jennifer Lawrence", "Дженнифер Лоуренс"],
  ["actors", 1, "Margot Robbie", "Марго Робби"],
  ["actors", 1, "Zendaya", "Зендея"],
  ["actors", 1, "Emma Stone", "Эмма Стоун"],
  ["actors", 1, "Ryan Reynolds", "Райан Рейнольдс"],
  ["actors", 1, "Chris Evans", "Крис Эванс"],
  ["actors", 1, "Chris Hemsworth", "Крис Хемсворт"],
  ["actors", 1, "Samuel L. Jackson", "Сэмюэл Л. Джексон"],
  ["actors", 1, "Gal Gadot", "Галь Гадот"],
  ["actors", 2, "Ryan Gosling", "Райан Гослинг"],
  ["actors", 2, "Timothée Chalamet", "Тимоте Шаламе"],
  ["actors", 2, "Tom Holland", "Том Холланд"],
  ["actors", 2, "Robert Pattinson", "Роберт Паттинсон"],
  ["actors", 2, "Charlize Theron", "Шарлиз Терон"],
  ["actors", 2, "Cate Blanchett", "Кейт Бланшетт"],
  ["actors", 2, "Will Ferrell", "Уилл Феррелл"],
  ["actors", 3, "Lupita Nyong'o", "Лупита Нионго"],

  ["musicians", 1, "Michael Jackson", "Майкл Джексон"],
  ["musicians", 1, "Taylor Swift", "Тейлор Свифт"],
  ["musicians", 1, "Beyoncé", "Бейонсе"],
  ["musicians", 1, "Rihanna", "Рианна"],
  ["musicians", 1, "Elvis Presley", "Элвис Пресли"],
  ["musicians", 1, "Madonna", "Мадонна"],
  ["musicians", 1, "Adele", "Адель"],
  ["musicians", 1, "Lady Gaga", "Леди Гага"],
  ["musicians", 1, "Eminem", "Эминем"],
  ["musicians", 1, "Bob Marley", "Боб Марли"],
  ["musicians", 1, "Freddie Mercury", "Фредди Меркьюри"],
  ["musicians", 1, "John Lennon", "Джон Леннон"],
  ["musicians", 1, "Drake", "Дрейк"],
  ["musicians", 1, "Ariana Grande", "Ариана Гранде"],
  ["musicians", 1, "Justin Bieber", "Джастин Бибер"],
  ["musicians", 1, "Ed Sheeran", "Эд Ширан"],
  ["musicians", 1, "Elton John", "Элтон Джон"],
  ["musicians", 1, "Whitney Houston", "Уитни Хьюстон"],
  ["musicians", 1, "Mariah Carey", "Мэрайя Кэри"],
  ["musicians", 1, "Katy Perry", "Кэти Перри"],
  ["musicians", 1, "Snoop Dogg", "Снуп Догг"],
  ["musicians", 1, "Shakira", "Шакира"],
  ["musicians", 1, "Selena Gomez", "Селена Гомес"],
  ["musicians", 1, "Miley Cyrus", "Майли Сайрус"],
  ["musicians", 1, "Bruno Mars", "Бруно Марс"],
  ["musicians", 2, "Kanye West", "Канье Уэст"],
  ["musicians", 2, "The Weeknd", "Уикнд"],
  ["musicians", 2, "Billie Eilish", "Билли Айлиш"],
  ["musicians", 2, "Dua Lipa", "Дуа Липа"],
  ["musicians", 2, "Bad Bunny", "Бэд Банни"],
  ["musicians", 2, "Harry Styles", "Гарри Стайлс"],
  ["musicians", 2, "Nicki Minaj", "Ники Минаж"],
  ["musicians", 2, "Post Malone", "Пост Мэлоун"],
  ["musicians", 2, "Travis Scott", "Трэвис Скотт"],
  ["musicians", 2, "Stevie Wonder", "Стиви Уандер"],
  ["musicians", 3, "Cardi B", "Карди Би"],
  ["musicians", 3, "Olivia Rodrigo", "Оливия Родриго"],
  ["musicians", 3, "SZA", "СЗА"],

  ["athletes", 1, "Lionel Messi", "Лионель Месси"],
  ["athletes", 1, "Cristiano Ronaldo", "Криштиану Роналду"],
  ["athletes", 1, "LeBron James", "ЛеБрон Джеймс"],
  ["athletes", 1, "Michael Jordan", "Майкл Джордан"],
  ["athletes", 1, "Muhammad Ali", "Мухаммед Али"],
  ["athletes", 1, "Usain Bolt", "Усэйн Болт"],
  ["athletes", 1, "Serena Williams", "Серена Уильямс"],
  ["athletes", 1, "Tiger Woods", "Тайгер Вудс"],
  ["athletes", 1, "Tom Brady", "Том Брэди"],
  ["athletes", 1, "Roger Federer", "Роджер Федерер"],
  ["athletes", 1, "Kobe Bryant", "Коби Брайант"],
  ["athletes", 1, "Pelé", "Пеле"],
  ["athletes", 1, "Mike Tyson", "Майк Тайсон"],
  ["athletes", 1, "David Beckham", "Дэвид Бекхэм"],
  ["athletes", 1, "Maradona", "Марадона"],
  ["athletes", 1, "Neymar", "Неймар"],
  ["athletes", 1, "Lewis Hamilton", "Льюис Хэмилтон"],
  ["athletes", 2, "Kylian Mbappé", "Килиан Мбаппе"],
  ["athletes", 2, "Rafael Nadal", "Рафаэль Надаль"],
  ["athletes", 2, "Novak Djokovic", "Новак Джокович"],
  ["athletes", 2, "Floyd Mayweather", "Флойд Мэйуэзер"],
  ["athletes", 2, "Conor McGregor", "Конор МакГрегор"],
  ["athletes", 2, "Shaquille O'Neal", "Шакил О'Нил"],
  ["athletes", 2, "Stephen Curry", "Стефен Карри"],
  ["athletes", 2, "Michael Phelps", "Майкл Фелпс"],
  ["athletes", 2, "Simone Biles", "Симона Байлз"],
  ["athletes", 2, "Zlatan Ibrahimović", "Златан Ибрагимович"],
  ["athletes", 2, "Naomi Osaka", "Наоми Осака"],
  ["athletes", 3, "Giannis Antetokounmpo", "Яннис Адетокумбо"],
  ["athletes", 3, "Eliud Kipchoge", "Элиуд Кипчоге"],

  ["tech", 1, "Elon Musk", "Илон Маск"],
  ["tech", 1, "Bill Gates", "Билл Гейтс"],
  ["tech", 1, "Steve Jobs", "Стив Джобс"],
  ["tech", 1, "Mark Zuckerberg", "Марк Цукерберг"],
  ["tech", 1, "Jeff Bezos", "Джефф Безос"],
  ["tech", 1, "Warren Buffett", "Уоррен Баффетт"],
  ["tech", 1, "Oprah Winfrey", "Опра Уинфри"],
  ["tech", 1, "Walt Disney", "Уолт Дисней"],
  ["tech", 1, "Thomas Edison", "Томас Эдисон"],
  ["tech", 1, "Nikola Tesla", "Никола Тесла"],
  ["tech", 1, "Henry Ford", "Генри Форд"],
  ["tech", 2, "Tim Cook", "Тим Кук"],
  ["tech", 2, "Sam Altman", "Сэм Альтман"],
  ["tech", 2, "Jensen Huang", "Дженсен Хуан"],
  ["tech", 2, "Larry Page", "Ларри Пейдж"],
  ["tech", 2, "Sergey Brin", "Сергей Брин"],
  ["tech", 2, "Jack Ma", "Джек Ма"],
  ["tech", 2, "Richard Branson", "Ричард Брэнсон"],
  ["tech", 2, "Mark Cuban", "Марк Кьюбан"],
  ["tech", 2, "Larry Ellison", "Ларри Эллисон"],
  ["tech", 3, "Sundar Pichai", "Сундар Пичаи"],
  ["tech", 3, "Reed Hastings", "Рид Хастингс"],
  ["tech", 3, "Satya Nadella", "Сатья Наделла"],

  ["influencers", 1, "MrBeast", "МрБист"],
  ["influencers", 1, "PewDiePie", "ПьюДиПай"],
  ["influencers", 1, "Kim Kardashian", "Ким Кардашьян"],
  ["influencers", 1, "Kylie Jenner", "Кайли Дженнер"],
  ["influencers", 1, "Khaby Lame", "Хаби Лам"],
  ["influencers", 1, "Charli D'Amelio", "Чарли Д'Амелио"],
  ["influencers", 1, "Logan Paul", "Логан Пол"],
  ["influencers", 2, "Jake Paul", "Джейк Пол"],
  ["influencers", 2, "KSI", "КСИ"],
  ["influencers", 2, "IShowSpeed", "АйШоуСпид"],
  ["influencers", 2, "David Dobrik", "Дэвид Добрик"],
  ["influencers", 2, "Markiplier", "Маркиплиер"],
  ["influencers", 2, "Ninja", "Ниндзя"],
  ["influencers", 2, "Kai Cenat", "Кай Сенат"],
  ["influencers", 2, "Pokimane", "Покимейн"],
  ["influencers", 2, "Emma Chamberlain", "Эмма Чемберлен"],
  ["influencers", 2, "Addison Rae", "Эддисон Рэй"],
  ["influencers", 2, "Bella Poarch", "Белла Поарч"],
  ["influencers", 3, "James Charles", "Джеймс Чарльз"],
  ["influencers", 3, "Jeffree Star", "Джефри Стар"],
  ["influencers", 3, "Zach King", "Зак Кинг"],

  ["leaders", 1, "Barack Obama", "Барак Обама"],
  ["leaders", 1, "Donald Trump", "Дональд Трамп"],
  ["leaders", 1, "Vladimir Putin", "Владимир Путин"],
  ["leaders", 1, "Queen Elizabeth II", "Королева Елизавета II"],
  ["leaders", 1, "Nelson Mandela", "Нельсон Мандела"],
  ["leaders", 1, "Winston Churchill", "Уинстон Черчилль"],
  ["leaders", 1, "Mahatma Gandhi", "Махатма Ганди"],
  ["leaders", 1, "JFK", "Джон Кеннеди"],
  ["leaders", 1, "Abraham Lincoln", "Авраам Линкольн"],
  ["leaders", 1, "Napoleon Bonaparte", "Наполеон Бонапарт"],
  ["leaders", 1, "Martin Luther King", "Мартин Лютер Кинг"],
  ["leaders", 1, "George Washington", "Джордж Вашингтон"],
  ["leaders", 2, "Angela Merkel", "Ангела Меркель"],
  ["leaders", 2, "Margaret Thatcher", "Маргарет Тэтчер"],
  ["leaders", 2, "Volodymyr Zelensky", "Владимир Зеленский"],
  ["leaders", 2, "Pope Francis", "Папа Франциск"],
  ["leaders", 2, "Dalai Lama", "Далай-лама"],
  ["leaders", 2, "Joe Biden", "Джо Байден"],
  ["leaders", 2, "King Charles III", "Король Карл III"],
  ["leaders", 2, "Charles de Gaulle", "Шарль де Голль"],
  ["leaders", 2, "Fidel Castro", "Фидель Кастро"],
  ["leaders", 3, "Xi Jinping", "Си Цзиньпин"],
  ["leaders", 3, "Emmanuel Macron", "Эммануэль Макрон"],
  ["leaders", 3, "Mao Zedong", "Мао Цзэдун"],
]);
