/* Films (with years) */
addWords("films", [
  // [ subgroupId, difficulty(1-3), "EN title", "RU title", YEAR ]

  // classics — 80s/90s
  ["classics", 1, "The Terminator", "Терминатор", 1984],
  ["classics", 1, "Jurassic Park", "Парк Юрского периода", 1993],
  ["classics", 1, "Back to the Future", "Назад в будущее", 1985],
  ["classics", 1, "Titanic", "Титаник", 1997],
  ["classics", 1, "The Matrix", "Матрица", 1999],
  ["classics", 1, "Forrest Gump", "Форрест Гамп", 1994],
  ["classics", 1, "Die Hard", "Крепкий орешек", 1988],
  ["classics", 1, "Home Alone", "Один дома", 1990],
  ["classics", 1, "Ghostbusters", "Охотники за привидениями", 1984],
  ["classics", 1, "Rocky", "Рокки", 1976],
  ["classics", 2, "Pulp Fiction", "Криминальное чтиво", 1994],
  ["classics", 2, "Goodfellas", "Славные парни", 1990],
  ["classics", 2, "The Shawshank Redemption", "Побег из Шоушенка", 1994],
  ["classics", 2, "Aliens", "Чужие", 1986],
  ["classics", 2, "E.T.", "Инопланетянин", 1982],
  ["classics", 2, "The Silence of the Lambs", "Молчание ягнят", 1991],
  ["classics", 2, "Braveheart", "Храброе сердце", 1995],
  ["classics", 3, "Blade Runner", "Бегущий по лезвию", 1982],
  ["classics", 3, "Full Metal Jacket", "Цельнометаллическая оболочка", 1987],
  ["classics", 3, "Apocalypse Now", "Апокалипсис сегодня", 1979],

  // modern — 2000s+ blockbusters
  ["modern", 1, "Avatar", "Аватар", 2009],
  ["modern", 1, "The Avengers", "Мстители", 2012],
  ["modern", 1, "Inception", "Начало", 2010],
  ["modern", 1, "Interstellar", "Интерстеллар", 2014],
  ["modern", 1, "Dune", "Дюна", 2021],
  ["modern", 1, "Oppenheimer", "Оппенгеймер", 2023],
  ["modern", 1, "Barbie", "Барби", 2023],
  ["modern", 1, "Joker", "Джокер", 2019],
  ["modern", 1, "The Dark Knight", "Тёмный рыцарь", 2008],
  ["modern", 1, "Gladiator", "Гладиатор", 2000],
  ["modern", 2, "Mad Max: Fury Road", "Безумный Макс: Дорога ярости", 2015],
  ["modern", 2, "La La Land", "Ла-Ла Ленд", 2016],
  ["modern", 2, "Parasite", "Паразиты", 2019],
  ["modern", 2, "Everything Everywhere All at Once", "Всё везде и сразу", 2022],
  ["modern", 2, "The Revenant", "Выживший", 2015],
  ["modern", 2, "Black Panther", "Чёрная пантера", 2018],
  ["modern", 2, "Spider-Man: No Way Home", "Человек-паук: Нет пути домой", 2021],
  ["modern", 3, "Tenet", "Довод", 2020],
  ["modern", 3, "The Lighthouse", "Маяк", 2019],

  // korean
  ["korean", 1, "Parasite", "Паразиты", 2019],
  ["korean", 1, "Train to Busan", "Поезд в Пусан", 2016],
  ["korean", 2, "Oldboy", "Олдбой", 2003],
  ["korean", 2, "The Handmaiden", "Служанка", 2016],
  ["korean", 2, "Memories of Murder", "Воспоминания об убийстве", 2003],
  ["korean", 2, "Burning", "Пылающий", 2018],
  ["korean", 2, "Snowpiercer", "Сквозь снег", 2013],
  ["korean", 2, "A Taxi Driver", "Таксист", 2017],
  ["korean", 2, "The Wailing", "Вопль", 2016],
  ["korean", 2, "A Tale of Two Sisters", "Две сестры", 2003],
  ["korean", 3, "I Saw the Devil", "Я видел дьявола", 2010],
  ["korean", 3, "Mother", "Мать", 2009],
  ["korean", 3, "Poetry", "Поэзия", 2010],
  ["korean", 3, "The Thieves", "Воры", 2012],
  ["korean", 3, "Along with the Gods", "Вместе с богами", 2017],

  // animation — Pixar / Disney / Ghibli
  ["animation", 1, "Toy Story", "История игрушек", 1995],
  ["animation", 1, "Frozen", "Холодное сердце", 2013],
  ["animation", 1, "Shrek", "Шрек", 2001],
  ["animation", 1, "The Lion King", "Король Лев", 1994],
  ["animation", 1, "Spirited Away", "Унесённые призраками", 2001],
  ["animation", 1, "Finding Nemo", "В поисках Немо", 2003],
  ["animation", 1, "Moana", "Моана", 2016],
  ["animation", 2, "Coco", "Тайна Коко", 2017],
  ["animation", 2, "Up", "Вверх", 2009],
  ["animation", 2, "Inside Out", "Головоломка", 2015],
  ["animation", 2, "Spider-Man: Into the Spider-Verse", "Человек-паук: Через вселенные", 2018],
  ["animation", 2, "How to Train Your Dragon", "Как приручить дракона", 2010],
  ["animation", 2, "Ratatouille", "Рататуй", 2007],
  ["animation", 2, "WALL-E", "ВАЛЛ-И", 2008],
  ["animation", 2, "Zootopia", "Зверополис", 2016],
  ["animation", 3, "Princess Mononoke", "Принцесса Мононоке", 1997],
  ["animation", 3, "Grave of the Fireflies", "Могила светлячков", 1988],
  ["animation", 3, "The Tale of the Princess Kaguya", "Сказание о принцессе Кагуя", 2013],

  // horror
  ["horror", 1, "The Shining", "Сияние", 1980],
  ["horror", 1, "It", "Оно", 2017],
  ["horror", 1, "The Conjuring", "Заклятие", 2013],
  ["horror", 1, "Get Out", "Прочь", 2017],
  ["horror", 1, "A Nightmare on Elm Street", "Кошмар на улице Вязов", 1984],
  ["horror", 1, "The Exorcist", "Изгоняющий дьявола", 1973],
  ["horror", 1, "Halloween", "Хэллоуин", 1978],
  ["horror", 1, "Scream", "Крик", 1996],
  ["horror", 2, "Saw", "Пила", 2004],
  ["horror", 2, "The Ring", "Звонок", 2002],
  ["horror", 2, "Hereditary", "Реинкарнация", 2018],
  ["horror", 2, "Midsommar", "Солнцестояние", 2019],
  ["horror", 2, "A Quiet Place", "Тихое место", 2018],
  ["horror", 3, "The Babadook", "Бабадук", 2014],
  ["horror", 3, "The Witch", "Ведьма", 2015],
  ["horror", 3, "Suspiria", "Суспирия", 1977],
  ["horror", 3, "Mandy", "Мэнди", 2018],

  // franchises — action series, first/most famous film's year
  ["franchises", 1, "Star Wars", "Звёздные войны", 1977],
  ["franchises", 1, "James Bond", "Джеймс Бонд", 1962],
  ["franchises", 1, "Mission: Impossible", "Миссия: невыполнима", 1996],
  ["franchises", 1, "Fast & Furious", "Форсаж", 2001],
  ["franchises", 1, "Indiana Jones", "Индиана Джонс", 1981],
  ["franchises", 1, "John Wick", "Джон Уик", 2014],
  ["franchises", 1, "Pirates of the Caribbean", "Пираты Карибского моря", 2003],
  ["franchises", 1, "Jurassic World", "Мир Юрского периода", 2015],
  ["franchises", 2, "The Hunger Games", "Голодные игры", 2012],
  ["franchises", 2, "Transformers", "Трансформеры", 2007],
  ["franchises", 2, "Kingsman: The Secret Service", "Kingsman: Секретная служба", 2014],
  ["franchises", 2, "Ocean's Eleven", "Одиннадцать друзей Оушена", 2001],
  ["franchises", 2, "Taken", "Заложница", 2008],
  ["franchises", 3, "The Bourne Identity", "Идентификация Борна", 2002],
  ["franchises", 3, "The Expendables", "Неудержимые", 2010],
  ["franchises", 3, "Ip Man", "Ип Ман", 2008],

  // prestige — Oscar / arthouse acclaimed
  ["prestige", 1, "The Godfather", "Крёстный отец", 1972],
  ["prestige", 1, "Schindler's List", "Список Шиндлера", 1993],
  ["prestige", 1, "Forrest Gump", "Форрест Гамп", 1994],
  ["prestige", 2, "The Departed", "Отступники", 2006],
  ["prestige", 2, "No Country for Old Men", "Старикам тут не место", 2007],
  ["prestige", 2, "12 Years a Slave", "12 лет рабства", 2013],
  ["prestige", 2, "Moonlight", "Лунный свет", 2016],
  ["prestige", 2, "Birdman", "Бёрдмэн", 2014],
  ["prestige", 2, "Nomadland", "Земля кочевников", 2020],
  ["prestige", 2, "The Shape of Water", "Форма воды", 2017],
  ["prestige", 2, "Whiplash", "Одержимость", 2014],
  ["prestige", 2, "Parasite", "Паразиты", 2019],
  ["prestige", 3, "There Will Be Blood", "Нефть", 2007],
  ["prestige", 3, "Boyhood", "Отрочество", 2014],
  ["prestige", 3, "Roma", "Рома", 2018],
  ["prestige", 3, "Amour", "Любовь", 2012],
  ["prestige", 3, "Drive My Car", "Сядь за руль моей машины", 2021],
]);
