/* Food & Drink */
addWords("food", [
  ["fastfood", 1, "Pizza", "Пицца", "draw"],
  ["fastfood", 1, "Burger", "Бургер", "draw"],
  ["fastfood", 1, "French Fries", "Картофель фри", "draw"],
  ["fastfood", 1, "Hot Dog", "Хот-дог", "draw"],
  ["fastfood", 1, "Sandwich", "Сэндвич", "draw"],
  ["fastfood", 1, "Donut", "Пончик", "draw"],
  ["fastfood", 1, "Taco", "Тако", "draw"],
  ["fastfood", 1, "Nuggets", "Наггетсы", "draw"],
  ["fastfood", 2, "Fried Chicken", "Жареная курица", "draw"],
  ["fastfood", 2, "Kebab", "Кебаб", "draw"],
  ["fastfood", 2, "Burrito", "Буррито", "draw"],
  ["fastfood", 2, "Wrap", "Ролл-сэндвич", "draw"],
  ["fastfood", 2, "Onion Rings", "Луковые кольца", "draw"],
  ["fastfood", 2, "Milkshake", "Молочный коктейль", "draw"],
  ["fastfood", 2, "Quesadilla", "Кесадилья", "draw"],
  ["fastfood", 2, "Gyro", "Гирос", "draw"],
  ["fastfood", 2, "Sushi", "Суши", "draw"],
  ["fastfood", 3, "Fish and Chips", "Рыба и чипсы", "draw"],
  ["fastfood", 3, "Corn Dog", "Корн-дог", "draw"],
  ["fastfood", 3, "Poutine", "Путин (блюдо)", "draw"],
  ["fastfood", 3, "Banh Mi", "Бань-ми", "draw"],
  ["fastfood", 3, "Chimichanga", "Чимичанга", "draw"],
  ["fastfood", 3, "Sloppy Joe", "Слоппи Джо", "draw"],
  ["fastfood", 3, "Croque-Monsieur", "Крок-месье", "draw"],
  ["fastfood", 3, "Arepa", "Арепа", "draw"],
  ["fastfood", 3, "Smash Burger", "Смэш-бургер", "draw"],

  ["fruitveg", 1, "Apple", "Яблоко", "draw"],
  ["fruitveg", 1, "Banana", "Банан", "draw"],
  ["fruitveg", 1, "Watermelon", "Арбуз", "draw"],
  ["fruitveg", 1, "Carrot", "Морковь", "draw"],
  ["fruitveg", 1, "Strawberry", "Клубника", "draw"],
  ["fruitveg", 1, "Orange", "Апельсин", "draw"],
  ["fruitveg", 1, "Potato", "Картофель", "draw"],
  ["fruitveg", 1, "Tomato", "Помидор", "draw"],
  ["fruitveg", 1, "Corn", "Кукуруза", "draw"],
  ["fruitveg", 1, "Grapes", "Виноград", "draw"],
  ["fruitveg", 2, "Avocado", "Авокадо", "draw"],
  ["fruitveg", 2, "Pineapple", "Ананас", "draw"],
  ["fruitveg", 2, "Broccoli", "Брокколи", "draw"],
  ["fruitveg", 2, "Eggplant", "Баклажан", "draw"],
  ["fruitveg", 2, "Mango", "Манго", "draw"],
  ["fruitveg", 2, "Cucumber", "Огурец", "draw"],
  ["fruitveg", 2, "Pumpkin", "Тыква", "draw"],
  ["fruitveg", 2, "Cherry", "Вишня", "draw"],
  ["fruitveg", 2, "Lemon", "Лимон", "draw"],
  ["fruitveg", 2, "Mushroom", "Гриб", "draw"],
  ["fruitveg", 2, "Peach", "Персик", "draw"],
  ["fruitveg", 2, "Onion", "Лук", "draw"],
  ["fruitveg", 2, "Pepper", "Перец", "draw"],
  ["fruitveg", 2, "Pear", "Груша", "draw"],
  ["fruitveg", 3, "Kiwi", "Киви", "draw"],
  ["fruitveg", 3, "Coconut", "Кокос", "draw"],
  ["fruitveg", 3, "Raspberry", "Малина", "draw"],
  ["fruitveg", 3, "Spinach", "Шпинат", "draw"],
  ["fruitveg", 3, "Artichoke", "Артишок", "draw"],
  ["fruitveg", 3, "Dragonfruit", "Питайя", "draw"],

  ["desserts", 1, "Ice Cream", "Мороженое", "draw"],
  ["desserts", 1, "Cake", "Торт", "draw"],
  ["desserts", 1, "Chocolate", "Шоколад", "draw"],
  ["desserts", 1, "Cookie", "Печенье", "draw"],
  ["desserts", 1, "Candy", "Конфета", "draw"],
  ["desserts", 1, "Pie", "Пирог", "draw"],
  ["desserts", 1, "Waffle", "Вафля", "draw"],
  ["desserts", 1, "Pancake", "Блин", "draw"],
  ["desserts", 2, "Cupcake", "Капкейк", "draw"],
  ["desserts", 2, "Brownie", "Брауни", "draw"],
  ["desserts", 2, "Cheesecake", "Чизкейк", "draw"],
  ["desserts", 2, "Pudding", "Пудинг", "draw"],
  ["desserts", 2, "Croissant", "Круассан", "draw"],
  ["desserts", 2, "Lollipop", "Леденец", "draw"],
  ["desserts", 2, "Gingerbread", "Пряник", "draw"],
  ["desserts", 2, "Marshmallow", "Маршмеллоу", "draw"],
  ["desserts", 2, "Fudge", "Фадж", "draw"],
  ["desserts", 3, "Macaron", "Макарон", "draw"],
  ["desserts", 3, "Tiramisu", "Тирамису", "draw"],
  ["desserts", 3, "Baklava", "Пахлава", "draw"],
  ["desserts", 3, "Eclair", "Эклер", "draw"],
  ["desserts", 3, "Churros", "Чуррос", "draw"],
  ["desserts", 3, "Mochi", "Моти", "draw"],
  ["desserts", 3, "Mousse", "Мусс", "draw"],
  ["desserts", 3, "Cannoli", "Канноли", "draw"],
  ["desserts", 3, "Jelly", "Желе", "draw"],

  ["cuisine", 1, "Pasta", "Паста", "draw"],
  ["cuisine", 1, "Dumplings", "Пельмени", "draw"],
  ["cuisine", 1, "Steak", "Стейк", "draw"],
  ["cuisine", 1, "Curry", "Карри", "draw"],
  ["cuisine", 1, "Lasagna", "Лазанья", "draw"],
  ["cuisine", 2, "Ramen", "Рамэн", "draw"],
  ["cuisine", 2, "Paella", "Паэлья", "draw"],
  ["cuisine", 2, "Pad Thai", "Пад Тай", "draw"],
  ["cuisine", 2, "Falafel", "Фалафель", "draw"],
  ["cuisine", 2, "Borscht", "Борщ", "draw"],
  ["cuisine", 2, "Shawarma", "Шаурма", "draw"],
  ["cuisine", 2, "Risotto", "Ризотто", "draw"],
  ["cuisine", 2, "Gyoza", "Гёдза", "draw"],
  ["cuisine", 2, "Tacos", "Такос", "draw"],
  ["cuisine", 2, "Pierogi", "Вареники", "draw"],
  ["cuisine", 2, "Biryani", "Бирьяни", "draw"],
  ["cuisine", 3, "Pho", "Фо", "draw"],
  ["cuisine", 3, "Bibimbap", "Пибимпап", "draw"],
  ["cuisine", 3, "Kimchi", "Кимчи", "draw"],
  ["cuisine", 3, "Shakshuka", "Шакшука", "draw"],
  ["cuisine", 3, "Rendang", "Ренданг", "draw"],
  ["cuisine", 3, "Goulash", "Гуляш", "draw"],
  ["cuisine", 3, "Tagine", "Тажин", "draw"],
  ["cuisine", 3, "Dim Sum", "Дим Сам", "draw"],
  ["cuisine", 3, "Ceviche", "Севиче", "draw"],
  ["cuisine", 3, "Schnitzel", "Шницель", "draw"],
  ["cuisine", 3, "Moussaka", "Мусака", "draw"],

  ["drinks", 1, "Coffee", "Кофе", "draw"],
  ["drinks", 1, "Tea", "Чай", "draw"],
  ["drinks", 1, "Cola", "Кола", "draw"],
  ["drinks", 1, "Juice", "Сок", "draw"],
  ["drinks", 1, "Water", "Вода", "draw"],
  ["drinks", 2, "Lemonade", "Лимонад", "draw"],
  ["drinks", 2, "Smoothie", "Смузи", "draw"],
  ["drinks", 2, "Espresso", "Эспрессо", "draw"],
  ["drinks", 2, "Hot Chocolate", "Горячий шоколад", "draw"],
  ["drinks", 2, "Beer", "Пиво", "draw"],
  ["drinks", 2, "Wine", "Вино", "draw"],
  ["drinks", 2, "Cocktail", "Коктейль", "draw"],
  ["drinks", 2, "Soda", "Газировка", "draw"],
  ["drinks", 2, "Cappuccino", "Капучино", "draw"],
  ["drinks", 2, "Latte", "Латте", "draw"],
  ["drinks", 3, "Matcha", "Матча", "draw"],
  ["drinks", 3, "Kombucha", "Чайный гриб", "draw"],
  ["drinks", 3, "Bubble Tea", "Тапиока (боба)", "draw"],
  ["drinks", 3, "Horchata", "Орчата", "draw"],
  ["drinks", 3, "Mojito", "Мохито", "draw"],
  ["drinks", 3, "Sangria", "Сангрия", "draw"],
  ["drinks", 3, "Energy Drink", "Энергетик", "draw"],
  ["drinks", 3, "Chai Latte", "Чай латте", "draw"],

  ["snacks", 1, "Popcorn", "Попкорн", "draw"],
  ["snacks", 1, "Chips", "Чипсы", "draw"],
  ["snacks", 1, "Nuts", "Орехи", "draw"],
  ["snacks", 1, "Crackers", "Крекеры", "draw"],
  ["snacks", 1, "Chocolate Bar", "Шоколадный батончик", "draw"],
  ["snacks", 2, "Pretzel", "Крендель", "draw"],
  ["snacks", 2, "Nachos", "Начос", "draw"],
  ["snacks", 2, "Gummy Bears", "Мармеладные мишки", "draw"],
  ["snacks", 2, "Granola Bar", "Гранола-батончик", "draw"],
  ["snacks", 2, "Trail Mix", "Ореховая смесь", "draw"],
  ["snacks", 2, "Jerky", "Вяленое мясо", "draw"],
  ["snacks", 2, "Peanut Butter", "Арахисовое масло", "draw"],
  ["snacks", 2, "Rice Cake", "Рисовый хлебец", "draw"],
  ["snacks", 2, "Cheese", "Сыр", "draw"],
  ["snacks", 2, "Pickle", "Маринованный огурец", "draw"],
  ["snacks", 2, "Olives", "Маслины", "draw"],
  ["snacks", 3, "Edamame", "Эдамамэ", "draw"],
  ["snacks", 3, "Hummus", "Хумус", "draw"],
  ["snacks", 3, "Pork Rinds", "Шкварки", "draw"],
  ["snacks", 3, "Dried Mango", "Сушёное манго", "draw"],
  ["snacks", 3, "Seaweed Snack", "Чипсы из нори", "draw"],
  ["snacks", 3, "Kale Chips", "Чипсы из кейла", "draw"],
]);
