/* Video Games (deeper, with years) */
addWords("games", [
  ["nintendo", 1, "Mario", "Марио", "draw", 1985],
  ["nintendo", 1, "Luigi", "Луиджи", "draw", 1985],
  ["nintendo", 1, "Bowser", "Боузер", "draw", 1985],
  ["nintendo", 1, "Kirby", "Кирби", "draw", 1985],
  ["nintendo", 2, "Princess Peach", "Принцесса Пич", 1985],
  ["nintendo", 2, "Yoshi", "Йоши", "draw", 1985],
  ["nintendo", 2, "Donkey Kong", "Донки Конг", "draw", 1985],
  ["nintendo", 2, "Toad", "Тоад", "draw", 1985],
  ["nintendo", 2, "Wario", "Варио", "draw", 1985],
  ["nintendo", 2, "Waluigi", "Валуиджи", "draw", 1985],
  ["nintendo", 2, "Samus", "Самус", 1985],
  ["nintendo", 2, "Captain Falcon", "Капитан Фалькон", 1985],
  ["nintendo", 3, "Princess Daisy", "Принцесса Дейзи", 1985],
  ["nintendo", 3, "Rosalina", "Розалина", 1985],
  ["nintendo", 3, "Diddy Kong", "Дидди Конг", 1985],
  ["nintendo", 3, "King K. Rool", "Кинг К. Рул", "draw", 1985],
  ["nintendo", 3, "Bowser Jr", "Боузер Джуниор", 1985],
  ["nintendo", 3, "Birdo", "Бёрдо", "draw", 1985],
  ["nintendo", 3, "Ness", "Несс", 1985],
  ["nintendo", 3, "Olimar", "Олимар", 1985],
  ["nintendo", 3, "King Boo", "Кинг Бу", "draw", 1985],
  ["nintendo", 3, "Villager", "Житель", "draw", 1985],

  ["pokemon", 1, "Pikachu", "Пикачу", "draw", 1996],
  ["pokemon", 1, "Charizard", "Чаризард", "draw", 1996],
  ["pokemon", 1, "Mewtwo", "Мьюту", "draw", 1996],
  ["pokemon", 2, "Eevee", "Иви", "draw", 1996],
  ["pokemon", 2, "Bulbasaur", "Бульбазавр", "draw", 1996],
  ["pokemon", 2, "Squirtle", "Сквиртл", "draw", 1996],
  ["pokemon", 2, "Charmander", "Чармандер", "draw", 1996],
  ["pokemon", 2, "Snorlax", "Снорлакс", "draw", 1996],
  ["pokemon", 2, "Gengar", "Генгар", "draw", 1996],
  ["pokemon", 2, "Jigglypuff", "Джиглипафф", "draw", 1996],
  ["pokemon", 2, "Lucario", "Лукарио", "draw", 1996],
  ["pokemon", 2, "Greninja", "Гренинджа", "draw", 1996],
  ["pokemon", 2, "Mew", "Мью", "draw", 1996],
  ["pokemon", 2, "Meowth", "Мяут", "draw", 1996],
  ["pokemon", 3, "Gardevoir", "Гардевуар", 1996],
  ["pokemon", 3, "Lugia", "Лугиа", "draw", 1996],
  ["pokemon", 3, "Rayquaza", "Рейкуаза", "draw", 1996],
  ["pokemon", 3, "Gyarados", "Гяарадос", "draw", 1996],
  ["pokemon", 3, "Dragonite", "Драгонайт", "draw", 1996],
  ["pokemon", 3, "Psyduck", "Псайдак", "draw", 1996],
  ["pokemon", 3, "Magikarp", "Маджикарп", "draw", 1996],
  ["pokemon", 3, "Ditto", "Дитто", "draw", 1996],
  ["pokemon", 3, "Arceus", "Аркеус", 1996],

  ["zelda", 1, "Link", "Линк", "draw", 1986],
  ["zelda", 1, "Princess Zelda", "Принцесса Зельда", "draw", 1986],
  ["zelda", 1, "Ganondorf", "Ганондорф", "draw", 1986],
  ["zelda", 2, "Navi", "Нави", "draw", 1986],
  ["zelda", 2, "Midna", "Мидна", "draw", 1986],
  ["zelda", 2, "Sheik", "Шейк", 1986],
  ["zelda", 2, "Skull Kid", "Скалл Кид", "draw", 1986],
  ["zelda", 2, "Impa", "Импа", 1986],
  ["zelda", 2, "Epona", "Эпона", "draw", 1986],
  ["zelda", 3, "Tingle", "Тингл", "draw", 1986],
  ["zelda", 3, "Revali", "Ревали", 1986],
  ["zelda", 3, "Urbosa", "Урбоза", 1986],
  ["zelda", 3, "Mipha", "Мифа", 1986],
  ["zelda", 3, "Daruk", "Дарук", 1986],
  ["zelda", 3, "Great Deku Tree", "Великое Дерево Деку", 1986],

  ["sonic", 1, "Sonic", "Соник", "draw", 1991],
  ["sonic", 1, "Doctor Eggman", "Доктор Эггман", "draw", 1991],
  ["sonic", 2, "Tails", "Тейлз", "draw", 1991],
  ["sonic", 2, "Knuckles", "Наклз", "draw", 1991],
  ["sonic", 2, "Amy Rose", "Эми Роуз", "draw", 1991],
  ["sonic", 2, "Shadow", "Шэдоу", "draw", 1991],
  ["sonic", 2, "Metal Sonic", "Метал Соник", "draw", 1991],
  ["sonic", 3, "Silver", "Сильвер", "draw", 1991],
  ["sonic", 3, "Rouge", "Руж", 1991],
  ["sonic", 3, "Cream", "Крим", "draw", 1991],
  ["sonic", 3, "Blaze", "Блейз", 1991],
  ["sonic", 3, "Big the Cat", "Биг Кот", "draw", 1991],
  ["sonic", 3, "Espio", "Эспио", 1991],
  ["sonic", 3, "Jet", "Джет", 1991],

  ["minecraft", 1, "Creeper", "Крипер", "draw", 2011],
  ["minecraft", 1, "Steve", "Стив", "draw", 2011],
  ["minecraft", 2, "Alex", "Алекс", "draw", 2011],
  ["minecraft", 2, "Enderman", "Эндермен", "draw", 2011],
  ["minecraft", 2, "Zombie", "Зомби", "draw", 2011],
  ["minecraft", 2, "Skeleton", "Скелет", "draw", 2011],
  ["minecraft", 2, "Ender Dragon", "Дракон Края", "draw", 2011],
  ["minecraft", 2, "Villager", "Житель", "draw", 2011],
  ["minecraft", 3, "Wither", "Визер", "draw", 2011],
  ["minecraft", 3, "Ghast", "Гаст", "draw", 2011],
  ["minecraft", 3, "Piglin", "Пиглин", "draw", 2011],
  ["minecraft", 3, "Iron Golem", "Железный Голем", "draw", 2011],
  ["minecraft", 3, "Slime", "Слизень", "draw", 2011],
  ["minecraft", 3, "Herobrine", "Геробрайн", "draw", 2011],
  ["minecraft", 3, "Spider", "Паук", "draw", 2011],
  ["minecraft", 3, "Witch", "Ведьма", "draw", 2011],

  ["fortnite", 1, "Jonesy", "Джонси", "draw", 2017],
  ["fortnite", 1, "Peely", "Пили", "draw", 2017],
  ["fortnite", 1, "Skull Trooper", "Скелет-Боец", "draw", 2017],
  ["fortnite", 2, "Fishstick", "Фишстик", "draw", 2017],
  ["fortnite", 2, "Midas", "Мидас", 2017],
  ["fortnite", 2, "Meowscles", "Мяускулы", "draw", 2017],
  ["fortnite", 2, "Black Knight", "Чёрный Рыцарь", "draw", 2017],
  ["fortnite", 2, "Raven", "Рейвен", "draw", 2017],
  ["fortnite", 2, "Drift", "Дрифт", 2017],
  ["fortnite", 3, "Cuddle Team Leader", "Лидер Обнимашек", "draw", 2017],
  ["fortnite", 3, "Omega", "Омега", 2017],
  ["fortnite", 3, "The Foundation", "Фундамент", 2017],
  ["fortnite", 3, "Brutus", "Брут", 2017],
  ["fortnite", 3, "Lynx", "Линкс", 2017],
  ["fortnite", 3, "Slone", "Слоун", 2017],
  ["fortnite", 3, "Jules", "Джулс", 2017],

  ["gta", 1, "CJ", "Си-Джей", 1997],
  ["gta", 1, "Trevor", "Тревор", 1997],
  ["gta", 1, "Tommy Vercetti", "Томми Версетти", 1997],
  ["gta", 2, "Michael", "Майкл", 1997],
  ["gta", 2, "Franklin", "Франклин", 1997],
  ["gta", 2, "Niko Bellic", "Нико Беллик", 1997],
  ["gta", 2, "Big Smoke", "Биг Смоук", "draw", 1997],
  ["gta", 2, "Lamar", "Ламар", 1997],
  ["gta", 3, "Sweet", "Свит", 1997],
  ["gta", 3, "Ryder", "Райдер", 1997],
  ["gta", 3, "Roman Bellic", "Роман Беллик", 1997],
  ["gta", 3, "Lester", "Лестер", 1997],
  ["gta", 3, "Wade", "Уэйд", 1997],
  ["gta", 3, "Lance Vance", "Лэнс Вэнс", 1997],

  ["cod", 1, "Captain Price", "Капитан Прайс", "draw", 2003],
  ["cod", 1, "Ghost", "Гоуст", "draw", 2003],
  ["cod", 2, "Soap MacTavish", "Соуп МакТавиш", 2003],
  ["cod", 2, "Makarov", "Макаров", "draw", 2003],
  ["cod", 2, "Alex Mason", "Алекс Мейсон", 2003],
  ["cod", 2, "Woods", "Вудс", 2003],
  ["cod", 2, "Roach", "Роуч", 2003],
  ["cod", 3, "Shepherd", "Шеперд", "draw", 2003],
  ["cod", 3, "Gaz", "Газ", 2003],
  ["cod", 3, "Reznov", "Резнов", 2003],
  ["cod", 3, "Adler", "Адлер", 2003],
  ["cod", 3, "König", "Кёниг", "draw", 2003],
  ["cod", 3, "Nikolai", "Николай", 2003],
  ["cod", 3, "Graves", "Грейвс", 2003],

  ["lol", 1, "Jinx", "Джинкс", "draw", 2009],
  ["lol", 1, "Yasuo", "Ясуо", "draw", 2009],
  ["lol", 1, "Teemo", "Тимо", "draw", 2009],
  ["lol", 1, "Ahri", "Ари", "draw", 2009],
  ["lol", 2, "Lux", "Люкс", 2009],
  ["lol", 2, "Garen", "Гарен", "draw", 2009],
  ["lol", 2, "Ezreal", "Эзреаль", 2009],
  ["lol", 2, "Darius", "Дариус", "draw", 2009],
  ["lol", 2, "Zed", "Зед", "draw", 2009],
  ["lol", 2, "Katarina", "Катарина", 2009],
  ["lol", 2, "Thresh", "Треш", "draw", 2009],
  ["lol", 2, "Jhin", "Джин", "draw", 2009],
  ["lol", 3, "Yone", "Ён", 2009],
  ["lol", 3, "Akali", "Акали", 2009],
  ["lol", 3, "Lee Sin", "Ли Синь", "draw", 2009],
  ["lol", 3, "Vi", "Ви", 2009],
  ["lol", 3, "Caitlyn", "Кейтлин", 2009],
  ["lol", 3, "Morgana", "Моргана", 2009],
  ["lol", 3, "Blitzcrank", "Блицкранк", "draw", 2009],
  ["lol", 3, "Vayne", "Вейн", 2009],
  ["lol", 3, "Kindred", "Киндред", "draw", 2009],

  ["fromsoft", 1, "Solaire of Astora", "Солер из Асторы", "draw", 2011],
  ["fromsoft", 1, "Malenia", "Маления", "draw", 2011],
  ["fromsoft", 1, "Radahn", "Радан", "draw", 2011],
  ["fromsoft", 2, "Ranni the Witch", "Ранни-ведьма", "draw", 2011],
  ["fromsoft", 2, "Artorias", "Арториас", "draw", 2011],
  ["fromsoft", 2, "Lady Maria", "Леди Мария", "draw", 2011],
  ["fromsoft", 2, "Patches", "Патчес", "draw", 2011],
  ["fromsoft", 2, "Morgott", "Моргот", 2011],
  ["fromsoft", 2, "Gwyn", "Гвин", 2011],
  ["fromsoft", 3, "Sif the Wolf", "Сиф-волк", "draw", 2011],
  ["fromsoft", 3, "Gehrman", "Герман", 2011],
  ["fromsoft", 3, "Messmer", "Мессмер", 2011],
  ["fromsoft", 3, "Margit", "Маргит", 2011],
  ["fromsoft", 3, "Micolash", "Миколаш", 2011],
  ["fromsoft", 3, "Isshin Ashina", "Иссин Асина", "draw", 2011],
  ["fromsoft", 3, "Genichiro", "Геничиро", 2011],

  ["residentevil", 1, "Leon Kennedy", "Леон Кеннеди", "draw", 1996],
  ["residentevil", 1, "Albert Wesker", "Альберт Вескер", "draw", 1996],
  ["residentevil", 1, "Nemesis", "Немезис", "draw", 1996],
  ["residentevil", 2, "Chris Redfield", "Крис Редфилд", 1996],
  ["residentevil", 2, "Jill Valentine", "Джилл Валентайн", "draw", 1996],
  ["residentevil", 2, "Ada Wong", "Ада Вонг", "draw", 1996],
  ["residentevil", 2, "Claire Redfield", "Клэр Редфилд", 1996],
  ["residentevil", 2, "Lady Dimitrescu", "Леди Димитреску", "draw", 1996],
  ["residentevil", 2, "Mr. X", "Мистер Икс", "draw", 1996],
  ["residentevil", 3, "Ethan Winters", "Этан Уинтерс", 1996],
  ["residentevil", 3, "Mia Winters", "Миа Уинтерс", 1996],
  ["residentevil", 3, "Rebecca Chambers", "Ребекка Чемберс", 1996],
  ["residentevil", 3, "Jack Baker", "Джек Бейкер", "draw", 1996],
  ["residentevil", 3, "Sherry Birkin", "Шерри Биркин", 1996],
  ["residentevil", 3, "Salazar", "Салазар", "draw", 1996],

  ["fnaf", 1, "Freddy Fazbear", "Фредди Фазбер", "draw", 2014],
  ["fnaf", 1, "Bonnie", "Бонни", "draw", 2014],
  ["fnaf", 1, "Chica", "Чика", "draw", 2014],
  ["fnaf", 1, "Foxy", "Фокси", "draw", 2014],
  ["fnaf", 2, "Springtrap", "Спрингтрап", "draw", 2014],
  ["fnaf", 2, "Golden Freddy", "Золотой Фредди", "draw", 2014],
  ["fnaf", 2, "Puppet", "Марионетка", "draw", 2014],
  ["fnaf", 2, "Mangle", "Мангл", "draw", 2014],
  ["fnaf", 2, "Balloon Boy", "Мальчик с шариками", "draw", 2014],
  ["fnaf", 2, "Circus Baby", "Цирковая Бэби", "draw", 2014],
  ["fnaf", 3, "Ballora", "Балора", "draw", 2014],
  ["fnaf", 3, "Funtime Freddy", "Фантайм Фредди", "draw", 2014],
  ["fnaf", 3, "Ennard", "Эннард", "draw", 2014],
  ["fnaf", 3, "William Afton", "Уильям Афтон", 2014],
  ["fnaf", 3, "Mike Schmidt", "Майк Шмидт", 2014],
  ["fnaf", 3, "Phone Guy", "Парень с Телефоном", 2014],

  ["fnaf", 1, "Crewmate", "Член экипажа", "draw", 2018],
  ["fnaf", 1, "Impostor", "Самозванец", "draw", 2018],
  ["fnaf", 2, "Engineer", "Инженер", "draw", 2018],
  ["fnaf", 3, "Scientist", "Учёный", "draw", 2018],
]);
