/* Geography */
addWords("geography", [
  // ---- Countries (talk-only) ----
  ["countries", 1, "United States", "США"],
  ["countries", 1, "China", "Китай"],
  ["countries", 1, "Russia", "Россия"],
  ["countries", 1, "Japan", "Япония"],
  ["countries", 1, "Germany", "Германия"],
  ["countries", 1, "France", "Франция"],
  ["countries", 1, "United Kingdom", "Великобритания"],
  ["countries", 1, "Italy", "Италия"],
  ["countries", 1, "Spain", "Испания"],
  ["countries", 1, "Canada", "Канада"],
  ["countries", 1, "Brazil", "Бразилия"],
  ["countries", 1, "India", "Индия"],
  ["countries", 1, "Australia", "Австралия"],
  ["countries", 1, "Mexico", "Мексика"],
  ["countries", 1, "Argentina", "Аргентина"],
  ["countries", 1, "Egypt", "Египет"],
  ["countries", 1, "Turkey", "Турция"],
  ["countries", 1, "Greece", "Греция"],
  ["countries", 1, "Netherlands", "Нидерланды"],
  ["countries", 1, "Switzerland", "Швейцария"],
  ["countries", 1, "Sweden", "Швеция"],
  ["countries", 1, "Norway", "Норвегия"],
  ["countries", 1, "Poland", "Польша"],
  ["countries", 1, "Ukraine", "Украина"],
  ["countries", 1, "South Korea", "Южная Корея"],
  ["countries", 1, "Saudi Arabia", "Саудовская Аравия"],
  ["countries", 1, "South Africa", "ЮАР"],
  ["countries", 1, "Portugal", "Португалия"],
  ["countries", 1, "Ireland", "Ирландия"],
  ["countries", 1, "Austria", "Австрия"],
  ["countries", 2, "Belgium", "Бельгия"],
  ["countries", 2, "Denmark", "Дания"],
  ["countries", 2, "Finland", "Финляндия"],
  ["countries", 2, "Czech Republic", "Чехия"],
  ["countries", 2, "Hungary", "Венгрия"],
  ["countries", 2, "Romania", "Румыния"],
  ["countries", 2, "Indonesia", "Индонезия"],
  ["countries", 2, "Thailand", "Таиланд"],
  ["countries", 2, "Vietnam", "Вьетнам"],
  ["countries", 2, "Philippines", "Филиппины"],
  ["countries", 2, "Malaysia", "Малайзия"],
  ["countries", 2, "Pakistan", "Пакистан"],
  ["countries", 2, "Iran", "Иран"],
  ["countries", 2, "Iraq", "Ирак"],
  ["countries", 2, "Israel", "Израиль"],
  ["countries", 2, "Nigeria", "Нигерия"],
  ["countries", 2, "Kenya", "Кения"],
  ["countries", 2, "Morocco", "Марокко"],
  ["countries", 2, "Chile", "Чили"],
  ["countries", 2, "Colombia", "Колумбия"],
  ["countries", 2, "Peru", "Перу"],
  ["countries", 2, "Venezuela", "Венесуэла"],
  ["countries", 2, "New Zealand", "Новая Зеландия"],
  ["countries", 2, "Cuba", "Куба"],
  ["countries", 2, "Iceland", "Исландия"],
  ["countries", 2, "Croatia", "Хорватия"],
  ["countries", 2, "Serbia", "Сербия"],
  ["countries", 2, "Kazakhstan", "Казахстан"],
  ["countries", 2, "Singapore", "Сингапур"],
  ["countries", 2, "United Arab Emirates", "ОАЭ"],
  ["countries", 2, "Qatar", "Катар"],
  ["countries", 2, "Jordan", "Иордания"],
  ["countries", 2, "Lebanon", "Ливан"],
  ["countries", 2, "Cambodia", "Камбоджа"],
  ["countries", 2, "Bangladesh", "Бангладеш"],
  ["countries", 2, "Ethiopia", "Эфиопия"],
  ["countries", 2, "Ghana", "Гана"],
  ["countries", 2, "Tanzania", "Танзания"],
  ["countries", 2, "Bulgaria", "Болгария"],
  ["countries", 2, "Slovakia", "Словакия"],
  ["countries", 2, "Slovenia", "Словения"],
  ["countries", 2, "Ecuador", "Эквадор"],
  ["countries", 2, "Bolivia", "Боливия"],
  ["countries", 2, "Uruguay", "Уругвай"],
  ["countries", 2, "Tunisia", "Тунис"],
  ["countries", 2, "Algeria", "Алжир"],
  ["countries", 3, "Bhutan", "Бутан"],
  ["countries", 3, "Nepal", "Непал"],
  ["countries", 3, "Mongolia", "Монголия"],
  ["countries", 3, "Sri Lanka", "Шри-Ланка"],
  ["countries", 3, "Myanmar", "Мьянма"],
  ["countries", 3, "Laos", "Лаос"],
  ["countries", 3, "Brunei", "Бруней"],
  ["countries", 3, "Maldives", "Мальдивы"],
  ["countries", 3, "Eritrea", "Эритрея"],
  ["countries", 3, "Rwanda", "Руанда"],
  ["countries", 3, "Madagascar", "Мадагаскар"],
  ["countries", 3, "Comoros", "Коморы"],
  ["countries", 3, "Lesotho", "Лесото"],
  ["countries", 3, "Eswatini", "Эсватини"],
  ["countries", 3, "Botswana", "Ботсвана"],
  ["countries", 3, "Namibia", "Намибия"],
  ["countries", 3, "Zambia", "Замбия"],
  ["countries", 3, "Suriname", "Суринам"],
  ["countries", 3, "Guyana", "Гайана"],
  ["countries", 3, "Paraguay", "Парагвай"],
  ["countries", 3, "Belize", "Белиз"],
  ["countries", 3, "San Marino", "Сан-Марино"],
  ["countries", 3, "Andorra", "Андорра"],
  ["countries", 3, "Liechtenstein", "Лихтенштейн"],
  ["countries", 3, "Monaco", "Монако"],
  ["countries", 3, "Malta", "Мальта"],
  ["countries", 3, "Luxembourg", "Люксембург"],
  ["countries", 3, "Montenegro", "Черногория"],
  ["countries", 3, "North Macedonia", "Северная Македония"],
  ["countries", 3, "Moldova", "Молдова"],
  ["countries", 3, "Georgia", "Грузия"],
  ["countries", 3, "Armenia", "Армения"],
  ["countries", 3, "Azerbaijan", "Азербайджан"],
  ["countries", 3, "Kyrgyzstan", "Киргизия"],
  ["countries", 3, "Tajikistan", "Таджикистан"],
  ["countries", 3, "Uzbekistan", "Узбекистан"],
  ["countries", 3, "Vanuatu", "Вануату"],
  ["countries", 3, "Kiribati", "Кирибати"],
  ["countries", 3, "Fiji", "Фиджи"],
  ["countries", 3, "Samoa", "Самоа"],
  ["countries", 3, "Tonga", "Тонга"],
  ["countries", 3, "Palau", "Палау"],

  // ---- Cities (talk-only) ----
  ["cities", 1, "New York", "Нью-Йорк"],
  ["cities", 1, "London", "Лондон"],
  ["cities", 1, "Paris", "Париж"],
  ["cities", 1, "Tokyo", "Токио"],
  ["cities", 1, "Dubai", "Дубай"],
  ["cities", 1, "Los Angeles", "Лос-Анджелес"],
  ["cities", 1, "Rome", "Рим"],
  ["cities", 1, "Barcelona", "Барселона"],
  ["cities", 1, "Moscow", "Москва"],
  ["cities", 1, "Istanbul", "Стамбул"],
  ["cities", 1, "Hong Kong", "Гонконг"],
  ["cities", 1, "Las Vegas", "Лас-Вегас"],
  ["cities", 1, "Miami", "Майами"],
  ["cities", 1, "Amsterdam", "Амстердам"],
  ["cities", 1, "Venice", "Венеция"],
  ["cities", 2, "Shanghai", "Шанхай"],
  ["cities", 2, "Mumbai", "Мумбаи"],
  ["cities", 2, "Rio de Janeiro", "Рио-де-Жанейро"],
  ["cities", 2, "San Francisco", "Сан-Франциско"],
  ["cities", 2, "Chicago", "Чикаго"],
  ["cities", 2, "Toronto", "Торонто"],
  ["cities", 2, "Sydney", "Сидней"],
  ["cities", 2, "Munich", "Мюнхен"],
  ["cities", 2, "Milan", "Милан"],
  ["cities", 2, "Berlin", "Берлин"],
  ["cities", 2, "Seoul", "Сеул"],
  ["cities", 2, "Bangkok", "Бангкок"],
  ["cities", 2, "Cairo", "Каир"],
  ["cities", 2, "Cape Town", "Кейптаун"],
  ["cities", 2, "Vienna", "Вена"],
  ["cities", 2, "Prague", "Прага"],
  ["cities", 2, "Lisbon", "Лиссабон"],
  ["cities", 2, "Marrakesh", "Марракеш"],
  ["cities", 2, "Mexico City", "Мехико"],
  ["cities", 2, "Buenos Aires", "Буэнос-Айрес"],
  ["cities", 2, "Boston", "Бостон"],
  ["cities", 3, "Petra", "Петра"],
  ["cities", 3, "Marseille", "Марсель"],
  ["cities", 3, "Naples", "Неаполь"],
  ["cities", 3, "Osaka", "Осака"],
  ["cities", 3, "Kyoto", "Киото"],
  ["cities", 3, "Casablanca", "Касабланка"],
  ["cities", 3, "Hanoi", "Ханой"],
  ["cities", 3, "Reykjavik", "Рейкьявик"],
  ["cities", 3, "Dubrovnik", "Дубровник"],
  ["cities", 3, "Bruges", "Брюгге"],
  ["cities", 3, "Porto", "Порту"],
  ["cities", 3, "Valencia", "Валенсия"],

  // ---- Capitals (talk-only) ----
  ["capitals", 1, "Paris", "Париж"],
  ["capitals", 1, "London", "Лондон"],
  ["capitals", 1, "Rome", "Рим"],
  ["capitals", 1, "Madrid", "Мадрид"],
  ["capitals", 1, "Berlin", "Берлин"],
  ["capitals", 1, "Moscow", "Москва"],
  ["capitals", 1, "Tokyo", "Токио"],
  ["capitals", 1, "Beijing", "Пекин"],
  ["capitals", 1, "Washington", "Вашингтон"],
  ["capitals", 1, "Cairo", "Каир"],
  ["capitals", 1, "Athens", "Афины"],
  ["capitals", 1, "Lisbon", "Лиссабон"],
  ["capitals", 1, "Vienna", "Вена"],
  ["capitals", 1, "Amsterdam", "Амстердам"],
  ["capitals", 1, "Brussels", "Брюссель"],
  ["capitals", 2, "Ottawa", "Оттава"],
  ["capitals", 2, "Canberra", "Канберра"],
  ["capitals", 2, "Brasilia", "Бразилиа"],
  ["capitals", 2, "Stockholm", "Стокгольм"],
  ["capitals", 2, "Oslo", "Осло"],
  ["capitals", 2, "Helsinki", "Хельсинки"],
  ["capitals", 2, "Warsaw", "Варшава"],
  ["capitals", 2, "Prague", "Прага"],
  ["capitals", 2, "Budapest", "Будапешт"],
  ["capitals", 2, "Dublin", "Дублин"],
  ["capitals", 2, "Bern", "Берн"],
  ["capitals", 2, "Seoul", "Сеул"],
  ["capitals", 2, "Bangkok", "Бангкок"],
  ["capitals", 2, "New Delhi", "Нью-Дели"],
  ["capitals", 2, "Buenos Aires", "Буэнос-Айрес"],
  ["capitals", 2, "Nairobi", "Найроби"],
  ["capitals", 2, "Reykjavik", "Рейкьявик"],
  ["capitals", 2, "Copenhagen", "Копенгаген"],
  ["capitals", 2, "Ankara", "Анкара"],
  ["capitals", 3, "Sarajevo", "Сараево"],
  ["capitals", 3, "Naypyidaw", "Нейпьидо"],
  ["capitals", 3, "Thimphu", "Тхимпху"],
  ["capitals", 3, "Bishkek", "Бишкек"],
  ["capitals", 3, "Ulaanbaatar", "Улан-Батор"],
  ["capitals", 3, "Astana", "Астана"],
  ["capitals", 3, "Tashkent", "Ташкент"],
  ["capitals", 3, "Tbilisi", "Тбилиси"],
  ["capitals", 3, "Yerevan", "Ереван"],
  ["capitals", 3, "Baku", "Баку"],
  ["capitals", 3, "Vientiane", "Вьентьян"],
  ["capitals", 3, "Kathmandu", "Катманду"],
  ["capitals", 3, "Wellington", "Веллингтон"],
  ["capitals", 3, "Pretoria", "Претория"],
  ["capitals", 3, "Addis Ababa", "Аддис-Абеба"],

  // ---- Landmarks (draw) ----
  ["landmarks", 1, "Eiffel Tower", "Эйфелева башня", "draw"],
  ["landmarks", 1, "Statue of Liberty", "Статуя Свободы", "draw"],
  ["landmarks", 1, "Big Ben", "Биг-Бен", "draw"],
  ["landmarks", 1, "Great Wall of China", "Великая Китайская стена", "draw"],
  ["landmarks", 1, "Pyramids of Giza", "Пирамиды Гизы", "draw"],
  ["landmarks", 1, "Colosseum", "Колизей", "draw"],
  ["landmarks", 1, "Taj Mahal", "Тадж-Махал", "draw"],
  ["landmarks", 1, "Christ the Redeemer", "Христос-Искупитель", "draw"],
  ["landmarks", 1, "Sydney Opera House", "Сиднейский оперный театр", "draw"],
  ["landmarks", 1, "Burj Khalifa", "Бурдж-Халифа", "draw"],
  ["landmarks", 1, "Golden Gate Bridge", "Мост Золотые Ворота", "draw"],
  ["landmarks", 1, "Mount Rushmore", "Гора Рашмор", "draw"],
  ["landmarks", 2, "Sagrada Familia", "Саграда Фамилия", "draw"],
  ["landmarks", 2, "Stonehenge", "Стоунхендж", "draw"],
  ["landmarks", 2, "Angkor Wat", "Ангкор-Ват", "draw"],
  ["landmarks", 2, "Petra", "Петра", "draw"],
  ["landmarks", 2, "Machu Picchu", "Мачу-Пикчу", "draw"],
  ["landmarks", 2, "Chichen Itza", "Чичен-Ица", "draw"],
  ["landmarks", 2, "Hagia Sophia", "Айя-София", "draw"],
  ["landmarks", 2, "Leaning Tower of Pisa", "Пизанская башня", "draw"],
  ["landmarks", 2, "Empire State Building", "Эмпайр-стейт-билдинг", "draw"],
  ["landmarks", 2, "Tower Bridge", "Тауэрский мост", "draw"],
  ["landmarks", 2, "Acropolis", "Акрополь", "draw"],
  ["landmarks", 2, "Brandenburg Gate", "Бранденбургские ворота", "draw"],
  ["landmarks", 2, "Petronas Towers", "Башни Петронас", "draw"],
  ["landmarks", 3, "Moai", "Моаи", "draw"],
  ["landmarks", 3, "Neuschwanstein Castle", "Замок Нойшванштайн", "draw"],
  ["landmarks", 3, "Great Sphinx", "Большой сфинкс", "draw"],
  ["landmarks", 3, "Atomium", "Атомиум", "draw"],
  ["landmarks", 3, "Sky Tower", "Скай-Тауэр", "draw"],

  // ---- Flags (draw) ----
  ["flags", 1, "Flag of Japan", "Флаг Японии", "draw"],
  ["flags", 1, "Flag of the United States", "Флаг США", "draw"],
  ["flags", 1, "Flag of the United Kingdom", "Флаг Великобритании", "draw"],
  ["flags", 1, "Flag of France", "Флаг Франции", "draw"],
  ["flags", 1, "Flag of Canada", "Флаг Канады", "draw"],
  ["flags", 1, "Flag of Brazil", "Флаг Бразилии", "draw"],
  ["flags", 1, "Flag of Germany", "Флаг Германии", "draw"],
  ["flags", 1, "Flag of Italy", "Флаг Италии", "draw"],
  ["flags", 2, "Flag of Switzerland", "Флаг Швейцарии", "draw"],
  ["flags", 2, "Flag of South Korea", "Флаг Южной Кореи", "draw"],
  ["flags", 2, "Flag of Greece", "Флаг Греции", "draw"],
  ["flags", 2, "Flag of Turkey", "Флаг Турции", "draw"],
  ["flags", 2, "Flag of Mexico", "Флаг Мексики", "draw"],
  ["flags", 2, "Flag of India", "Флаг Индии", "draw"],
  ["flags", 2, "Flag of Israel", "Флаг Израиля", "draw"],
  ["flags", 2, "Flag of South Africa", "Флаг ЮАР", "draw"],
  ["flags", 2, "Flag of Argentina", "Флаг Аргентины", "draw"],
  ["flags", 3, "Flag of Nepal", "Флаг Непала", "draw"],
  ["flags", 3, "Flag of Bhutan", "Флаг Бутана", "draw"],
  ["flags", 3, "Flag of Wales", "Флаг Уэльса", "draw"],
  ["flags", 3, "Flag of Jamaica", "Флаг Ямайки", "draw"],
  ["flags", 3, "Flag of Kenya", "Флаг Кении", "draw"],
  ["flags", 3, "Flag of Lebanon", "Флаг Ливана", "draw"],
  ["flags", 3, "Flag of South Sudan", "Флаг Южного Судана", "draw"],
  ["flags", 3, "Flag of Mongolia", "Флаг Монголии", "draw"],

  // ---- Wonders of nature (draw) ----
  ["wonders", 1, "Grand Canyon", "Гранд-Каньон", "draw"],
  ["wonders", 1, "Niagara Falls", "Ниагарский водопад", "draw"],
  ["wonders", 1, "Mount Everest", "Эверест", "draw"],
  ["wonders", 1, "Sahara Desert", "Пустыня Сахара", "draw"],
  ["wonders", 1, "Amazon Rainforest", "Амазонские джунгли", "draw"],
  ["wonders", 1, "Great Barrier Reef", "Большой Барьерный риф", "draw"],
  ["wonders", 1, "Mount Fuji", "Гора Фудзи", "draw"],
  ["wonders", 1, "Northern Lights", "Северное сияние", "draw"],
  ["wonders", 2, "Victoria Falls", "Водопад Виктория", "draw"],
  ["wonders", 2, "Dead Sea", "Мёртвое море", "draw"],
  ["wonders", 2, "Iguazu Falls", "Водопад Игуасу", "draw"],
  ["wonders", 2, "Galapagos Islands", "Галапагосские острова", "draw"],
  ["wonders", 2, "Ha Long Bay", "Бухта Халонг", "draw"],
  ["wonders", 2, "Yellowstone", "Йеллоустоун", "draw"],
  ["wonders", 2, "Mount Kilimanjaro", "Килиманджаро", "draw"],
  ["wonders", 2, "Plitvice Lakes", "Плитвицкие озёра", "draw"],
  ["wonders", 3, "Salar de Uyuni", "Солончак Уюни", "draw"],
  ["wonders", 3, "Pamukkale", "Памуккале", "draw"],
  ["wonders", 3, "Wadi Rum", "Вади-Рам", "draw"],
  ["wonders", 3, "Antelope Canyon", "Каньон Антилопы", "draw"],
  ["wonders", 3, "Zhangjiajie", "Чжанцзяцзе", "draw"],
  ["wonders", 3, "Cappadocia", "Каппадокия", "draw"],
  ["wonders", 3, "Giant's Causeway", "Дорога гигантов", "draw"],
  ["wonders", 3, "Socotra", "Сокотра", "draw"],
  ["wonders", 3, "Lake Baikal", "Озеро Байкал", "draw"],
]);
