/* History (easy-heavy, with years) */
addWords("history", [
  // people — tier 1 (easy, world-famous)
  ["people", 1, "Albert Einstein", "Альберт Эйнштейн", 1921],
  ["people", 1, "Cleopatra", "Клеопатра", -30],
  ["people", 1, "Napoleon Bonaparte", "Наполеон Бонапарт", 1804],
  ["people", 1, "Leonardo da Vinci", "Леонардо да Винчи", 1503],
  ["people", 1, "Mahatma Gandhi", "Махатма Ганди", 1930],
  ["people", 1, "Abraham Lincoln", "Авраам Линкольн", 1865],
  ["people", 1, "Isaac Newton", "Исаак Ньютон", 1687],
  ["people", 1, "Nikola Tesla", "Никола Тесла", 1891],
  ["people", 1, "Genghis Khan", "Чингисхан", 1206],
  ["people", 1, "Winston Churchill", "Уинстон Черчилль", 1940],
  ["people", 1, "Marie Curie", "Мария Кюри", 1903],
  ["people", 1, "Galileo Galilei", "Галилео Галилей", 1610],
  ["people", 1, "Christopher Columbus", "Христофор Колумб", 1492],
  ["people", 1, "Alexander the Great", "Александр Великий", -323],
  ["people", 1, "Joan of Arc", "Жанна д'Арк", 1429],
  ["people", 1, "Wolfgang Amadeus Mozart", "Вольфганг Амадей Моцарт", 1791],
  ["people", 1, "William Shakespeare", "Уильям Шекспир", 1600],
  ["people", 1, "Julius Caesar", "Юлий Цезарь", -44],
  ["people", 1, "George Washington", "Джордж Вашингтон", 1789],
  ["people", 1, "Ludwig van Beethoven", "Людвиг ван Бетховен", 1804],
  ["people", 1, "Charles Darwin", "Чарльз Дарвин", 1859],
  ["people", 1, "Nelson Mandela", "Нельсон Мандела", 1994],
  ["people", 1, "Plato", "Платон", -380],
  ["people", 1, "Socrates", "Сократ", -399],
  ["people", 1, "Marco Polo", "Марко Поло", 1271],
  ["people", 1, "Ferdinand Magellan", "Фернан Магеллан", 1519],
  ["people", 1, "Nicolaus Copernicus", "Николай Коперник", 1543],
  ["people", 1, "Catherine the Great", "Екатерина Великая", 1762],
  ["people", 1, "Queen Victoria", "Королева Виктория", 1837],
  ["people", 1, "Tutankhamun", "Тутанхамон", -1323],
  ["people", 1, "Confucius", "Конфуций", -500],
  ["people", 1, "Thomas Edison", "Томас Эдисон", 1879],
  ["people", 1, "Martin Luther King Jr.", "Мартин Лютер Кинг", 1963],
  ["people", 1, "Mother Teresa", "Мать Тереза", 1979],
  ["people", 1, "Neil Armstrong", "Нил Армстронг", 1969],
  ["people", 1, "Amelia Earhart", "Амелия Эрхарт", 1932],
  ["people", 1, "Rosa Parks", "Роза Паркс", 1955],
  ["people", 1, "Archimedes", "Архимед", -250],
  ["people", 1, "Pythagoras", "Пифагор", -530],
  ["people", 1, "Attila the Hun", "Аттила", 434],
  // people — tier 2
  ["people", 2, "Aristotle", "Аристотель", -350],
  ["people", 2, "Ramesses II", "Рамсес II", -1279],
  ["people", 2, "Nefertiti", "Нефертити", -1345],
  ["people", 2, "Hannibal Barca", "Ганнибал Барка", -218],
  ["people", 2, "Johann Sebastian Bach", "Иоганн Себастьян Бах", 1723],
  ["people", 2, "Pablo Picasso", "Пабло Пикассо", 1907],
  ["people", 2, "Vincent van Gogh", "Винсент ван Гог", 1889],
  ["people", 2, "Johannes Gutenberg", "Иоганн Гутенберг", 1450],
  ["people", 2, "Vladimir Lenin", "Владимир Ленин", 1917],
  ["people", 2, "Joseph Stalin", "Иосиф Сталин", 1924],
  ["people", 2, "Adolf Hitler", "Адольф Гитлер", 1933],
  ["people", 2, "Orville Wright", "Орвилл Райт", 1903],
  ["people", 2, "Homer", "Гомер", -700],
  ["people", 2, "Michelangelo", "Микеланджело", 1512],
  ["people", 2, "Spartacus", "Спартак", -73],
  ["people", 2, "Charlemagne", "Карл Великий", 800],
  // people — tier 3
  ["people", 3, "Hammurabi", "Хаммурапи", -1750],
  ["people", 3, "Tamerlane", "Тамерлан", 1370],
  ["people", 3, "Saladin", "Саладин", 1187],
  ["people", 3, "Suleiman the Magnificent", "Сулейман Великолепный", 1520],
  ["people", 3, "Frederick the Great", "Фридрих Великий", 1740],
  ["people", 3, "Simón Bolívar", "Симон Боливар", 1819],
  ["people", 3, "Boudicca", "Боудикка", 61],

  // events — tier 1 (iconic, easy)
  ["events", 1, "Moon Landing", "Высадка на Луну", 1969],
  ["events", 1, "Fall of the Berlin Wall", "Падение Берлинской стены", 1989],
  ["events", 1, "French Revolution", "Французская революция", 1789],
  ["events", 1, "World War I", "Первая мировая война", 1914],
  ["events", 1, "World War II", "Вторая мировая война", 1939],
  ["events", 1, "Titanic Sinking", "Гибель Титаника", 1912],
  ["events", 1, "American Revolution", "Американская революция", 1776],
  ["events", 1, "Pearl Harbor Attack", "Атака на Перл-Харбор", 1941],
  ["events", 1, "D-Day Landings", "День Д", 1944],
  ["events", 1, "Great Depression", "Великая депрессия", 1929],
  ["events", 1, "Hiroshima Bombing", "Бомбардировка Хиросимы", 1945],
  ["events", 1, "Boston Tea Party", "Бостонское чаепитие", 1773],
  ["events", 1, "Wright Brothers First Flight", "Первый полёт братьев Райт", 1903],
  ["events", 1, "Discovery of America", "Открытие Америки", 1492],
  ["events", 1, "Fall of the Roman Empire", "Падение Римской империи", 476],
  ["events", 1, "Black Death Plague", "Чёрная чума", 1347],
  ["events", 1, "Cold War Begins", "Начало холодной войны", 1947],
  ["events", 1, "Industrial Revolution", "Промышленная революция", 1760],
  ["events", 1, "Renaissance", "Эпоха Возрождения", 1500],
  ["events", 1, "September 11 Attacks", "Теракты 11 сентября", 2001],
  ["events", 1, "Olympic Games Revival", "Возрождение Олимпийских игр", 1896],
  ["events", 1, "American Civil War", "Гражданская война в США", 1861],
  ["events", 1, "Russian Revolution", "Русская революция", 1917],
  // events — tier 2
  ["events", 2, "Chernobyl Disaster", "Чернобыльская катастрофа", 1986],
  ["events", 2, "Fall of the Soviet Union", "Распад СССР", 1991],
  ["events", 2, "Vietnam War", "Война во Вьетнаме", 1965],
  ["events", 2, "Civil Rights Act", "Закон о гражданских правах", 1964],
  ["events", 2, "First iPhone Released", "Выход первого iPhone", 2007],
  ["events", 2, "World Wide Web Invented", "Изобретение World Wide Web", 1989],
  ["events", 2, "Television Invented", "Изобретение телевидения", 1926],
  ["events", 2, "Space Race Begins", "Начало космической гонки", 1957],
  ["events", 2, "Magna Carta Signed", "Подписание Великой хартии вольностей", 1215],
  ["events", 2, "Printing Press Invented", "Изобретение печатного станка", 1450],
  ["events", 2, "End of Apartheid", "Конец апартеида", 1994],
  ["events", 2, "Cuban Missile Crisis", "Карибский кризис", 1962],
  ["events", 2, "Spanish Flu Pandemic", "Испанский грипп", 1918],
  ["events", 2, "Battle of Waterloo", "Битва при Ватерлоо", 1815],
  // events — tier 3
  ["events", 3, "Treaty of Westphalia", "Вестфальский мир", 1648],
  ["events", 3, "The Reformation", "Реформация", 1517],
  ["events", 3, "Battle of Hastings", "Битва при Гастингсе", 1066],
  ["events", 3, "The Crusades Begin", "Начало крестовых походов", 1096],
  ["events", 3, "Hundred Years War", "Столетняя война", 1337],

  // ancient — tier 1
  ["ancient", 1, "Great Pyramid of Giza", "Пирамида Хеопса", -2560],
  ["ancient", 1, "Ancient Egypt", "Древний Египет", -3000],
  ["ancient", 1, "Roman Empire", "Римская империя", -27],
  ["ancient", 1, "Ancient Greece", "Древняя Греция", -500],
  ["ancient", 1, "Colosseum", "Колизей", 80],
  ["ancient", 1, "Trojan War", "Троянская война", -1200],
  ["ancient", 1, "Great Wall of China", "Великая китайская стена", -221],
  ["ancient", 1, "Pompeii Destroyed by Vesuvius", "Гибель Помпей", 79],
  ["ancient", 1, "Vikings", "Викинги", 793],
  ["ancient", 1, "Babylon", "Вавилон", -1800],
  ["ancient", 1, "Sparta", "Спарта", -800],
  ["ancient", 1, "First Olympic Games", "Первые Олимпийские игры", -776],
  ["ancient", 1, "Stonehenge", "Стоунхендж", -2500],
  ["ancient", 1, "Mummies of Egypt", "Египетские мумии", -2700],
  ["ancient", 1, "Hieroglyphics", "Иероглифы", -3200],
  ["ancient", 1, "Roman Gladiators", "Римские гладиаторы", -264],
  ["ancient", 1, "Pharaohs of Egypt", "Фараоны Египта", -3000],
  ["ancient", 1, "Athens Democracy", "Демократия в Афинах", -508],
  // ancient — tier 2
  ["ancient", 2, "Hammurabi's Code", "Кодекс Хаммурапи", -1754],
  ["ancient", 2, "Hanging Gardens of Babylon", "Висячие сады Вавилона", -600],
  ["ancient", 2, "Battle of Marathon", "Марафонская битва", -490],
  ["ancient", 2, "Persian Empire", "Персидская империя", -550],
  ["ancient", 2, "Maya Civilization", "Цивилизация майя", -2000],
  ["ancient", 2, "Phoenician Alphabet", "Финикийский алфавит", -1100],
  ["ancient", 2, "The Silk Road", "Великий шёлковый путь", -130],
  ["ancient", 2, "Roman Republic", "Римская республика", -509],
  ["ancient", 2, "Battle of Thermopylae", "Битва при Фермопилах", -480],
  ["ancient", 2, "Alexander's Conquest of Persia", "Завоевание Персии Александром", -330],
  // ancient — tier 3
  ["ancient", 3, "Sumerian Civilization", "Шумерская цивилизация", -3500],
  ["ancient", 3, "Minoan Civilization", "Минойская цивилизация", -2700],
  ["ancient", 3, "Assyrian Empire", "Ассирийская империя", -900],
  ["ancient", 3, "Punic Wars", "Пунические войны", -264],
  ["ancient", 3, "Carthage Founded", "Основание Карфагена", -814],
  ["ancient", 3, "Acropolis of Athens", "Афинский Акрополь", -447],
  ["ancient", 3, "Indus Valley Civilization", "Цивилизация долины Инда", -2600],

  // modern — tier 1
  ["modern", 1, "Moon Landing Apollo 11", "Высадка Аполлона-11", 1969],
  ["modern", 1, "Internet Goes Public", "Интернет становится публичным", 1991],
  ["modern", 1, "First Personal Computer", "Первый персональный компьютер", 1977],
  ["modern", 1, "World Wide Web", "Всемирная паутина", 1989],
  ["modern", 1, "First iPhone", "Первый iPhone", 2007],
  ["modern", 1, "Chernobyl Nuclear Disaster", "Чернобыльская катастрофа", 1986],
  ["modern", 1, "9/11 Terrorist Attacks", "Теракты 9/11", 2001],
  ["modern", 1, "Fall of Berlin Wall", "Падение Берлинской стены", 1989],
  ["modern", 1, "Dissolution of USSR", "Распад СССР", 1991],
  ["modern", 1, "Civil Rights Movement", "Движение за гражданские права", 1964],
  ["modern", 1, "Sputnik Satellite Launch", "Запуск спутника", 1957],
  ["modern", 1, "DNA Structure Discovered", "Открытие структуры ДНК", 1953],
  ["modern", 1, "Penicillin Discovered", "Открытие пенициллина", 1928],
  ["modern", 1, "First Airplane Flight", "Первый полёт самолёта", 1903],
  ["modern", 1, "Women Get Vote in USA", "Женщины получают право голоса в США", 1920],
  // modern — tier 2
  ["modern", 2, "Hubble Telescope Launched", "Запуск телескопа Хаббл", 1990],
  ["modern", 2, "Human Genome Mapped", "Расшифровка генома человека", 2003],
  ["modern", 2, "COVID-19 Pandemic", "Пандемия COVID-19", 2020],
  ["modern", 2, "First Cloned Sheep Dolly", "Первая клонированная овца Долли", 1996],
  ["modern", 2, "Social Media Rises", "Расцвет социальных сетей", 2004],
  ["modern", 2, "Vietnam War", "Война во Вьетнаме", 1965],
  ["modern", 2, "Korean War", "Корейская война", 1950],
  ["modern", 2, "Cuban Missile Crisis", "Карибский кризис", 1962],
  ["modern", 2, "First Human in Space", "Первый человек в космосе", 1961],
  ["modern", 2, "Berlin Wall Built", "Строительство Берлинской стены", 1961],
  ["modern", 2, "End of Apartheid", "Конец апартеида", 1994],
  // modern — tier 3
  ["modern", 3, "Kyoto Protocol", "Киотский протокол", 1997],
  ["modern", 3, "Rwandan Genocide", "Геноцид в Руанде", 1994],
  ["modern", 3, "Tiananmen Square Protests", "Протесты на площади Тяньаньмэнь", 1989],
  ["modern", 3, "Iranian Revolution", "Иранская революция", 1979],
  ["modern", 3, "Arab Spring", "Арабская весна", 2011],
  ["modern", 3, "Marshall Plan", "План Маршалла", 1948],
]);
