/* Internet & Memes */
addWords("internet", [
  // memes — classic evergreen memes
  ["memes", 1, "Doge", "Доге", "draw"],
  ["memes", 1, "Rickroll", "Рикролл", "draw"],
  ["memes", 1, "Grumpy Cat", "Сердитый кот", "draw"],
  ["memes", 1, "Trollface", "Троллфейс", "draw"],
  ["memes", 1, "Gangnam Style", "Gangnam Style", "draw"],
  ["memes", 1, "Nyan Cat", "Нян Кот", "draw"],
  ["memes", 2, "Distracted Boyfriend", "Парень, отвлёкшийся на другую", "draw"],
  ["memes", 2, "Harlem Shake", "Harlem Shake", "draw"],
  ["memes", 2, "Bad Luck Brian", "Невезучий Брайан", "draw"],
  ["memes", 2, "Success Kid", "Малыш-успех", "draw"],
  ["memes", 2, "Forever Alone", "Навсегда один", "draw"],
  ["memes", 2, "Y U No", "Ну почему ты не", "draw"],
  ["memes", 2, "This Is Fine", "Это нормально", "draw"],
  ["memes", 2, "Overly Attached Girlfriend", "Чересчур привязчивая девушка", "draw"],
  ["memes", 3, "Galaxy Brain", "Расширение сознания", "draw"],
  ["memes", 3, "Loss", "Loss", "draw"],
  ["memes", 3, "Ermahgerd", "Эрмагерд", "draw"],
  ["memes", 3, "Philosoraptor", "Философораптор", "draw"],
  ["memes", 3, "Scumbag Steve", "Подонок Стив", "draw"],
  ["memes", 3, "All Your Base", "All Your Base", "draw"],

  // reactions — reaction-face / format memes
  ["reactions", 1, "Surprised Pikachu", "Удивлённый Пикачу", "draw"],
  ["reactions", 1, "Drake Hotline Bling", "Дрейк (одобряет/не одобряет)", "draw"],
  ["reactions", 1, "Crying Jordan", "Плачущий Джордан", "draw"],
  ["reactions", 1, "Mocking SpongeBob", "Издевающийся Губка Боб", "draw"],
  ["reactions", 2, "Two Buttons", "Две кнопки", "draw"],
  ["reactions", 2, "Side-eye Chloe", "Хлоя с подозрительным взглядом", "draw"],
  ["reactions", 2, "Disaster Girl", "Девочка-катастрофа", "draw"],
  ["reactions", 2, "Hide the Pain Harold", "Скрывающий боль Гарольд", "draw"],
  ["reactions", 2, "Roll Safe", "Думающий парень", "draw"],
  ["reactions", 2, "Woman Yelling at Cat", "Женщина кричит на кота", "draw"],
  ["reactions", 2, "Blinking Guy", "Моргающий парень", "draw"],
  ["reactions", 2, "Confused Math Lady", "Запутавшаяся в подсчётах дама", "draw"],
  ["reactions", 3, "Is This a Pigeon?", "Это бабочка?", "draw"],
  ["reactions", 3, "First World Problems", "Проблемы первого мира", "draw"],
  ["reactions", 3, "Awkward Look Monkey Puppet", "Неловкий взгляд обезьянки", "draw"],
  ["reactions", 3, "Disappointed Cricket Fan", "Разочарованный болельщик", "draw"],
  ["reactions", 3, "They Don't Know", "Они не знают", "draw"],
  ["reactions", 3, "Sweating Guy", "Потеющий парень (две кнопки)", "draw"],

  // characters — viral characters / mascots
  ["characters", 1, "Shrek", "Шрек", "draw"],
  ["characters", 1, "Among Us Crewmate", "Член экипажа Among Us", "draw"],
  ["characters", 1, "Baby Yoda", "Малыш Йода", "draw"],
  ["characters", 1, "Pepe the Frog", "Лягушонок Пепе", "draw"],
  ["characters", 2, "Wojak", "Вояк", "draw"],
  ["characters", 2, "Stonks Man", "Stonks (Мужик)", "draw"],
  ["characters", 2, "Cheems", "Чимс", "draw"],
  ["characters", 2, "Chad", "Чад", "draw"],
  ["characters", 2, "Pop Cat", "Поп Кэт", "draw"],
  ["characters", 2, "Gigachad", "Гигачад", "draw"],
  ["characters", 2, "Doomer", "Думер", "draw"],
  ["characters", 3, "Polandball", "Полендбол", "draw"],
  ["characters", 3, "Yao Ming Face", "Лицо Яо Мина", "draw"],
  ["characters", 3, "Pepe the King Prawn", "Креветка Пепе", "draw"],
  ["characters", 3, "Soyjak", "Сойджак", "draw"],
  ["characters", 3, "Bongo Cat", "Бонго Кэт", "draw"],
  ["characters", 3, "Crying Wojak", "Плачущий Вояк", "draw"],
  ["characters", 3, "Pepe the Frog (Sad)", "Грустный Пепе", "draw"],

  // apps — apps & sites
  ["apps", 1, "YouTube", "YouTube", "draw"],
  ["apps", 1, "Google", "Google", "draw"],
  ["apps", 1, "TikTok", "TikTok", "draw"],
  ["apps", 1, "Instagram", "Instagram", "draw"],
  ["apps", 1, "WhatsApp", "WhatsApp", "draw"],
  ["apps", 1, "Wikipedia", "Wikipedia", "draw"],
  ["apps", 1, "Facebook", "Facebook", "draw"],
  ["apps", 1, "X (Twitter)", "X (Twitter)", "draw"],
  ["apps", 2, "Reddit", "Reddit", "draw"],
  ["apps", 2, "Netflix", "Netflix", "draw"],
  ["apps", 2, "Discord", "Discord", "draw"],
  ["apps", 2, "Twitch", "Twitch", "draw"],
  ["apps", 2, "Spotify", "Spotify", "draw"],
  ["apps", 2, "Telegram", "Telegram", "draw"],
  ["apps", 2, "Snapchat", "Snapchat", "draw"],
  ["apps", 2, "Zoom", "Zoom", "draw"],
  ["apps", 3, "Tumblr", "Tumblr", "draw"],
  ["apps", 3, "Pinterest", "Pinterest", "draw"],

  // creators — well-known long-running creators / streamers
  ["creators", 1, "MrBeast", "MrBeast", "draw"],
  ["creators", 1, "PewDiePie", "PewDiePie", "draw"],
  ["creators", 1, "Ninja", "Ninja"],
  ["creators", 1, "Markiplier", "Markiplier"],
  ["creators", 2, "Mr. Bean (Rowan Atkinson)", "Мистер Бин"],
  ["creators", 2, "Jacksepticeye", "Jacksepticeye"],
  ["creators", 2, "Logan Paul", "Логан Пол"],
  ["creators", 2, "KSI", "KSI"],
  ["creators", 2, "Dream", "Dream", "draw"],
  ["creators", 2, "Ryan Higa", "Ryan Higa"],
  ["creators", 2, "Smosh", "Smosh"],
  ["creators", 2, "Ludwig", "Ludwig"],
  ["creators", 3, "Pokimane", "Pokimane"],
  ["creators", 3, "Shroud", "Shroud"],
  ["creators", 3, "DanTDM", "DanTDM"],
  ["creators", 3, "VanossGaming", "VanossGaming"],
  ["creators", 3, "Tobuscus", "Tobuscus"],
  ["creators", 3, "Ray William Johnson", "Ray William Johnson"],
]);
