/* Jobs */
addWords("jobs", [
  ["everyday", 1, "Teacher", "Учитель", "draw"],
  ["everyday", 1, "Doctor", "Врач", "draw"],
  ["everyday", 1, "Nurse", "Медсестра", "draw"],
  ["everyday", 1, "Waiter", "Официант", "draw"],
  ["everyday", 1, "Cashier", "Кассир", "draw"],
  ["everyday", 1, "Cook", "Повар", "draw"],
  ["everyday", 1, "Driver", "Водитель", "draw"],
  ["everyday", 1, "Salesperson", "Продавец", "draw"],
  ["everyday", 2, "Cleaner", "Уборщик", "draw"],
  ["everyday", 2, "Farmer", "Фермер", "draw"],
  ["everyday", 2, "Librarian", "Библиотекарь", "draw"],
  ["everyday", 2, "Barber", "Парикмахер", "draw"],
  ["everyday", 2, "Lawyer", "Адвокат", "draw"],
  ["everyday", 2, "Dentist", "Стоматолог", "draw"],
  ["everyday", 2, "Secretary", "Секретарь", "draw"],
  ["everyday", 2, "Manager", "Менеджер"],
  ["everyday", 3, "Pharmacist", "Фармацевт", "draw"],
  ["everyday", 3, "Accountant", "Бухгалтер"],

  ["uniformed", 1, "Police Officer", "Полицейский", "draw"],
  ["uniformed", 1, "Firefighter", "Пожарный", "draw"],
  ["uniformed", 1, "Soldier", "Солдат", "draw"],
  ["uniformed", 1, "Pilot", "Пилот", "draw"],
  ["uniformed", 1, "Chef", "Шеф-повар", "draw"],
  ["uniformed", 2, "Surgeon", "Хирург", "draw"],
  ["uniformed", 2, "Judge", "Судья", "draw"],
  ["uniformed", 2, "Referee", "Рефери", "draw"],
  ["uniformed", 2, "Sailor", "Моряк", "draw"],
  ["uniformed", 2, "Paramedic", "Фельдшер", "draw"],
  ["uniformed", 2, "Flight Attendant", "Стюардесса", "draw"],
  ["uniformed", 2, "Security Guard", "Охранник", "draw"],
  ["uniformed", 2, "Postman", "Почтальон", "draw"],
  ["uniformed", 3, "Coast Guard", "Береговая охрана", "draw"],
  ["uniformed", 3, "Air Traffic Controller", "Авиадиспетчер"],
  ["uniformed", 3, "Prison Guard", "Тюремный охранник", "draw"],

  ["trades", 1, "Plumber", "Сантехник", "draw"],
  ["trades", 1, "Electrician", "Электрик", "draw"],
  ["trades", 1, "Carpenter", "Плотник", "draw"],
  ["trades", 1, "Mechanic", "Механик", "draw"],
  ["trades", 1, "Builder", "Строитель", "draw"],
  ["trades", 2, "Welder", "Сварщик", "draw"],
  ["trades", 2, "Painter", "Маляр", "draw"],
  ["trades", 2, "Butcher", "Мясник", "draw"],
  ["trades", 2, "Baker", "Пекарь", "draw"],
  ["trades", 2, "Locksmith", "Слесарь", "draw"],
  ["trades", 2, "Blacksmith", "Кузнец", "draw"],
  ["trades", 2, "Gardener", "Садовник", "draw"],
  ["trades", 2, "Bricklayer", "Каменщик", "draw"],
  ["trades", 3, "Roofer", "Кровельщик", "draw"],
  ["trades", 3, "Glazier", "Стекольщик", "draw"],
  ["trades", 3, "Tiler", "Плиточник", "draw"],
  ["trades", 3, "Boilermaker", "Котельщик", "draw"],

  ["creative", 1, "Artist", "Художник", "draw"],
  ["creative", 1, "Musician", "Музыкант", "draw"],
  ["creative", 1, "Actor", "Актёр", "draw"],
  ["creative", 1, "Photographer", "Фотограф", "draw"],
  ["creative", 1, "Singer", "Певец", "draw"],
  ["creative", 2, "Writer", "Писатель", "draw"],
  ["creative", 2, "Designer", "Дизайнер", "draw"],
  ["creative", 2, "Dancer", "Танцор", "draw"],
  ["creative", 2, "Architect", "Архитектор", "draw"],
  ["creative", 2, "Sculptor", "Скульптор", "draw"],
  ["creative", 2, "Filmmaker", "Режиссёр", "draw"],
  ["creative", 2, "Animator", "Аниматор", "draw"],
  ["creative", 2, "DJ", "Диджей", "draw"],
  ["creative", 2, "Comedian", "Комик", "draw"],
  ["creative", 3, "Illustrator", "Иллюстратор", "draw"],
  ["creative", 3, "Composer", "Композитор"],
  ["creative", 3, "Puppeteer", "Кукловод", "draw"],
  ["creative", 3, "Fashion Designer", "Модельер", "draw"],

  ["unusual", 1, "Astronaut", "Космонавт", "draw"],
  ["unusual", 2, "Lighthouse Keeper", "Смотритель маяка", "draw"],
  ["unusual", 2, "Beekeeper", "Пчеловод", "draw"],
  ["unusual", 2, "Magician", "Фокусник", "draw"],
  ["unusual", 2, "Tattoo Artist", "Тату-мастер", "draw"],
  ["unusual", 2, "Zookeeper", "Смотритель зоопарка", "draw"],
  ["unusual", 2, "Stuntman", "Каскадёр", "draw"],
  ["unusual", 2, "Diver", "Водолаз", "draw"],
  ["unusual", 2, "Lumberjack", "Лесоруб", "draw"],
  ["unusual", 2, "Clown", "Клоун", "draw"],
  ["unusual", 2, "Spy", "Шпион", "draw"],
  ["unusual", 2, "Ice Cream Man", "Мороженщик", "draw"],
  ["unusual", 3, "Falconer", "Сокольничий", "draw"],
  ["unusual", 3, "Sword Swallower", "Глотатель мечей", "draw"],
  ["unusual", 3, "Chimney Sweep", "Трубочист", "draw"],
  ["unusual", 3, "Pearl Diver", "Ловец жемчуга", "draw"],
  ["unusual", 3, "Snake Charmer", "Заклинатель змей", "draw"],
  ["unusual", 3, "Fortune Teller", "Гадалка", "draw"],
]);
