/* K-pop */
addWords("kpop", [
  ["boygroups", 1, "BTS", "BTS"],
  ["boygroups", 1, "BIGBANG", "BIGBANG"],
  ["boygroups", 1, "EXO", "EXO"],
  ["boygroups", 2, "SEVENTEEN", "SEVENTEEN"],
  ["boygroups", 2, "Stray Kids", "Stray Kids"],
  ["boygroups", 2, "NCT", "NCT"],
  ["boygroups", 2, "TXT", "TXT"],
  ["boygroups", 2, "ATEEZ", "ATEEZ"],
  ["boygroups", 2, "ENHYPEN", "ENHYPEN"],
  ["boygroups", 2, "SHINee", "SHINee"],
  ["boygroups", 2, "Super Junior", "Super Junior"],
  ["boygroups", 2, "GOT7", "GOT7"],
  ["boygroups", 2, "Monsta X", "Monsta X"],
  ["boygroups", 2, "TVXQ", "TVXQ"],
  ["boygroups", 2, "The Boyz", "The Boyz"],
  ["boygroups", 3, "iKON", "iKON"],
  ["boygroups", 3, "BTOB", "BTOB"],
  ["boygroups", 3, "Pentagon", "Pentagon"],
  ["boygroups", 3, "NCT Dream", "NCT Dream"],
  ["boygroups", 3, "P1Harmony", "P1Harmony"],
  ["boygroups", 3, "Treasure", "Treasure"],
  ["boygroups", 3, "Astro", "Astro"],
  ["boygroups", 3, "DAY6", "DAY6"],
  ["boygroups", 3, "2PM", "2PM"],
  ["boygroups", 3, "INFINITE", "INFINITE"],
  ["boygroups", 3, "SF9", "SF9"],
  ["boygroups", 3, "VICTON", "VICTON"],
  ["boygroups", 3, "CRAVITY", "CRAVITY"],
  ["boygroups", 3, "U-KISS", "U-KISS"],
  ["girlgroups", 1, "BLACKPINK", "BLACKPINK"],
  ["girlgroups", 1, "TWICE", "TWICE"],
  ["girlgroups", 1, "Girls' Generation", "Girls' Generation"],
  ["girlgroups", 2, "aespa", "aespa"],
  ["girlgroups", 2, "NewJeans", "NewJeans"],
  ["girlgroups", 2, "ITZY", "ITZY"],
  ["girlgroups", 2, "Red Velvet", "Red Velvet"],
  ["girlgroups", 2, "(G)I-DLE", "(G)I-DLE"],
  ["girlgroups", 2, "IVE", "IVE"],
  ["girlgroups", 2, "LE SSERAFIM", "LE SSERAFIM"],
  ["girlgroups", 2, "MAMAMOO", "MAMAMOO"],
  ["girlgroups", 2, "2NE1", "2NE1"],
  ["girlgroups", 2, "NMIXX", "NMIXX"],
  ["girlgroups", 2, "Wonder Girls", "Wonder Girls"],
  ["girlgroups", 3, "fromis_9", "fromis_9"],
  ["girlgroups", 3, "Apink", "Apink"],
  ["girlgroups", 3, "EXID", "EXID"],
  ["girlgroups", 3, "GFRIEND", "GFRIEND"],
  ["girlgroups", 3, "Oh My Girl", "Oh My Girl"],
  ["girlgroups", 3, "STAYC", "STAYC"],
  ["girlgroups", 3, "Kep1er", "Kep1er"],
  ["girlgroups", 3, "Brave Girls", "Brave Girls"],
  ["girlgroups", 3, "f(x)", "f(x)"],
  ["girlgroups", 3, "SISTAR", "SISTAR"],
  ["girlgroups", 3, "4Minute", "4Minute"],
  ["girlgroups", 3, "Lovelyz", "Lovelyz"],
  ["girlgroups", 3, "T-ara", "T-ara"],
  ["soloists", 1, "IU", "Айю"],
  ["soloists", 1, "PSY", "Пси"],
  ["soloists", 1, "G-Dragon", "Джи-Дрэгон"],
  ["soloists", 2, "Jungkook", "Чонгук"],
  ["soloists", 2, "Jimin", "Чимин"],
  ["soloists", 2, "V", "Ви"],
  ["soloists", 2, "Lisa", "Лиса"],
  ["soloists", 2, "Jennie", "Дженни"],
  ["soloists", 2, "Rosé", "Розэ"],
  ["soloists", 2, "Jisoo", "Джису"],
  ["soloists", 2, "Taeyeon", "Тхэён"],
  ["soloists", 2, "Taeyang", "Тхэян"],
  ["soloists", 2, "BoA", "Боа"],
  ["soloists", 2, "Sunmi", "Сонми"],
  ["soloists", 2, "Hwasa", "Хваса"],
  ["soloists", 2, "Zico", "Зико"],
  ["soloists", 2, "CL", "Си-эль"],
  ["soloists", 2, "Chungha", "Чхонха"],
  ["soloists", 3, "Heize", "Хэйз"],
  ["soloists", 3, "Jay Park", "Джей Парк"],
  ["soloists", 3, "Rain", "Рэйн"],
  ["soloists", 3, "Taemin", "Тхэмин"],
  ["soloists", 3, "Kai", "Кай"],
  ["soloists", 3, "Baekhyun", "Бэкхён"],
  ["soloists", 3, "Xiumin", "Сюмин"],
  ["soloists", 3, "Sehun", "Сехун"],
  ["soloists", 3, "Wheein", "Хвиин"],
  ["soloists", 3, "Moonbyul", "Мунбёль"],
  ["soloists", 3, "Solar", "Солар"],
  ["soloists", 3, "Eunha", "Ынха"],
  ["rookies", 1, "RIIZE", "RIIZE"],
  ["rookies", 1, "BABYMONSTER", "BABYMONSTER"],
  ["rookies", 1, "ILLIT", "ILLIT"],
  ["rookies", 2, "ZEROBASEONE", "ZEROBASEONE"],
  ["rookies", 2, "KISS OF LIFE", "KISS OF LIFE"],
  ["rookies", 2, "TWS", "TWS"],
  ["rookies", 2, "BOYNEXTDOOR", "BOYNEXTDOOR"],
  ["rookies", 2, "NCT Wish", "NCT Wish"],
  ["rookies", 2, "Hearts2Hearts", "Hearts2Hearts"],
  ["rookies", 2, "izna", "izna"],
  ["rookies", 3, "MEOVV", "MEOVV"],
  ["rookies", 3, "UNIS", "UNIS"],
  ["rookies", 3, "AMPERS&ONE", "AMPERS&ONE"],
  ["rookies", 3, "NEXZ", "NEXZ"],
  ["rookies", 3, "tripleS", "tripleS"],
  ["rookies", 3, "RESCENE", "RESCENE"],
  ["rookies", 3, "NOWADAYS", "NOWADAYS"],
  ["rookies", 3, "FANTASY BOYS", "FANTASY BOYS"],
  ["rookies", 3, "TEMPEST", "TEMPEST"],
  ["rookies", 3, "DXMON", "DXMON"],
]);
