/* Music (with years) */
addWords("music", [
  // [ subgroupId, difficulty, "EN", "RU", YEAR ]

  // --- POP ---
  ["pop", 1, "Taylor Swift", "Тейлор Свифт", 2006],
  ["pop", 1, "Michael Jackson", "Майкл Джексон", 1982],
  ["pop", 1, "Madonna", "Мадонна", 1983],
  ["pop", 1, "Beyoncé", "Бейонсе", 2003],
  ["pop", 1, "Adele", "Адель", 2008],
  ["pop", 2, "Ed Sheeran", "Эд Ширан", 2011],
  ["pop", 2, "Ariana Grande", "Ариана Гранде", 2013],
  ["pop", 2, "Billie Eilish", "Билли Айлиш", 2019],
  ["pop", 2, "The Weeknd", "Уикнд", 2015],
  ["pop", 2, "Harry Styles", "Гарри Стайлс", 2012],
  ["pop", 2, "Dua Lipa", "Дуа Липа", 2018],
  ["pop", 2, "Rihanna", "Рианна", 2007],
  ["pop", 2, "Justin Bieber", "Джастин Бибер", 2010],
  ["pop", 2, "Lady Gaga", "Леди Гага", 2008],
  ["pop", 2, "Katy Perry", "Кэти Перри", 2010],
  ["pop", 2, "Bruno Mars", "Бруно Марс", 2010],
  ["pop", 2, "Olivia Rodrigo", "Оливия Родриго", 2021],
  ["pop", 2, "Sabrina Carpenter", "Сабрина Карпентер", 2024],
  ["pop", 3, "Sam Smith", "Сэм Смит", 2014],
  ["pop", 3, "Lorde", "Лорд", 2013],
  ["pop", 3, "Charli XCX", "Чарли ИксСиИкс", 2014],
  ["pop", 3, "Troye Sivan", "Трой Сиван", 2015],
  ["pop", 3, "Halsey", "Холзи", 2015],
  ["pop", 3, "Lizzo", "Лиззо", 2019],
  ["pop", 3, "Sia", "Сиа", 2014],
  ["pop", 3, "Demi Lovato", "Деми Ловато", 2008],

  // --- HIPHOP (RAP) ---
  ["hiphop", 1, "Eminem", "Эминем", 1999],
  ["hiphop", 1, "Drake", "Дрейк", 2010],
  ["hiphop", 1, "Jay-Z", "Джей-Зи", 1996],
  ["hiphop", 1, "Kanye West", "Канье Уэст", 2004],
  ["hiphop", 1, "Kendrick Lamar", "Кендрик Ламар", 2012],
  ["hiphop", 2, "Lil Wayne", "Лил Уэйн", 2008],
  ["hiphop", 2, "Nicki Minaj", "Ники Минаж", 2010],
  ["hiphop", 2, "Cardi B", "Карди Би", 2018],
  ["hiphop", 2, "Travis Scott", "Трэвис Скотт", 2016],
  ["hiphop", 2, "Post Malone", "Пост Мэлоун", 2016],
  ["hiphop", 2, "21 Savage", "21 Сэвидж", 2016],
  ["hiphop", 2, "Snoop Dogg", "Снуп Догг", 1993],
  ["hiphop", 2, "J. Cole", "Джей Коул", 2013],
  ["hiphop", 2, "50 Cent", "50 Сент", 2003],
  ["hiphop", 2, "Doja Cat", "Доджа Кэт", 2020],
  ["hiphop", 2, "Megan Thee Stallion", "Меган Зе Стэльон", 2019],
  ["hiphop", 3, "Tupac", "Тупак", 1996],
  ["hiphop", 3, "Notorious B.I.G.", "Notorious B.I.G.", 1994],
  ["hiphop", 3, "Tyler, the Creator", "Тайлер, де Криэйтор", 2011],
  ["hiphop", 3, "A$AP Rocky", "ЭСЭП Рокки", 2013],
  ["hiphop", 3, "Lil Uzi Vert", "Лил Узи Верт", 2017],
  ["hiphop", 3, "Future", "Фьючер", 2012],
  ["hiphop", 3, "Gunna", "Ганна", 2018],
  ["hiphop", 3, "Ice Spice", "Айс Спайс", 2023],

  // --- LATIN ---
  ["latin", 1, "Bad Bunny", "Бэд Банни", 2017],
  ["latin", 1, "Shakira", "Шакира", 2001],
  ["latin", 1, "J Balvin", "Джей Балвин", 2017],
  ["latin", 2, "Ozuna", "Озуна", 2016],
  ["latin", 2, "Daddy Yankee", "Дэдди Янки", 2004],
  ["latin", 2, "Maluma", "Малума", 2015],
  ["latin", 2, "Karol G", "Кароль Джи", 2021],
  ["latin", 2, "Rauw Alejandro", "Рауль Алехандро", 2020],
  ["latin", 2, "Nicky Jam", "Ники Джэм", 2017],
  ["latin", 2, "Anuel AA", "Ануэль АА", 2018],
  ["latin", 2, "Rosalía", "Росалия", 2018],
  ["latin", 2, "Enrique Iglesias", "Энрике Иглесиас", 1999],
  ["latin", 2, "Marc Anthony", "Марк Энтони", 1999],
  ["latin", 3, "Peso Pluma", "Песо Плума", 2023],
  ["latin", 3, "Feid", "Фейд", 2022],
  ["latin", 3, "Becky G", "Бекки Джи", 2013],
  ["latin", 3, "Sech", "Сеч", 2019],
  ["latin", 3, "Myke Towers", "Майк Тауэрс", 2020],
  ["latin", 3, "Natanael Cano", "Натанаэль Кано", 2021],
  ["latin", 3, "Farruko", "Фаррuco", 2012],
  ["latin", 3, "Don Omar", "Дон Омар", 2003],
  ["latin", 3, "Camilo", "Камило", 2020],

  // --- ROCK (& LEGENDS) ---
  ["rock", 1, "The Beatles", "The Beatles", 1963],
  ["rock", 1, "Queen", "Queen", 1975],
  ["rock", 1, "Led Zeppelin", "Led Zeppelin", 1969],
  ["rock", 1, "AC/DC", "AC/DC", 1975],
  ["rock", 1, "Metallica", "Metallica", 1986],
  ["rock", 2, "The Rolling Stones", "The Rolling Stones", 1965],
  ["rock", 2, "Nirvana", "Nirvana", 1991],
  ["rock", 2, "Pink Floyd", "Pink Floyd", 1973],
  ["rock", 2, "U2", "U2", 1987],
  ["rock", 2, "Guns N' Roses", "Guns N' Roses", 1987],
  ["rock", 2, "Coldplay", "Coldplay", 2000],
  ["rock", 2, "Red Hot Chili Peppers", "Red Hot Chili Peppers", 1991],
  ["rock", 2, "Linkin Park", "Linkin Park", 2001],
  ["rock", 2, "Imagine Dragons", "Imagine Dragons", 2012],
  ["rock", 2, "David Bowie", "Дэвид Боуи", 1972],
  ["rock", 2, "Fleetwood Mac", "Fleetwood Mac", 1977],
  ["rock", 3, "Radiohead", "Radiohead", 1997],
  ["rock", 3, "Foo Fighters", "Foo Fighters", 1997],
  ["rock", 3, "Pearl Jam", "Pearl Jam", 1991],
  ["rock", 3, "Green Day", "Green Day", 1994],
  ["rock", 3, "System of a Down", "System of a Down", 2001],
  ["rock", 3, "Arctic Monkeys", "Arctic Monkeys", 2006],
  ["rock", 3, "The Strokes", "The Strokes", 2001],
  ["rock", 3, "Tame Impala", "Tame Impala", 2012],
  ["rock", 3, "Soundgarden", "Soundgarden", 1994],

  // --- EDM (DJs) ---
  ["edm", 1, "Daft Punk", "Daft Punk", 2001],
  ["edm", 1, "Calvin Harris", "Кэлвин Харрис", 2012],
  ["edm", 1, "David Guetta", "Дэвид Гетта", 2009],
  ["edm", 2, "Tiësto", "Тиесто", 2004],
  ["edm", 2, "Martin Garrix", "Мартин Гаррикс", 2013],
  ["edm", 2, "Avicii", "Авичи", 2011],
  ["edm", 2, "Skrillex", "Скриллекс", 2011],
  ["edm", 2, "Marshmello", "Маршмелло", 2016],
  ["edm", 2, "Zedd", "Зедд", 2012],
  ["edm", 2, "Deadmau5", "Дедмаус", 2009],
  ["edm", 2, "Kygo", "Кайго", 2015],
  ["edm", 2, "Swedish House Mafia", "Swedish House Mafia", 2012],
  ["edm", 2, "The Chainsmokers", "The Chainsmokers", 2016],
  ["edm", 2, "Diplo", "Дипло", 2012],
  ["edm", 3, "Aphex Twin", "Aphex Twin", 1992],
  ["edm", 3, "Disclosure", "Disclosure", 2013],
  ["edm", 3, "Porter Robinson", "Портер Робинсон", 2014],
  ["edm", 3, "Flume", "Флюм", 2012],
  ["edm", 3, "Odesza", "Одеза", 2014],
  ["edm", 3, "Fred Again..", "Фред Эгейн", 2022],
  ["edm", 3, "John Summit", "Джон Саммит", 2021],
  ["edm", 3, "Illenium", "Илениум", 2016],
  ["edm", 3, "Fisher", "Фишер", 2019],

  // --- COUNTRY ---
  ["country", 1, "Dolly Parton", "Долли Партон", 1974],
  ["country", 1, "Johnny Cash", "Джонни Кэш", 1956],
  ["country", 1, "Garth Brooks", "Гарт Брукс", 1989],
  ["country", 2, "Morgan Wallen", "Морган Уоллен", 2018],
  ["country", 2, "Luke Combs", "Люк Комбс", 2017],
  ["country", 2, "Shania Twain", "Шания Твейн", 1997],
  ["country", 2, "Carrie Underwood", "Кэрри Андервуд", 2005],
  ["country", 2, "Blake Shelton", "Блейк Шелтон", 2011],
  ["country", 2, "Kenny Rogers", "Кенни Роджерс", 1978],
  ["country", 2, "Zach Bryan", "Зак Брайан", 2022],
  ["country", 2, "Tim McGraw", "Тим МакГро", 1994],
  ["country", 2, "Keith Urban", "Кит Эрбан", 2000],
  ["country", 2, "Miranda Lambert", "Миранда Ламберт", 2005],
  ["country", 2, "Willie Nelson", "Уилли Нельсон", 1975],
  ["country", 3, "Chris Stapleton", "Крис Стэплтон", 2015],
  ["country", 3, "Kacey Musgraves", "Кейси Масгрейвс", 2013],
  ["country", 3, "Tyler Childers", "Тайлер Чайлдерс", 2017],
  ["country", 3, "Lainey Wilson", "Лейни Уилсон", 2023],
  ["country", 3, "Zac Brown Band", "Zac Brown Band", 2008],
  ["country", 3, "Cody Johnson", "Коди Джонсон", 2016],
  ["country", 3, "Alan Jackson", "Алан Джэксон", 1989],
  ["country", 3, "Brad Paisley", "Брэд Пэйсли", 1999],
  ["country", 3, "Toby Keith", "Тоби Кит", 1993],
]);
