/* Nature (easy-heavy) */
addWords("nature", [
  ["weather", 1, "Sun", "Солнце", "draw"],
  ["weather", 1, "Rain", "Дождь", "draw"],
  ["weather", 1, "Snow", "Снег", "draw"],
  ["weather", 1, "Cloud", "Облако", "draw"],
  ["weather", 1, "Rainbow", "Радуга", "draw"],
  ["weather", 1, "Wind", "Ветер", "draw"],
  ["weather", 1, "Ice", "Лёд", "draw"],
  ["weather", 1, "Thunder", "Гром", "draw"],
  ["weather", 1, "Lightning", "Молния", "draw"],
  ["weather", 1, "Fog", "Туман", "draw"],
  ["weather", 1, "Frost", "Иней", "draw"],
  ["weather", 1, "Storm", "Гроза", "draw"],
  ["weather", 1, "Flood", "Наводнение", "draw"],
  ["weather", 1, "Puddle", "Лужа", "draw"],
  ["weather", 1, "Snowflake", "Снежинка", "draw"],
  ["weather", 1, "Sunshine", "Солнечный свет", "draw"],
  ["weather", 1, "Hail", "Град", "draw"],
  ["weather", 1, "Dew", "Роса", "draw"],
  ["weather", 1, "Mist", "Дымка", "draw"],
  ["weather", 1, "Icicle", "Сосулька", "draw"],
  ["weather", 1, "Raindrop", "Капля дождя", "draw"],
  ["weather", 1, "Blizzard", "Метель", "draw"],
  ["weather", 1, "Breeze", "Бриз", "draw"],
  ["weather", 2, "Drizzle", "Морось", "draw"],
  ["weather", 2, "Thunderstorm", "Гроза с молнией", "draw"],
  ["weather", 2, "Tornado", "Торнадо", "draw"],
  ["weather", 2, "Hurricane", "Ураган", "draw"],
  ["weather", 2, "Heatwave", "Жара", "draw"],
  ["weather", 2, "Drought", "Засуха", "draw"],
  ["weather", 2, "Sleet", "Мокрый снег", "draw"],
  ["weather", 3, "Sandstorm", "Песчаная буря", "draw"],
  ["weather", 3, "Monsoon", "Муссон", "draw"],
  ["weather", 3, "Typhoon", "Тайфун", "draw"],
  ["weather", 3, "Dust devil", "Пыльный вихрь", "draw"],

  ["plants", 1, "Tree", "Дерево", "draw"],
  ["plants", 1, "Flower", "Цветок", "draw"],
  ["plants", 1, "Rose", "Роза", "draw"],
  ["plants", 1, "Grass", "Трава", "draw"],
  ["plants", 1, "Leaf", "Лист", "draw"],
  ["plants", 1, "Mushroom", "Гриб", "draw"],
  ["plants", 1, "Cactus", "Кактус", "draw"],
  ["plants", 1, "Sunflower", "Подсолнух", "draw"],
  ["plants", 1, "Daisy", "Ромашка", "draw"],
  ["plants", 1, "Tulip", "Тюльпан", "draw"],
  ["plants", 1, "Oak", "Дуб", "draw"],
  ["plants", 1, "Palm tree", "Пальма", "draw"],
  ["plants", 1, "Seed", "Семя", "draw"],
  ["plants", 1, "Branch", "Ветка", "draw"],
  ["plants", 1, "Root", "Корень", "draw"],
  ["plants", 1, "Bush", "Куст", "draw"],
  ["plants", 1, "Vine", "Лоза", "draw"],
  ["plants", 1, "Lily", "Лилия", "draw"],
  ["plants", 1, "Bamboo", "Бамбук", "draw"],
  ["plants", 1, "Acorn", "Желудь", "draw"],
  ["plants", 1, "Pinecone", "Шишка", "draw"],
  ["plants", 1, "Berry", "Ягода", "draw"],
  ["plants", 1, "Dandelion", "Одуванчик", "draw"],
  ["plants", 2, "Fern", "Папоротник", "draw"],
  ["plants", 2, "Ivy", "Плющ", "draw"],
  ["plants", 2, "Moss", "Мох", "draw"],
  ["plants", 2, "Maple", "Клён", "draw"],
  ["plants", 2, "Pine", "Сосна", "draw"],
  ["plants", 2, "Clover", "Клевер", "draw"],
  ["plants", 2, "Willow", "Ива", "draw"],
  ["plants", 2, "Cherry blossom", "Сакура", "draw"],
  ["plants", 2, "Apple tree", "Яблоня", "draw"],
  ["plants", 2, "Birch", "Берёза", "draw"],
  ["plants", 3, "Lavender", "Лаванда", "draw"],
  ["plants", 3, "Orchid", "Орхидея", "draw"],
  ["plants", 3, "Water lily", "Кувшинка", "draw"],
  ["plants", 3, "Cedar", "Кедр", "draw"],
  ["plants", 3, "Fir", "Ель", "draw"],
  ["plants", 3, "Weed", "Сорняк", "draw"],
  ["plants", 3, "Baobab", "Баобаб", "draw"],

  ["landforms", 1, "Mountain", "Гора", "draw"],
  ["landforms", 1, "River", "Река", "draw"],
  ["landforms", 1, "Lake", "Озеро", "draw"],
  ["landforms", 1, "Beach", "Пляж", "draw"],
  ["landforms", 1, "Ocean", "Океан", "draw"],
  ["landforms", 1, "Sea", "Море", "draw"],
  ["landforms", 1, "Island", "Остров", "draw"],
  ["landforms", 1, "Volcano", "Вулкан", "draw"],
  ["landforms", 1, "Waterfall", "Водопад", "draw"],
  ["landforms", 1, "Forest", "Лес", "draw"],
  ["landforms", 1, "Desert", "Пустыня", "draw"],
  ["landforms", 1, "Cave", "Пещера", "draw"],
  ["landforms", 1, "Hill", "Холм", "draw"],
  ["landforms", 1, "Valley", "Долина", "draw"],
  ["landforms", 1, "Field", "Поле", "draw"],
  ["landforms", 1, "Rock", "Скала", "draw"],
  ["landforms", 1, "Pond", "Пруд", "draw"],
  ["landforms", 1, "Stream", "Ручей", "draw"],
  ["landforms", 1, "Jungle", "Джунгли", "draw"],
  ["landforms", 1, "Cliff", "Утёс", "draw"],
  ["landforms", 1, "Iceberg", "Айсберг", "draw"],
  ["landforms", 2, "Canyon", "Каньон", "draw"],
  ["landforms", 2, "Glacier", "Ледник", "draw"],
  ["landforms", 2, "Swamp", "Болото", "draw"],
  ["landforms", 2, "Meadow", "Луг", "draw"],
  ["landforms", 2, "Plain", "Равнина", "draw"],
  ["landforms", 2, "Dune", "Дюна", "draw"],
  ["landforms", 2, "Bay", "Залив", "draw"],
  ["landforms", 2, "Reef", "Риф", "draw"],
  ["landforms", 2, "Coast", "Побережье", "draw"],
  ["landforms", 3, "Peninsula", "Полуостров", "draw"],
  ["landforms", 3, "Plateau", "Плато", "draw"],
  ["landforms", 3, "Geyser", "Гейзер", "draw"],
  ["landforms", 3, "Lagoon", "Лагуна", "draw"],
  ["landforms", 3, "Delta", "Дельта", "draw"],
  ["landforms", 3, "Fjord", "Фьорд", "draw"],
  ["landforms", 3, "Tundra", "Тундра", "draw"],

  ["space", 1, "Star", "Звезда", "draw"],
  ["space", 1, "Moon", "Луна", "draw"],
  ["space", 1, "Planet", "Планета", "draw"],
  ["space", 1, "Earth", "Земля", "draw"],
  ["space", 1, "Sky", "Небо", "draw"],
  ["space", 1, "Sunrise", "Рассвет", "draw"],
  ["space", 1, "Sunset", "Закат", "draw"],
  ["space", 1, "Full moon", "Полная луна", "draw"],
  ["space", 1, "Shooting star", "Падающая звезда", "draw"],
  ["space", 1, "Rocket", "Ракета", "draw"],
  ["space", 1, "Eclipse", "Затмение", "draw"],
  ["space", 1, "Comet", "Комета", "draw"],
  ["space", 1, "Night sky", "Ночное небо", "draw"],
  ["space", 1, "Mars", "Марс", "draw"],
  ["space", 1, "Saturn", "Сатурн", "draw"],
  ["space", 2, "Galaxy", "Галактика", "draw"],
  ["space", 2, "Meteor", "Метеор", "draw"],
  ["space", 2, "Aurora", "Северное сияние", "draw"],
  ["space", 2, "Milky Way", "Млечный путь", "draw"],
  ["space", 2, "Constellation", "Созвездие", "draw"],
  ["space", 2, "Crescent moon", "Полумесяц", "draw"],
  ["space", 2, "Asteroid", "Астероид", "draw"],
  ["space", 2, "North Star", "Полярная звезда", "draw"],
  ["space", 2, "Jupiter", "Юпитер", "draw"],
  ["space", 2, "Venus", "Венера", "draw"],
  ["space", 3, "Satellite", "Спутник", "draw"],
  ["space", 3, "Nebula", "Туманность", "draw"],
  ["space", 3, "Black hole", "Чёрная дыра", "draw"],
  ["space", 3, "Supernova", "Сверхновая", "draw"],
  ["space", 3, "Solar system", "Солнечная система", "draw"],
]);
