/* Objects */
addWords("objects", [
  ["household", 1, "Chair", "Стул", "draw"],
  ["household", 1, "Table", "Стол", "draw"],
  ["household", 1, "Lamp", "Лампа", "draw"],
  ["household", 1, "Clock", "Часы", "draw"],
  ["household", 1, "Mirror", "Зеркало", "draw"],
  ["household", 1, "Pillow", "Подушка", "draw"],
  ["household", 1, "Blanket", "Одеяло", "draw"],
  ["household", 2, "Curtain", "Штора", "draw"],
  ["household", 2, "Carpet", "Ковёр", "draw"],
  ["household", 2, "Vase", "Ваза", "draw"],
  ["household", 2, "Candle", "Свеча", "draw"],
  ["household", 2, "Trash Can", "Мусорное ведро", "draw"],
  ["household", 2, "Broom", "Метла", "draw"],
  ["household", 2, "Bucket", "Ведро", "draw"],
  ["household", 1, "Sofa", "Диван", "draw"],
  ["household", 1, "Bed", "Кровать", "draw"],
  ["household", 2, "Shelf", "Полка", "draw"],
  ["household", 2, "Drawer", "Ящик комода", "draw"],
  ["household", 2, "Doormat", "Коврик у двери", "draw"],
  ["household", 2, "Picture Frame", "Рамка для фото", "draw"],
  ["household", 3, "Light Switch", "Выключатель", "draw"],
  ["household", 2, "Fan", "Вентилятор", "draw"],
  ["household", 3, "Mop", "Швабра", "draw"],

  ["kitchen", 1, "Spoon", "Ложка", "draw"],
  ["kitchen", 1, "Fork", "Вилка", "draw"],
  ["kitchen", 1, "Knife", "Нож", "draw"],
  ["kitchen", 1, "Plate", "Тарелка", "draw"],
  ["kitchen", 1, "Cup", "Кружка", "draw"],
  ["kitchen", 1, "Pot", "Кастрюля", "draw"],
  ["kitchen", 1, "Pan", "Сковорода", "draw"],
  ["kitchen", 1, "Kettle", "Чайник", "draw"],
  ["kitchen", 2, "Toaster", "Тостер", "draw"],
  ["kitchen", 2, "Blender", "Блендер", "draw"],
  ["kitchen", 2, "Whisk", "Венчик", "draw"],
  ["kitchen", 2, "Cutting Board", "Разделочная доска", "draw"],
  ["kitchen", 1, "Mug", "Чашка", "draw"],
  ["kitchen", 1, "Bowl", "Миска", "draw"],
  ["kitchen", 2, "Ladle", "Половник", "draw"],
  ["kitchen", 2, "Grater", "Тёрка", "draw"],
  ["kitchen", 3, "Can Opener", "Консервный нож", "draw"],
  ["kitchen", 1, "Oven", "Духовка", "draw"],
  ["kitchen", 1, "Fridge", "Холодильник", "draw"],
  ["kitchen", 1, "Microwave", "Микроволновка", "draw"],
  ["kitchen", 2, "Teapot", "Заварочный чайник", "draw"],
  ["kitchen", 3, "Colander", "Дуршлаг", "draw"],
  ["kitchen", 2, "Rolling Pin", "Скалка", "draw"],

  ["tools", 1, "Scissors", "Ножницы", "draw"],
  ["tools", 1, "Hammer", "Молоток", "draw"],
  ["tools", 1, "Screwdriver", "Отвёртка", "draw"],
  ["tools", 2, "Wrench", "Гаечный ключ", "draw"],
  ["tools", 2, "Drill", "Дрель", "draw"],
  ["tools", 2, "Saw", "Пила", "draw"],
  ["tools", 1, "Nail", "Гвоздь", "draw"],
  ["tools", 1, "Tape", "Скотч", "draw"],
  ["tools", 2, "Ladder", "Лестница", "draw"],
  ["tools", 2, "Rope", "Верёвка", "draw"],
  ["tools", 2, "Pliers", "Плоскогубцы", "draw"],
  ["tools", 3, "Wheelbarrow", "Тачка", "draw"],
  ["tools", 2, "Shovel", "Лопата", "draw"],
  ["tools", 2, "Axe", "Топор", "draw"],
  ["tools", 3, "Chisel", "Стамеска", "draw"],
  ["tools", 3, "Level", "Уровень", "draw"],
  ["tools", 2, "Flashlight", "Фонарик", "draw"],
  ["tools", 2, "Toolbox", "Ящик с инструментами", "draw"],
  ["tools", 2, "Paintbrush", "Кисть для краски", "draw"],
  ["tools", 3, "Sandpaper", "Наждачная бумага", "draw"],
  ["tools", 3, "Bolt", "Болт", "draw"],

  ["tech", 1, "Phone", "Телефон", "draw"],
  ["tech", 1, "Laptop", "Ноутбук", "draw"],
  ["tech", 1, "Headphones", "Наушники", "draw"],
  ["tech", 1, "Charger", "Зарядка", "draw"],
  ["tech", 1, "Camera", "Фотоаппарат", "draw"],
  ["tech", 1, "TV", "Телевизор", "draw"],
  ["tech", 1, "Remote", "Пульт", "draw"],
  ["tech", 1, "Keyboard", "Клавиатура", "draw"],
  ["tech", 1, "Mouse", "Мышь", "draw"],
  ["tech", 2, "Speaker", "Колонка", "draw"],
  ["tech", 2, "Router", "Роутер", "draw"],
  ["tech", 1, "Tablet", "Планшет", "draw"],
  ["tech", 2, "Game Console", "Игровая приставка", "draw"],
  ["tech", 2, "Microphone", "Микрофон", "draw"],
  ["tech", 2, "Smartwatch", "Умные часы", "draw"],
  ["tech", 2, "Printer", "Принтер", "draw"],
  ["tech", 1, "Monitor", "Монитор", "draw"],
  ["tech", 2, "USB Stick", "Флешка", "draw"],
  ["tech", 2, "Power Bank", "Пауэрбанк", "draw"],
  ["tech", 3, "Webcam", "Веб-камера", "draw"],
  ["tech", 3, "Hard Drive", "Жёсткий диск", "draw"],

  ["clothing", 1, "Shirt", "Рубашка", "draw"],
  ["clothing", 1, "Pants", "Брюки", "draw"],
  ["clothing", 1, "Shoes", "Ботинки", "draw"],
  ["clothing", 1, "Hat", "Шапка", "draw"],
  ["clothing", 1, "Socks", "Носки", "draw"],
  ["clothing", 1, "Jacket", "Куртка", "draw"],
  ["clothing", 1, "Gloves", "Перчатки", "draw"],
  ["clothing", 1, "Scarf", "Шарф", "draw"],
  ["clothing", 2, "Belt", "Ремень", "draw"],
  ["clothing", 2, "Tie", "Галстук", "draw"],
  ["clothing", 1, "Dress", "Платье", "draw"],
  ["clothing", 1, "Sunglasses", "Солнечные очки", "draw"],
  ["clothing", 1, "Backpack", "Рюкзак", "draw"],
  ["clothing", 1, "Umbrella", "Зонт", "draw"],
  ["clothing", 1, "Boots", "Сапоги", "draw"],
  ["clothing", 1, "Sweater", "Свитер", "draw"],
  ["clothing", 1, "Shorts", "Шорты", "draw"],
  ["clothing", 2, "Skirt", "Юбка", "draw"],
  ["clothing", 2, "Helmet", "Шлем", "draw"],
  ["clothing", 2, "Watch", "Наручные часы", "draw"],
  ["clothing", 2, "Glasses", "Очки", "draw"],
  ["clothing", 2, "Handbag", "Сумочка", "draw"],

  ["stationery", 1, "Pen", "Ручка", "draw"],
  ["stationery", 1, "Pencil", "Карандаш", "draw"],
  ["stationery", 1, "Notebook", "Тетрадь", "draw"],
  ["stationery", 1, "Eraser", "Ластик", "draw"],
  ["stationery", 2, "Stapler", "Степлер", "draw"],
  ["stationery", 2, "Paperclip", "Скрепка", "draw"],
  ["stationery", 1, "Glue", "Клей", "draw"],
  ["stationery", 1, "Ruler", "Линейка", "draw"],
  ["stationery", 1, "Marker", "Маркер", "draw"],
  ["stationery", 2, "Envelope", "Конверт", "draw"],
  ["stationery", 1, "Book", "Книга", "draw"],
  ["stationery", 1, "Key", "Ключ", "draw"],
  ["stationery", 1, "Wallet", "Кошелёк", "draw"],
  ["stationery", 2, "Calculator", "Калькулятор", "draw"],
  ["stationery", 2, "Tape Dispenser", "Диспенсер для скотча", "draw"],
  ["stationery", 2, "Highlighter", "Маркер-выделитель", "draw"],
  ["stationery", 2, "Sticky Note", "Стикер", "draw"],
  ["stationery", 2, "Folder", "Папка", "draw"],
  ["stationery", 1, "Crayon", "Мелок", "draw"],
  ["stationery", 3, "Compass", "Циркуль", "draw"],
  ["stationery", 3, "Protractor", "Транспортир", "draw"],
  ["stationery", 2, "Scissors", "Ножницы", "draw"],
]);
