/* Places */
addWords("places", [
  ["home", 1, "Garage", "Гараж", "draw"],
  ["home", 1, "Kitchen", "Кухня", "draw"],
  ["home", 1, "Bedroom", "Спальня", "draw"],
  ["home", 1, "Bathroom", "Ванная", "draw"],
  ["home", 1, "Living Room", "Гостиная", "draw"],
  ["home", 2, "Backyard", "Задний двор", "draw"],
  ["home", 2, "Balcony", "Балкон", "draw"],
  ["home", 2, "Basement", "Подвал", "draw"],
  ["home", 2, "Attic", "Чердак", "draw"],
  ["home", 2, "Hallway", "Прихожая", "draw"],
  ["home", 2, "Dining Room", "Столовая", "draw"],
  ["home", 2, "Garden", "Сад", "draw"],
  ["home", 2, "Porch", "Веранда", "draw"],
  ["home", 2, "Closet", "Шкаф", "draw"],
  ["home", 3, "Driveway", "Подъездная дорожка", "draw"],
  ["home", 3, "Laundry Room", "Прачечная", "draw"],
  ["home", 3, "Pantry", "Кладовая", "draw"],
  ["home", 3, "Rooftop", "Крыша", "draw"],
  ["home", 3, "Study", "Кабинет", "draw"],
  ["home", 3, "Nursery", "Детская", "draw"],
  ["home", 3, "Cellar", "Погреб", "draw"],
  ["home", 3, "Sunroom", "Зимний сад", "draw"],
  ["home", 3, "Pool", "Бассейн", "draw"],
  ["home", 3, "Shed", "Сарай", "draw"],
  ["home", 3, "Home Office", "Домашний офис", "draw"],
  ["home", 3, "Foyer", "Фойе", "draw"],
  ["public", 1, "Restaurant", "Ресторан", "draw"],
  ["public", 1, "Hospital", "Больница", "draw"],
  ["public", 1, "School", "Школа", "draw"],
  ["public", 1, "Library", "Библиотека", "draw"],
  ["public", 1, "Shopping Mall", "Торговый центр", "draw"],
  ["public", 1, "Supermarket", "Супермаркет", "draw"],
  ["public", 1, "Cinema", "Кинотеатр", "draw"],
  ["public", 2, "Museum", "Музей", "draw"],
  ["public", 2, "Bank", "Банк", "draw"],
  ["public", 2, "Church", "Церковь", "draw"],
  ["public", 2, "Stadium", "Стадион", "draw"],
  ["public", 2, "Gym", "Спортзал", "draw"],
  ["public", 2, "Pharmacy", "Аптека", "draw"],
  ["public", 2, "Post Office", "Почта", "draw"],
  ["public", 2, "Police Station", "Полицейский участок", "draw"],
  ["public", 2, "Theater", "Театр", "draw"],
  ["public", 2, "Zoo", "Зоопарк", "draw"],
  ["public", 2, "Bakery", "Булочная", "draw"],
  ["public", 2, "Cafe", "Кафе", "draw"],
  ["public", 2, "Barbershop", "Парикмахерская", "draw"],
  ["public", 3, "Fire Station", "Пожарная часть", "draw"],
  ["public", 3, "Courthouse", "Суд", "draw"],
  ["public", 3, "Aquarium", "Аквариум", "draw"],
  ["public", 3, "Prison", "Тюрьма", "draw"],
  ["public", 3, "Casino", "Казино", "draw"],
  ["public", 3, "Nightclub", "Ночной клуб", "draw"],
  ["public", 3, "University", "Университет", "draw"],
  ["public", 3, "City Hall", "Мэрия", "draw"],
  ["outdoors", 1, "Beach", "Пляж", "draw"],
  ["outdoors", 1, "Park", "Парк", "draw"],
  ["outdoors", 1, "Forest", "Лес", "draw"],
  ["outdoors", 1, "Mountain", "Гора", "draw"],
  ["outdoors", 1, "Desert", "Пустыня", "draw"],
  ["outdoors", 1, "Lake", "Озеро", "draw"],
  ["outdoors", 2, "Cave", "Пещера", "draw"],
  ["outdoors", 2, "Waterfall", "Водопад", "draw"],
  ["outdoors", 2, "Island", "Остров", "draw"],
  ["outdoors", 2, "Jungle", "Джунгли", "draw"],
  ["outdoors", 2, "Volcano", "Вулкан", "draw"],
  ["outdoors", 2, "River", "Река", "draw"],
  ["outdoors", 2, "Canyon", "Каньон", "draw"],
  ["outdoors", 2, "Farm", "Ферма", "draw"],
  ["outdoors", 2, "Cliff", "Утёс", "draw"],
  ["outdoors", 2, "Field", "Поле", "draw"],
  ["outdoors", 3, "Swamp", "Болото", "draw"],
  ["outdoors", 3, "Glacier", "Ледник", "draw"],
  ["outdoors", 3, "Valley", "Долина", "draw"],
  ["outdoors", 3, "Meadow", "Луг", "draw"],
  ["outdoors", 3, "Campsite", "Лагерь", "draw"],
  ["outdoors", 3, "Tundra", "Тундра", "draw"],
  ["outdoors", 3, "Savanna", "Саванна", "draw"],
  ["outdoors", 3, "Reef", "Риф", "draw"],
  ["travel", 1, "Airport", "Аэропорт", "draw"],
  ["travel", 1, "Train Station", "Вокзал", "draw"],
  ["travel", 1, "Hotel", "Гостиница", "draw"],
  ["travel", 1, "Gas Station", "Заправка", "draw"],
  ["travel", 1, "Bus Stop", "Автобусная остановка", "draw"],
  ["travel", 2, "Harbor", "Гавань", "draw"],
  ["travel", 2, "Subway", "Метро", "draw"],
  ["travel", 2, "Parking Lot", "Парковка", "draw"],
  ["travel", 2, "Port", "Порт", "draw"],
  ["travel", 2, "Highway", "Шоссе", "draw"],
  ["travel", 2, "Motel", "Мотель", "draw"],
  ["travel", 2, "Dock", "Причал", "draw"],
  ["travel", 2, "Border Crossing", "Пограничный пост", "draw"],
  ["travel", 3, "Rest Stop", "Зона отдыха", "draw"],
  ["travel", 3, "Runway", "Взлётно-посадочная полоса", "draw"],
  ["travel", 3, "Customs", "Таможня", "draw"],
  ["travel", 3, "Lighthouse", "Маяк", "draw"],
  ["travel", 3, "Ferry", "Паром", "draw"],
  ["travel", 3, "Toll Booth", "Пункт оплаты", "draw"],
  ["imaginary", 1, "Planet", "Планета", "draw"],
  ["imaginary", 1, "Castle", "Замок", "draw"],
  ["imaginary", 1, "Haunted House", "Дом с привидениями", "draw"],
  ["imaginary", 1, "Space Station", "Космическая станция", "draw"],
  ["imaginary", 1, "Spaceship", "Космический корабль", "draw"],
  ["imaginary", 2, "Moon", "Луна", "draw"],
  ["imaginary", 2, "Dungeon", "Подземелье", "draw"],
  ["imaginary", 2, "Atlantis", "Атлантида", "draw"],
  ["imaginary", 2, "Heaven", "Рай", "draw"],
  ["imaginary", 2, "Treasure Island", "Остров сокровищ", "draw"],
  ["imaginary", 2, "Fortress", "Крепость", "draw"],
  ["imaginary", 2, "Pyramid", "Пирамида", "draw"],
  ["imaginary", 2, "Igloo", "Иглу", "draw"],
  ["imaginary", 2, "Windmill", "Ветряная мельница", "draw"],
  ["imaginary", 3, "Underworld", "Подземный мир", "draw"],
  ["imaginary", 3, "Wonderland", "Страна чудес", "draw"],
  ["imaginary", 3, "Dragon's Lair", "Логово дракона", "draw"],
  ["imaginary", 3, "Time Machine", "Машина времени", "draw"],
  ["imaginary", 3, "Black Hole", "Чёрная дыра", "draw"],
  ["imaginary", 3, "Lost City", "Затерянный город", "draw"],
  ["imaginary", 3, "Enchanted Forest", "Зачарованный лес", "draw"],
  ["imaginary", 3, "Pirate Ship", "Пиратский корабль", "draw"],
]);
