/* Science */
addWords("science", [
  ["space", 1, "Sun", "Солнце", "draw"],
  ["space", 1, "Moon", "Луна", "draw"],
  ["space", 1, "Star", "Звезда", "draw"],
  ["space", 1, "Mars", "Марс", "draw"],
  ["space", 1, "Saturn", "Сатурн", "draw"],
  ["space", 1, "Jupiter", "Юпитер", "draw"],
  ["space", 1, "Comet", "Комета", "draw"],
  ["space", 1, "Astronaut", "Астронавт", "draw"],
  ["space", 1, "Rocket", "Ракета", "draw"],
  ["space", 2, "Telescope", "Телескоп", "draw"],
  ["space", 2, "Galaxy", "Галактика", "draw"],
  ["space", 2, "Asteroid", "Астероид", "draw"],
  ["space", 2, "Meteor", "Метеор", "draw"],
  ["space", 2, "Satellite", "Спутник", "draw"],
  ["space", 2, "Solar System", "Солнечная система"],
  ["space", 2, "Milky Way", "Млечный путь"],
  ["space", 2, "Venus", "Венера", "draw"],
  ["space", 2, "Pluto", "Плутон", "draw"],
  ["space", 3, "Black Hole", "Чёрная дыра"],
  ["space", 3, "Nebula", "Туманность", "draw"],
  ["space", 3, "Supernova", "Сверхновая"],
  ["space", 3, "Big Bang", "Большой взрыв"],

  ["body", 1, "Heart", "Сердце", "draw"],
  ["body", 1, "Brain", "Мозг", "draw"],
  ["body", 1, "Eye", "Глаз", "draw"],
  ["body", 1, "Ear", "Ухо", "draw"],
  ["body", 1, "Teeth", "Зубы", "draw"],
  ["body", 1, "Skin", "Кожа", "draw"],
  ["body", 1, "Bones", "Кости", "draw"],
  ["body", 1, "Blood", "Кровь"],
  ["body", 2, "Lungs", "Лёгкие", "draw"],
  ["body", 2, "Stomach", "Желудок", "draw"],
  ["body", 2, "Liver", "Печень", "draw"],
  ["body", 2, "Kidney", "Почка", "draw"],
  ["body", 2, "Spine", "Позвоночник", "draw"],
  ["body", 2, "Muscle", "Мышца", "draw"],
  ["body", 2, "Ribs", "Рёбра", "draw"],
  ["body", 2, "Veins", "Вены", "draw"],
  ["body", 2, "Skeleton", "Скелет", "draw"],
  ["body", 3, "DNA", "ДНК"],
  ["body", 3, "Nerves", "Нервы"],
  ["body", 3, "Neuron", "Нейрон", "draw"],

  ["inventions", 1, "Wheel", "Колесо", "draw"],
  ["inventions", 1, "Telephone", "Телефон", "draw"],
  ["inventions", 1, "Light Bulb", "Лампочка", "draw"],
  ["inventions", 1, "Airplane", "Самолёт", "draw"],
  ["inventions", 1, "Computer", "Компьютер", "draw"],
  ["inventions", 1, "Television", "Телевизор", "draw"],
  ["inventions", 1, "Automobile", "Автомобиль", "draw"],
  ["inventions", 1, "Radio", "Радио", "draw"],
  ["inventions", 2, "Telescope", "Телескоп", "draw"],
  ["inventions", 2, "Microscope", "Микроскоп", "draw"],
  ["inventions", 2, "Steam Engine", "Паровой двигатель", "draw"],
  ["inventions", 2, "Compass", "Компас", "draw"],
  ["inventions", 2, "Printing Press", "Печатный станок", "draw"],
  ["inventions", 2, "Camera", "Фотоаппарат", "draw"],
  ["inventions", 2, "Battery", "Батарея", "draw"],
  ["inventions", 3, "Internet", "Интернет"],
  ["inventions", 3, "Penicillin", "Пенициллин"],
  ["inventions", 3, "Microchip", "Микрочип", "draw"],

  ["elements", 1, "Gold", "Золото", "draw"],
  ["elements", 1, "Iron", "Железо", "draw"],
  ["elements", 1, "Water", "Вода", "draw"],
  ["elements", 1, "Salt", "Соль", "draw"],
  ["elements", 1, "Carbon", "Углерод"],
  ["elements", 1, "Magnet", "Магнит", "draw"],
  ["elements", 2, "Oxygen", "Кислород"],
  ["elements", 2, "Hydrogen", "Водород"],
  ["elements", 2, "Helium", "Гелий"],
  ["elements", 2, "Nitrogen", "Азот"],
  ["elements", 2, "Copper", "Медь", "draw"],
  ["elements", 2, "Silver", "Серебро", "draw"],
  ["elements", 2, "Sodium", "Натрий"],
  ["elements", 2, "Diamond", "Алмаз", "draw"],
  ["elements", 3, "Mercury", "Ртуть", "draw"],
  ["elements", 3, "Uranium", "Уран"],
  ["elements", 3, "Neon", "Неон"],
  ["elements", 3, "Calcium", "Кальций"],

  ["tech", 1, "Robot", "Робот", "draw"],
  ["tech", 1, "Drone", "Дрон", "draw"],
  ["tech", 1, "Laser", "Лазер", "draw"],
  ["tech", 1, "Screen", "Экран", "draw"],
  ["tech", 1, "Camera", "Камера", "draw"],
  ["tech", 2, "Satellite", "Спутник", "draw"],
  ["tech", 2, "Battery", "Батарея", "draw"],
  ["tech", 2, "Solar Panel", "Солнечная панель", "draw"],
  ["tech", 2, "Electricity", "Электричество"],
  ["tech", 2, "GPS", "GPS"],
  ["tech", 2, "Microchip", "Микрочип", "draw"],
  ["tech", 2, "3D Printer", "3D-принтер", "draw"],
  ["tech", 2, "Submarine", "Подводная лодка", "draw"],
  ["tech", 3, "AI", "ИИ"],
  ["tech", 3, "Microscope", "Микроскоп", "draw"],
  ["tech", 3, "Nuclear Reactor", "Ядерный реактор", "draw"],
  ["tech", 3, "Quantum Computer", "Квантовый компьютер"],
]);
