/* Superheroes — Avengers/Marvel heroes */
addWords("superheroes", [
  ["avengers", 1, "Iron Man", "Железный человек", "draw"],
  ["avengers", 1, "Captain America", "Капитан Америка", "draw"],
  ["avengers", 1, "Thor", "Тор", "draw"],
  ["avengers", 1, "Hulk", "Халк", "draw"],
  ["avengers", 1, "Black Widow", "Чёрная Вдова", "draw"],
  ["avengers", 1, "Hawkeye", "Соколиный Глаз", "draw"],
  ["avengers", 1, "Spider-Man", "Человек-Паук", "draw"],
  ["avengers", 1, "Black Panther", "Чёрная Пантера", "draw"],
  ["avengers", 1, "Doctor Strange", "Доктор Стрэндж", "draw"],
  ["avengers", 1, "Captain Marvel", "Капитан Марвел", "draw"],
  ["avengers", 1, "Ant-Man", "Человек-Муравей", "draw"],
  ["avengers", 1, "Star-Lord", "Звёздный Лорд", "draw"],
  ["avengers", 1, "Groot", "Грут", "draw"],
  ["avengers", 1, "Rocket", "Ракета", "draw"],
  ["avengers", 1, "Scarlet Witch", "Алая Ведьма", "draw"],
  ["avengers", 1, "Vision", "Вижн", "draw"],
  ["avengers", 1, "War Machine", "Боевая Машина", "draw"],
  ["avengers", 2, "Falcon", "Сокол", "draw"],
  ["avengers", 2, "Winter Soldier", "Зимний Солдат", "draw"],
  ["avengers", 2, "Wasp", "Оса", "draw"],
  ["avengers", 2, "Gamora", "Гамора", "draw"],
  ["avengers", 2, "Drax", "Дракс", "draw"],
  ["avengers", 2, "Nebula", "Небула", "draw"],
  ["avengers", 2, "Mantis", "Мантис", "draw"],
  ["avengers", 2, "Nick Fury", "Ник Фьюри", "draw"],
  ["avengers", 2, "Quicksilver", "Ртуть", "draw"],
  ["avengers", 2, "Mr. Fantastic", "Мистер Фантастик", "draw"],
  ["avengers", 2, "Invisible Woman", "Женщина-Невидимка", "draw"],
  ["avengers", 2, "Human Torch", "Человек-Факел", "draw"],
  ["avengers", 2, "The Thing", "Существо", "draw"],
  ["avengers", 2, "Daredevil", "Сорвиголова", "draw"],
  ["avengers", 2, "Luke Cage", "Люк Кейдж", "draw"],
  ["avengers", 2, "She-Hulk", "Женщина-Халк", "draw"],
  ["avengers", 2, "Moon Knight", "Лунный Рыцарь", "draw"],
  ["avengers", 2, "Ms. Marvel", "Мисс Марвел", "draw"],
  ["avengers", 2, "Hercules", "Геркулес", "draw"],
  ["avengers", 2, "Iron Fist", "Железный Кулак", "draw"],
  ["avengers", 2, "Jessica Jones", "Джессика Джонс"],
  ["avengers", 2, "Shang-Chi", "Шан-Чи", "draw"],
  ["avengers", 3, "Wonder Man", "Чудо-человек"],
  ["avengers", 3, "Sentry", "Часовой", "draw"],
  ["avengers", 3, "Quasar", "Квазар"],
  ["avengers", 3, "Moondragon", "Лунный Дракон", "draw"],
  ["avengers", 3, "Tigra", "Тигра", "draw"],
  ["avengers", 3, "Mockingbird", "Пересмешница"],
  ["avengers", 3, "Nova", "Нова", "draw"],
  ["avengers", 3, "Adam Warlock", "Адам Варлок", "draw"],
  ["avengers", 3, "Squirrel Girl", "Девушка-Белка", "draw"],
  ["avengers", 3, "Photon", "Фотон"],
  ["avengers", 3, "Stature", "Статура"],
]);
