/* Superheroes — DC Heroes */
addWords("superheroes", [
  ["dcheroes", 1, "Batman", "Бэтмен", "draw"],
  ["dcheroes", 1, "Superman", "Супермен", "draw"],
  ["dcheroes", 1, "Wonder Woman", "Чудо-женщина", "draw"],
  ["dcheroes", 1, "The Flash", "Флэш", "draw"],
  ["dcheroes", 1, "Aquaman", "Аквамен", "draw"],
  ["dcheroes", 1, "Green Lantern", "Зелёный фонарь", "draw"],
  ["dcheroes", 1, "Cyborg", "Киборг", "draw"],
  ["dcheroes", 1, "Shazam", "Шазам", "draw"],
  ["dcheroes", 1, "Supergirl", "Супергёрл", "draw"],
  ["dcheroes", 1, "Nightwing", "Найтвинг", "draw"],
  ["dcheroes", 2, "Green Arrow", "Зелёная стрела", "draw"],
  ["dcheroes", 2, "Batgirl", "Бэтгёрл", "draw"],
  ["dcheroes", 2, "Robin", "Робин", "draw"],
  ["dcheroes", 2, "Martian Manhunter", "Марсианский охотник", "draw"],
  ["dcheroes", 2, "Black Canary", "Чёрная канарейка", "draw"],
  ["dcheroes", 2, "Hawkman", "Ястребиный человек", "draw"],
  ["dcheroes", 2, "Hawkgirl", "Девушка-ястреб", "draw"],
  ["dcheroes", 2, "Zatanna", "Затанна", "draw"],
  ["dcheroes", 2, "Raven", "Рейвен", "draw"],
  ["dcheroes", 2, "Starfire", "Огонёк", "draw"],
  ["dcheroes", 2, "Beast Boy", "Зверомальчик", "draw"],
  ["dcheroes", 2, "Red Hood", "Красный колпак", "draw"],
  ["dcheroes", 2, "Blue Beetle", "Синий жук", "draw"],
  ["dcheroes", 2, "Booster Gold", "Бустер Голд", "draw"],
  ["dcheroes", 2, "John Constantine", "Джон Константин"],
  ["dcheroes", 2, "Swamp Thing", "Болотная тварь", "draw"],
  ["dcheroes", 2, "Static", "Статик", "draw"],
  ["dcheroes", 2, "Kid Flash", "Малыш Флэш", "draw"],
  ["dcheroes", 2, "Wonder Girl", "Девушка-чудо", "draw"],
  ["dcheroes", 2, "Green Lantern (John Stewart)", "Зелёный фонарь (Джон Стюарт)"],
  ["dcheroes", 2, "Doctor Fate", "Доктор Рок", "draw"],
  ["dcheroes", 3, "Plastic Man", "Пластиковый человек", "draw"],
  ["dcheroes", 3, "Firestorm", "Огненный шторм", "draw"],
  ["dcheroes", 3, "Vixen", "Лиса", "draw"],
  ["dcheroes", 3, "Hal Jordan", "Хэл Джордан"],
  ["dcheroes", 3, "Dick Grayson", "Дик Грейсон"],
  ["dcheroes", 3, "Damian Wayne", "Дэмиан Уэйн"],
  ["dcheroes", 3, "Atom", "Атом", "draw"],
  ["dcheroes", 3, "Elongated Man", "Вытянутый человек", "draw"],
  ["dcheroes", 3, "Mister Miracle", "Мистер Чудо", "draw"],
  ["dcheroes", 3, "Big Barda", "Большая Барда", "draw"],
  ["dcheroes", 3, "Power Girl", "Девушка силы", "draw"],
  ["dcheroes", 3, "Donna Troy", "Донна Трой", "draw"],
  ["dcheroes", 3, "Steel", "Сталь", "draw"],
  ["dcheroes", 3, "Ragman", "Рваный", "draw"],
  ["dcheroes", 3, "Deadman", "Мертвец"],
  ["dcheroes", 3, "Phantom Stranger", "Незнакомец-призрак"],
]);
