/* Superheroes — DC Villains */
addWords("superheroes", [
  ["dcvillains", 1, "Joker", "Джокер", "draw"],
  ["dcvillains", 1, "Harley Quinn", "Харли Квинн", "draw"],
  ["dcvillains", 1, "Lex Luthor", "Лекс Лютор", "draw"],
  ["dcvillains", 1, "Bane", "Бэйн", "draw"],
  ["dcvillains", 1, "Penguin", "Пингвин", "draw"],
  ["dcvillains", 1, "Riddler", "Загадочник", "draw"],
  ["dcvillains", 1, "Two-Face", "Двуликий", "draw"],
  ["dcvillains", 1, "Scarecrow", "Пугало", "draw"],
  ["dcvillains", 1, "Catwoman", "Женщина-кошка", "draw"],
  ["dcvillains", 1, "Poison Ivy", "Ядовитый Плющ", "draw"],
  ["dcvillains", 1, "Mr. Freeze", "Мистер Фриз", "draw"],
  ["dcvillains", 1, "Darkseid", "Дарксайд", "draw"],
  ["dcvillains", 1, "General Zod", "Генерал Зод"],
  ["dcvillains", 2, "Deathstroke", "Дефстроук", "draw"],
  ["dcvillains", 2, "Reverse-Flash", "Обратный Флэш", "draw"],
  ["dcvillains", 2, "Sinestro", "Синестро", "draw"],
  ["dcvillains", 2, "Black Adam", "Чёрный Адам", "draw"],
  ["dcvillains", 2, "Brainiac", "Брейниак", "draw"],
  ["dcvillains", 2, "Ra's al Ghul", "Ра'с аль Гул"],
  ["dcvillains", 2, "Killer Croc", "Крокодил-убийца", "draw"],
  ["dcvillains", 2, "Clayface", "Глинолик", "draw"],
  ["dcvillains", 2, "Black Manta", "Чёрная Манта", "draw"],
  ["dcvillains", 2, "Cheetah", "Гепард", "draw"],
  ["dcvillains", 2, "Captain Cold", "Капитан Холод", "draw"],
  ["dcvillains", 2, "Gorilla Grodd", "Горилла Гродд", "draw"],
  ["dcvillains", 2, "Doomsday", "Судный День", "draw"],
  ["dcvillains", 2, "Ocean Master", "Властелин Океана"],
  ["dcvillains", 2, "Killer Frost", "Убийца Мороз", "draw"],
  ["dcvillains", 2, "Mad Hatter", "Безумный Шляпник", "draw"],
  ["dcvillains", 2, "Solomon Grundy", "Соломон Гранди", "draw"],
  ["dcvillains", 2, "Deadshot", "Дэдшот", "draw"],
  ["dcvillains", 2, "Amanda Waller", "Аманда Уоллер"],
  ["dcvillains", 2, "Bizarro", "Бизарро", "draw"],
  ["dcvillains", 3, "Metallo", "Металло", "draw"],
  ["dcvillains", 3, "Vandal Savage", "Вандал Сэвэдж"],
  ["dcvillains", 3, "Mister Mxyzptlk", "Мистер Мксизптлк"],
  ["dcvillains", 3, "Toyman", "Игрушечник", "draw"],
  ["dcvillains", 3, "Parasite", "Паразит", "draw"],
  ["dcvillains", 3, "Trigon", "Тригон", "draw"],
  ["dcvillains", 3, "Anti-Monitor", "Анти-Монитор"],
  ["dcvillains", 3, "Black Hand", "Чёрная Рука"],
  ["dcvillains", 3, "Mirror Master", "Мастер Зеркал", "draw"],
  ["dcvillains", 3, "Heat Wave", "Огненная Волна", "draw"],
  ["dcvillains", 3, "Weather Wizard", "Погодный Волшебник", "draw"],
]);
