/* Superheroes — Marvel Villains */
addWords("superheroes", [
  ["marvelvillains", 1, "Thanos", "Танос", "draw"],
  ["marvelvillains", 1, "Loki", "Локи", "draw"],
  ["marvelvillains", 1, "Ultron", "Альтрон", "draw"],
  ["marvelvillains", 1, "Red Skull", "Красный Череп", "draw"],
  ["marvelvillains", 1, "Doctor Doom", "Доктор Дум", "draw"],
  ["marvelvillains", 1, "Galactus", "Галактус", "draw"],
  ["marvelvillains", 1, "Hela", "Хела", "draw"],
  ["marvelvillains", 1, "Dormammu", "Дормамму", "draw"],
  ["marvelvillains", 1, "Magneto", "Магнето", "draw"],
  ["marvelvillains", 1, "Kingpin", "Кингпин", "draw"],
  ["marvelvillains", 2, "Kang the Conqueror", "Кэнг Завоеватель", "draw"],
  ["marvelvillains", 2, "Mandarin", "Мандарин", "draw"],
  ["marvelvillains", 2, "Abomination", "Мерзость", "draw"],
  ["marvelvillains", 2, "Ronan the Accuser", "Ронан Обвинитель", "draw"],
  ["marvelvillains", 2, "Killmonger", "Киллмонгер", "draw"],
  ["marvelvillains", 2, "Baron Zemo", "Барон Земо", "draw"],
  ["marvelvillains", 2, "Taskmaster", "Таскмастер", "draw"],
  ["marvelvillains", 2, "Bullseye", "Яблочко", "draw"],
  ["marvelvillains", 2, "Ego", "Эго", "draw"],
  ["marvelvillains", 2, "Surtur", "Суртур", "draw"],
  ["marvelvillains", 2, "MODOK", "МОДОК", "draw"],
  ["marvelvillains", 2, "Mephisto", "Мефисто", "draw"],
  ["marvelvillains", 2, "Crossbones", "Скрещенные кости"],
  ["marvelvillains", 2, "Whiplash", "Хлыст", "draw"],
  ["marvelvillains", 2, "Malekith", "Малекит", "draw"],
  ["marvelvillains", 2, "Gorr the God Butcher", "Горр Убийца Богов", "draw"],
  ["marvelvillains", 2, "The Leader", "Лидер", "draw"],
  ["marvelvillains", 2, "Yellowjacket", "Жёлтая Куртка", "draw"],
  ["marvelvillains", 2, "Ghost", "Призрак", "draw"],
  ["marvelvillains", 3, "Annihilus", "Аннигилус", "draw"],
  ["marvelvillains", 3, "Magus", "Магус"],
  ["marvelvillains", 3, "Onslaught", "Натиск", "draw"],
  ["marvelvillains", 3, "Red Hulk", "Красный Халк", "draw"],
  ["marvelvillains", 3, "Enchantress", "Чаровница", "draw"],
  ["marvelvillains", 3, "Absorbing Man", "Поглотитель", "draw"],
  ["marvelvillains", 3, "Attuma", "Аттума"],
  ["marvelvillains", 3, "Blizzard", "Буран", "draw"],
  ["marvelvillains", 3, "Crimson Dynamo", "Багряный Динамо", "draw"],
  ["marvelvillains", 3, "Korvac", "Корвак"],
  ["marvelvillains", 3, "Molecule Man", "Человек-Молекула"],
  ["marvelvillains", 3, "The Beyonder", "Потусторонний"],
  ["marvelvillains", 3, "Typhoid Mary", "Тифозная Мэри"],
]);
