/* Superheroes — Spider-verse */
addWords("superheroes", [
  ["spiderverse", 1, "Spider-Man", "Человек-паук", "draw"],
  ["spiderverse", 1, "Venom", "Веном", "draw"],
  ["spiderverse", 1, "Green Goblin", "Зелёный гоблин", "draw"],
  ["spiderverse", 1, "Doctor Octopus", "Доктор Осьминог", "draw"],
  ["spiderverse", 1, "Carnage", "Карнаж", "draw"],
  ["spiderverse", 1, "Mary Jane", "Мэри Джейн"],
  ["spiderverse", 1, "Aunt May", "Тётя Мэй"],
  ["spiderverse", 1, "Mysterio", "Мистерио", "draw"],
  ["spiderverse", 1, "Electro", "Электро", "draw"],
  ["spiderverse", 1, "Vulture", "Стервятник", "draw"],
  ["spiderverse", 1, "Sandman", "Песчаный человек", "draw"],
  ["spiderverse", 1, "Rhino", "Носорог", "draw"],
  ["spiderverse", 2, "Miles Morales", "Майлз Моралес", "draw"],
  ["spiderverse", 2, "Spider-Gwen", "Паук-Гвен", "draw"],
  ["spiderverse", 2, "Gwen Stacy", "Гвен Стэйси"],
  ["spiderverse", 2, "J. Jonah Jameson", "Дж. Джона Джеймсон"],
  ["spiderverse", 2, "Harry Osborn", "Гарри Осборн"],
  ["spiderverse", 2, "Kingpin", "Король преступного мира", "draw"],
  ["spiderverse", 2, "Kraven the Hunter", "Крейвен Охотник", "draw"],
  ["spiderverse", 2, "Lizard", "Ящер", "draw"],
  ["spiderverse", 2, "Shocker", "Шокер", "draw"],
  ["spiderverse", 2, "Hobgoblin", "Гоблин-призрак", "draw"],
  ["spiderverse", 2, "Black Cat", "Чёрная кошка", "draw"],
  ["spiderverse", 2, "Scorpion", "Скорпион", "draw"],
  ["spiderverse", 2, "Morbius", "Морбиус", "draw"],
  ["spiderverse", 2, "Prowler", "Бродяга", "draw"],
  ["spiderverse", 2, "Spider-Woman", "Женщина-паук", "draw"],
  ["spiderverse", 2, "Ben Reilly", "Бен Рейли", "draw"],
  ["spiderverse", 3, "Miguel O'Hara", "Мигель О'Хара", "draw"],
  ["spiderverse", 3, "Norman Osborn", "Норман Осборн"],
  ["spiderverse", 3, "Silk", "Шёлк", "draw"],
  ["spiderverse", 3, "Peni Parker", "Пэни Паркер", "draw"],
  ["spiderverse", 3, "Tombstone", "Надгробие", "draw"],
  ["spiderverse", 3, "Hammerhead", "Молоток", "draw"],
  ["spiderverse", 3, "Chameleon", "Хамелеон", "draw"],
  ["spiderverse", 3, "Silver Sable", "Серебряная соболь", "draw"],
  ["spiderverse", 3, "Spot", "Пятно", "draw"],
]);
