/* Superheroes — X-Men */
addWords("superheroes", [
  ["xmen", 1, "Wolverine", "Росомаха", "draw"],
  ["xmen", 1, "Professor X", "Профессор Икс", "draw"],
  ["xmen", 1, "Storm", "Шторм", "draw"],
  ["xmen", 1, "Cyclops", "Циклоп", "draw"],
  ["xmen", 1, "Jean Grey", "Джин Грей", "draw"],
  ["xmen", 1, "Beast", "Зверь", "draw"],
  ["xmen", 1, "Rogue", "Шельма", "draw"],
  ["xmen", 1, "Nightcrawler", "Ночной Змей", "draw"],
  ["xmen", 1, "Mystique", "Мистик", "draw"],
  ["xmen", 1, "Magneto", "Магнето", "draw"],
  ["xmen", 1, "Deadpool", "Дэдпул", "draw"],
  ["xmen", 1, "Iceman", "Человек-Лёд", "draw"],
  ["xmen", 1, "Colossus", "Колосс", "draw"],
  ["xmen", 2, "Gambit", "Гамбит", "draw"],
  ["xmen", 2, "Jubilee", "Джубили", "draw"],
  ["xmen", 2, "Psylocke", "Псайлок", "draw"],
  ["xmen", 2, "Angel", "Ангел", "draw"],
  ["xmen", 2, "Emma Frost", "Эмма Фрост", "draw"],
  ["xmen", 2, "Cable", "Кейбл", "draw"],
  ["xmen", 2, "Bishop", "Бишоп"],
  ["xmen", 2, "Havok", "Хавок"],
  ["xmen", 2, "Polaris", "Полярис"],
  ["xmen", 2, "Kitty Pryde", "Китти Прайд", "draw"],
  ["xmen", 2, "Sabretooth", "Саблезуб", "draw"],
  ["xmen", 2, "Apocalypse", "Апокалипсис", "draw"],
  ["xmen", 2, "Juggernaut", "Джаггернаут", "draw"],
  ["xmen", 2, "Quicksilver", "Ртуть", "draw"],
  ["xmen", 2, "Domino", "Домино"],
  ["xmen", 2, "Pyro", "Пиро", "draw"],
  ["xmen", 2, "Toad", "Жаба", "draw"],
  ["xmen", 3, "Banshee", "Банши"],
  ["xmen", 3, "Forge", "Кузнец"],
  ["xmen", 3, "Warpath", "Боевой Путь"],
  ["xmen", 3, "Sunfire", "Солнечный Огонь"],
  ["xmen", 3, "Morph", "Морф"],
  ["xmen", 3, "Marrow", "Костный Мозг"],
  ["xmen", 3, "Mimic", "Мимик"],
  ["xmen", 3, "Dazzler", "Ослепительная"],
  ["xmen", 3, "Longshot", "Длинный Выстрел"],
  ["xmen", 3, "Multiple Man", "Мультиплекс"],
  ["xmen", 3, "Siryn", "Сирена"],
  ["xmen", 3, "Shatterstar", "Шаттерстар"],
  ["xmen", 3, "Rictor", "Риктор"],
]);
