/* NBA — Central */
addWords("nba", [
  // Chicago Bulls
  ["bulls", 1, "Michael Jordan", "Майкл Джордан"],
  ["bulls", 1, "Scottie Pippen", "Скотти Пиппен"],
  ["bulls", 2, "Dennis Rodman", "Деннис Родман"],
  ["bulls", 2, "Derrick Rose", "Деррик Роуз"],
  ["bulls", 2, "DeMar DeRozan", "Демар Дерозан"],
  ["bulls", 2, "Zach LaVine", "Зак Лавин"],
  ["bulls", 3, "Horace Grant", "Хорас Грант"],
  ["bulls", 3, "Toni Kukoc", "Тони Кукоч"],
  ["bulls", 3, "Joakim Noah", "Йоаким Ноа"],
  ["bulls", 3, "Jimmy Butler", "Джимми Батлер"],
  ["bulls", 3, "Bob Love", "Боб Лав"],
  ["bulls", 3, "Artis Gilmore", "Артис Гилмор"],

  // Cleveland Cavaliers
  ["cavs", 1, "LeBron James", "Леброн Джеймс"],
  ["cavs", 1, "Kyrie Irving", "Кайри Ирвинг"],
  ["cavs", 2, "Donovan Mitchell", "Донован Митчелл"],
  ["cavs", 2, "Kevin Love", "Кевин Лав"],
  ["cavs", 2, "Darius Garland", "Дариус Гарлэнд"],
  ["cavs", 3, "Mark Price", "Марк Прайс"],
  ["cavs", 3, "Brad Daugherty", "Брэд Доэрти"],
  ["cavs", 3, "Zydrunas Ilgauskas", "Жидрунас Илгаускас"],
  ["cavs", 3, "Larry Nance", "Ларри Нэнс"],
  ["cavs", 3, "Evan Mobley", "Эван Мобли"],
  ["cavs", 3, "Jarrett Allen", "Джарретт Аллен"],

  // Detroit Pistons
  ["pistons", 1, "Isiah Thomas", "Айзея Томас"],
  ["pistons", 1, "Ben Wallace", "Бен Уоллес"],
  ["pistons", 2, "Chauncey Billups", "Чонси Биллапс"],
  ["pistons", 2, "Joe Dumars", "Джо Дюмарс"],
  ["pistons", 2, "Cade Cunningham", "Кейд Каннингем"],
  ["pistons", 3, "Bill Laimbeer", "Билл Леймбир"],
  ["pistons", 3, "Dennis Rodman", "Деннис Родман"],
  ["pistons", 3, "Rasheed Wallace", "Рашид Уоллес"],
  ["pistons", 3, "Richard Hamilton", "Ричард Хэмилтон"],
  ["pistons", 3, "Grant Hill", "Грант Хилл"],
  ["pistons", 3, "Andre Drummond", "Андре Драммонд"],

  // Indiana Pacers
  ["pacers", 1, "Reggie Miller", "Реджи Миллер"],
  ["pacers", 1, "Tyrese Haliburton", "Тайриз Халибертон"],
  ["pacers", 2, "Paul George", "Пол Джордж"],
  ["pacers", 2, "Victor Oladipo", "Виктор Оладипо"],
  ["pacers", 3, "Jermaine O'Neal", "Джермейн О'Нил"],
  ["pacers", 3, "Rik Smits", "Рик Смитс"],
  ["pacers", 3, "Mark Jackson", "Марк Джексон"],
  ["pacers", 3, "Danny Granger", "Дэнни Грэнджер"],
  ["pacers", 3, "Metta World Peace", "Метта Уорлд Пис"],
  ["pacers", 3, "Myles Turner", "Майлс Тёрнер"],
  ["pacers", 3, "Pascal Siakam", "Паскаль Сиакам"],

  // Milwaukee Bucks
  ["bucks", 1, "Giannis Antetokounmpo", "Яннис Адетокумбо"],
  ["bucks", 1, "Kareem Abdul-Jabbar", "Карим Абдул-Джаббар"],
  ["bucks", 2, "Ray Allen", "Рэй Аллен"],
  ["bucks", 2, "Damian Lillard", "Дэмиан Лиллард"],
  ["bucks", 2, "Khris Middleton", "Крис Миддлтон"],
  ["bucks", 3, "Oscar Robertson", "Оскар Робертсон"],
  ["bucks", 3, "Sidney Moncrief", "Сидни Монкриф"],
  ["bucks", 3, "Glenn Robinson", "Гленн Робинсон"],
  ["bucks", 3, "Sam Cassell", "Сэм Кэсселл"],
  ["bucks", 3, "Michael Redd", "Майкл Редд"],
  ["bucks", 3, "Brook Lopez", "Брук Лопес"],
  ["bucks", 3, "Jrue Holiday", "Джру Холидэй"],
]);
