/* NBA — Northwest */
addWords("nba", [
  // Denver Nuggets
  ["nuggets", 1, "Nikola Jokić", "Никола Йокич"],
  ["nuggets", 2, "Jamal Murray", "Джамал Мюррэй"],
  ["nuggets", 2, "Carmelo Anthony", "Кармело Энтони"],
  ["nuggets", 2, "Alex English", "Алекс Инглиш"],
  ["nuggets", 2, "Dikembe Mutombo", "Дикембе Мутомбо"],
  ["nuggets", 2, "Aaron Gordon", "Аарон Гордон"],
  ["nuggets", 3, "Allen Iverson", "Аллен Айверсон"],
  ["nuggets", 3, "Chauncey Billups", "Чонси Биллапс"],
  ["nuggets", 3, "Marcus Camby", "Маркус Кэмби"],
  ["nuggets", 3, "Michael Porter Jr.", "Майкл Портер мл."],
  ["nuggets", 3, "Fat Lever", "Фэт Левер"],
  ["nuggets", 3, "Dan Issel", "Дэн Иссел"],

  // Minnesota Timberwolves
  ["wolves", 1, "Anthony Edwards", "Энтони Эдвардс"],
  ["wolves", 1, "Kevin Garnett", "Кевин Гарнетт"],
  ["wolves", 2, "Karl-Anthony Towns", "Карл-Энтони Таунс"],
  ["wolves", 2, "Rudy Gobert", "Руди Гобер"],
  ["wolves", 2, "Kevin Love", "Кевин Лав"],
  ["wolves", 2, "Jimmy Butler", "Джимми Батлер"],
  ["wolves", 3, "Stephon Marbury", "Стефон Марбери"],
  ["wolves", 3, "Sam Cassell", "Сэм Касселл"],
  ["wolves", 3, "Wally Szczerbiak", "Уолли Щербяк"],
  ["wolves", 3, "Andrew Wiggins", "Эндрю Уиггинс"],
  ["wolves", 3, "Ricky Rubio", "Рики Рубио"],
  ["wolves", 3, "Mike Conley", "Майк Конли"],

  // Oklahoma City Thunder
  ["thunder", 1, "Shai Gilgeous-Alexander", "Шей Гилджес-Александер"],
  ["thunder", 1, "Kevin Durant", "Кевин Дюрант"],
  ["thunder", 2, "Russell Westbrook", "Расселл Уэстбрук"],
  ["thunder", 2, "James Harden", "Джеймс Харден"],
  ["thunder", 2, "Chet Holmgren", "Чет Холмгрен"],
  ["thunder", 2, "Jalen Williams", "Джейлен Уильямс"],
  ["thunder", 3, "Paul George", "Пол Джордж"],
  ["thunder", 3, "Serge Ibaka", "Серж Ибака"],
  ["thunder", 3, "Steven Adams", "Стивен Адамс"],
  ["thunder", 3, "Victor Oladipo", "Виктор Оладипо"],
  ["thunder", 3, "Dennis Schröder", "Деннис Шрёдер"],

  // Portland Trail Blazers
  ["blazers", 1, "Damian Lillard", "Дэмиан Лиллард"],
  ["blazers", 1, "Clyde Drexler", "Клайд Дрекслер"],
  ["blazers", 2, "Bill Walton", "Билл Уолтон"],
  ["blazers", 2, "CJ McCollum", "Си Джей Маккаллум"],
  ["blazers", 2, "Brandon Roy", "Брэндон Рой"],
  ["blazers", 2, "Rasheed Wallace", "Рашид Уоллес"],
  ["blazers", 3, "Terry Porter", "Терри Портер"],
  ["blazers", 3, "Clifford Robinson", "Клиффорд Робинсон"],
  ["blazers", 3, "LaMarcus Aldridge", "Ламаркус Олдридж"],
  ["blazers", 3, "Maurice Lucas", "Морис Лукас"],
  ["blazers", 3, "Arvydas Sabonis", "Арвидас Сабонис"],

  // Utah Jazz
  ["jazz", 1, "Karl Malone", "Карл Мэлоун"],
  ["jazz", 1, "John Stockton", "Джон Стоктон"],
  ["jazz", 2, "Donovan Mitchell", "Донован Митчелл"],
  ["jazz", 2, "Deron Williams", "Дерон Уильямс"],
  ["jazz", 2, "Rudy Gobert", "Руди Гобер"],
  ["jazz", 2, "Pete Maravich", "Пит Маравич"],
  ["jazz", 3, "Andrei Kirilenko", "Андрей Кириленко"],
  ["jazz", 3, "Carlos Boozer", "Карлос Бузер"],
  ["jazz", 3, "Mark Eaton", "Марк Итон"],
  ["jazz", 3, "Adrian Dantley", "Эдриан Дэнтли"],
  ["jazz", 3, "Jeff Hornacek", "Джефф Хорнасек"],
  ["jazz", 3, "Lauri Markkanen", "Лаури Маркканен"],
]);
