/* NBA — Pacific */
addWords("nba", [
  // Golden State Warriors
  ["warriors", 1, "Stephen Curry", "Стефен Карри"],
  ["warriors", 1, "Klay Thompson", "Клэй Томпсон"],
  ["warriors", 1, "Draymond Green", "Дрэймонд Грин"],
  ["warriors", 1, "Kevin Durant", "Кевин Дюрант"],
  ["warriors", 2, "Wilt Chamberlain", "Уилт Чемберлен"],
  ["warriors", 2, "Andre Iguodala", "Андре Игудала"],
  ["warriors", 2, "Rick Barry", "Рик Барри"],
  ["warriors", 2, "Chris Mullin", "Крис Маллин"],
  ["warriors", 3, "Tim Hardaway", "Тим Хардуэй"],
  ["warriors", 3, "Baron Davis", "Бэрон Дэвис"],
  ["warriors", 3, "Latrell Sprewell", "Латрелл Спрюэлл"],
  ["warriors", 3, "Nate Thurmond", "Нэйт Турмонд"],
  ["warriors", 3, "Jonathan Kuminga", "Джонатан Куминга"],

  // LA Clippers
  ["clippers", 1, "Kawhi Leonard", "Кавай Леонард"],
  ["clippers", 1, "Chris Paul", "Крис Пол"],
  ["clippers", 1, "Blake Griffin", "Блейк Гриффин"],
  ["clippers", 1, "Paul George", "Пол Джордж"],
  ["clippers", 2, "James Harden", "Джеймс Харден"],
  ["clippers", 2, "DeAndre Jordan", "ДеАндре Джордан"],
  ["clippers", 2, "Lou Williams", "Лу Уильямс"],
  ["clippers", 3, "Elton Brand", "Элтон Брэнд"],
  ["clippers", 3, "Eric Gordon", "Эрик Гордон"],
  ["clippers", 3, "Corey Maggette", "Кори Мэджетт"],
  ["clippers", 3, "Danny Manning", "Дэнни Мэннинг"],
  ["clippers", 3, "Norman Powell", "Норман Пауэлл"],

  // Los Angeles Lakers
  ["lakers", 1, "Kobe Bryant", "Коби Брайант"],
  ["lakers", 1, "LeBron James", "Леброн Джеймс"],
  ["lakers", 1, "Magic Johnson", "Мэджик Джонсон"],
  ["lakers", 1, "Kareem Abdul-Jabbar", "Карим Абдул-Джаббар"],
  ["lakers", 1, "Shaquille O'Neal", "Шакил О'Нил"],
  ["lakers", 2, "Anthony Davis", "Энтони Дэвис"],
  ["lakers", 2, "Jerry West", "Джерри Уэст"],
  ["lakers", 2, "James Worthy", "Джеймс Уорти"],
  ["lakers", 2, "Pau Gasol", "Пау Газоль"],
  ["lakers", 3, "Elgin Baylor", "Элджин Бэйлор"],
  ["lakers", 3, "Wilt Chamberlain", "Уилт Чемберлен"],
  ["lakers", 3, "Gary Payton", "Гэри Пэйтон"],
  ["lakers", 3, "Lamar Odom", "Ламар Одом"],
  ["lakers", 3, "Luka Doncic", "Лука Дончич"],

  // Phoenix Suns
  ["suns", 1, "Steve Nash", "Стив Нэш"],
  ["suns", 1, "Charles Barkley", "Чарльз Баркли"],
  ["suns", 1, "Devin Booker", "Девин Букер"],
  ["suns", 1, "Kevin Durant", "Кевин Дюрант"],
  ["suns", 2, "Amar'e Stoudemire", "Амаре Стадемайр"],
  ["suns", 2, "Chris Paul", "Крис Пол"],
  ["suns", 2, "Shawn Marion", "Шон Мэрион"],
  ["suns", 2, "Walter Davis", "Уолтер Дэвис"],
  ["suns", 3, "Kevin Johnson", "Кевин Джонсон"],
  ["suns", 3, "Dan Majerle", "Дэн Мэйджерли"],
  ["suns", 3, "Tom Chambers", "Том Чемберс"],
  ["suns", 3, "Goran Dragic", "Горан Драгич"],

  // Sacramento Kings
  ["kings", 1, "De'Aaron Fox", "Де'Аарон Фокс"],
  ["kings", 1, "Chris Webber", "Крис Уэббер"],
  ["kings", 1, "DeMarcus Cousins", "ДеМаркус Кузинс"],
  ["kings", 2, "Domantas Sabonis", "Домантас Сабонис"],
  ["kings", 2, "Mitch Richmond", "Митч Ричмонд"],
  ["kings", 2, "Peja Stojakovic", "Пея Стоякович"],
  ["kings", 2, "Vlade Divac", "Владе Дивац"],
  ["kings", 3, "Tyreke Evans", "Тайрик Эванс"],
  ["kings", 3, "Mike Bibby", "Майк Бибби"],
  ["kings", 3, "Oscar Robertson", "Оскар Робертсон"],
  ["kings", 3, "Jason Williams", "Джейсон Уильямс"],
  ["kings", 3, "Doug Christie", "Даг Кристи"],
]);
