/* NBA — Southeast */
addWords("nba", [
  // Atlanta Hawks
  ["hawks", 1, "Trae Young", "Трэй Янг"],
  ["hawks", 1, "Dominique Wilkins", "Доминик Уилкинс"],
  ["hawks", 2, "Dikembe Mutombo", "Дикембе Мутомбо"],
  ["hawks", 2, "Jalen Johnson", "Джейлен Джонсон"],
  ["hawks", 2, "Dejounte Murray", "Деджонте Мюррей"],
  ["hawks", 2, "Al Horford", "Эл Хорфорд"],
  ["hawks", 2, "Joe Johnson", "Джо Джонсон"],
  ["hawks", 3, "John Collins", "Джон Коллинз"],
  ["hawks", 3, "Bob Pettit", "Боб Петтит"],
  ["hawks", 3, "Lou Hudson", "Лу Хадсон"],
  ["hawks", 3, "Josh Smith", "Джош Смит"],
  ["hawks", 3, "Mookie Blaylock", "Муки Блэйлок"],

  // Charlotte Hornets
  ["hornets", 1, "LaMelo Ball", "Ламело Болл"],
  ["hornets", 1, "Larry Johnson", "Ларри Джонсон"],
  ["hornets", 2, "Alonzo Mourning", "Алонзо Моурнинг"],
  ["hornets", 2, "Kemba Walker", "Кемба Уокер"],
  ["hornets", 2, "Glen Rice", "Глен Райс"],
  ["hornets", 2, "Baron Davis", "Бэрон Дэвис"],
  ["hornets", 3, "Muggsy Bogues", "Магси Богз"],
  ["hornets", 3, "Dell Curry", "Делл Карри"],
  ["hornets", 3, "Gerald Wallace", "Джеральд Уоллес"],
  ["hornets", 3, "Emeka Okafor", "Эмека Окафор"],
  ["hornets", 3, "Brandon Miller", "Брэндон Миллер"],
  ["hornets", 3, "Miles Bridges", "Майлз Бриджес"],

  // Miami Heat
  ["heat", 1, "Dwyane Wade", "Дуэйн Уэйд"],
  ["heat", 1, "LeBron James", "Леброн Джеймс"],
  ["heat", 2, "Jimmy Butler", "Джимми Батлер"],
  ["heat", 2, "Alonzo Mourning", "Алонзо Моурнинг"],
  ["heat", 2, "Bam Adebayo", "Бэм Адебайо"],
  ["heat", 2, "Chris Bosh", "Крис Бош"],
  ["heat", 2, "Tyler Herro", "Тайлер Хирро"],
  ["heat", 3, "Tim Hardaway", "Тим Хардуэй"],
  ["heat", 3, "Udonis Haslem", "Удонис Хаслем"],
  ["heat", 3, "Goran Dragic", "Горан Драгич"],
  ["heat", 3, "Glen Rice", "Глен Райс"],
  ["heat", 3, "Shane Battier", "Шейн Баттье"],

  // Orlando Magic
  ["magic", 1, "Shaquille O'Neal", "Шакил О'Нил"],
  ["magic", 1, "Tracy McGrady", "Трэйси Макгрэйди"],
  ["magic", 2, "Dwight Howard", "Дуайт Ховард"],
  ["magic", 2, "Penny Hardaway", "Пенни Хардуэй"],
  ["magic", 2, "Paolo Banchero", "Паоло Банкеро"],
  ["magic", 2, "Franz Wagner", "Франц Вагнер"],
  ["magic", 3, "Nikola Vucevic", "Никола Вучевич"],
  ["magic", 3, "Hedo Turkoglu", "Хедо Тюркоглу"],
  ["magic", 3, "Rashard Lewis", "Рашард Льюис"],
  ["magic", 3, "Jameer Nelson", "Джамир Нельсон"],
  ["magic", 3, "Grant Hill", "Грант Хилл"],
  ["magic", 3, "Aaron Gordon", "Аарон Гордон"],

  // Washington Wizards
  ["wizards", 1, "John Wall", "Джон Уолл"],
  ["wizards", 1, "Gilbert Arenas", "Гилберт Аринас"],
  ["wizards", 2, "Bradley Beal", "Брэдли Бил"],
  ["wizards", 2, "Wes Unseld", "Уэс Анселд"],
  ["wizards", 2, "Elvin Hayes", "Элвин Хейс"],
  ["wizards", 2, "Chris Webber", "Крис Уэббер"],
  ["wizards", 3, "Caron Butler", "Кэрон Батлер"],
  ["wizards", 3, "Antawn Jamison", "Антуан Джеймисон"],
  ["wizards", 3, "Juwan Howard", "Джуван Ховард"],
  ["wizards", 3, "Rasheed Wallace", "Рашид Уоллес"],
  ["wizards", 3, "Kyle Kuzma", "Кайл Кузма"],
  ["wizards", 3, "Wesley Unseld Jr.", "Уэсли Анселд мл."],
]);
