/* Films — Action/Sci-fi characters */
addWords("films", [
  ["ch_action", 1, "The Terminator", "Терминатор", "draw", 1984],
  ["ch_action", 1, "John Wick", "Джон Уик", 2014],
  ["ch_action", 1, "Mad Max", "Безумный Макс", 1979],
  ["ch_action", 1, "Indiana Jones", "Индиана Джонс", 1981],
  ["ch_action", 1, "Rocky Balboa", "Рокки Бальбоа", 1976],
  ["ch_action", 1, "Rambo", "Рэмбо", 1982],
  ["ch_action", 1, "Neo", "Нео", 1999],
  ["ch_action", 1, "Ellen Ripley", "Эллен Рипли", 1979],
  ["ch_action", 1, "Jack Sparrow", "Джек Воробей", 2003],
  ["ch_action", 1, "Forrest Gump", "Форрест Гамп", 1994],
  ["ch_action", 1, "Hannibal Lecter", "Ганнибал Лектер", 1991],
  ["ch_action", 1, "Marty McFly", "Марти МакФлай", 1985],
  ["ch_action", 1, "Tony Montana", "Тони Монтана", 1983],
  ["ch_action", 1, "Vito Corleone", "Вито Корлеоне", 1972],
  ["ch_action", 1, "The Predator", "Хищник", "draw", 1987],
  ["ch_action", 1, "Xenomorph", "Ксеноморф", "draw", 1979],
  ["ch_action", 1, "RoboCop", "РобоКоп", "draw", 1987],
  ["ch_action", 1, "King Kong", "Кинг Конг", "draw", 1933],
  ["ch_action", 1, "Godzilla", "Годзилла", "draw", 1954],
  ["ch_action", 2, "Morpheus", "Морфеус", 1999],
  ["ch_action", 2, "Trinity", "Тринити", 1999],
  ["ch_action", 2, "Agent Smith", "Агент Смит", 1999],
  ["ch_action", 2, "Doc Brown", "Доктор Браун", 1985],
  ["ch_action", 2, "Maximus", "Максимус", 2000],
  ["ch_action", 2, "Michael Corleone", "Майкл Корлеоне", 1972],
  ["ch_action", 2, "Travis Bickle", "Трэвис Бикл", 1976],
  ["ch_action", 2, "Jason Bourne", "Джейсон Борн", 2002],
  ["ch_action", 2, "Ethan Hunt", "Итан Хант", 1996],
  ["ch_action", 2, "Optimus Prime", "Оптимус Прайм", "draw", 2007],
  ["ch_action", 2, "T-1000", "Т-1000", "draw", 1991],
  ["ch_action", 3, "Snake Plissken", "Змей Плискин", 1981],
  ["ch_action", 3, "Sarah Connor", "Сара Коннор", 1984],
  ["ch_action", 3, "Roy Batty", "Рой Батти", 1982],
  ["ch_action", 3, "Dutch", "Датч", 1987],
]);
