/* Films — James Bond characters */
addWords("films", [
  ["ch_bond", 1, "James Bond", "Джеймс Бонд", 1962],
  ["ch_bond", 1, "M", "М", 1962],
  ["ch_bond", 1, "Q", "Кью", 1962],
  ["ch_bond", 1, "Moneypenny", "Манипенни", 1962],
  ["ch_bond", 2, "Blofeld", "Блофельд", 1962],
  ["ch_bond", 2, "Goldfinger", "Голдфингер", 1962],
  ["ch_bond", 2, "Jaws", "Челюсти", 1962],
  ["ch_bond", 2, "Oddjob", "Оддджоб", 1962],
  ["ch_bond", 2, "Le Chiffre", "Ле Шифр", 1962],
  ["ch_bond", 2, "Dr. No", "Доктор Ноу", 1962],
  ["ch_bond", 2, "Scaramanga", "Скараманга", 1962],
  ["ch_bond", 2, "Raoul Silva", "Рауль Сильва", 1962],
  ["ch_bond", 2, "May Day", "Мэй Дэй", 1962],
  ["ch_bond", 3, "Vesper Lynd", "Веспер Линд", 1962],
  ["ch_bond", 3, "Felix Leiter", "Феликс Лейтер", 1962],
  ["ch_bond", 3, "Xenia Onatopp", "Ксения Онатопп", 1962],
  ["ch_bond", 3, "Pussy Galore", "Пасси Галор", 1962],
  ["ch_bond", 3, "Honey Ryder", "Хани Райдер", 1962],
  ["ch_bond", 3, "Rosa Klebb", "Роза Клебб", 1962],
  ["ch_bond", 3, "Mr. White", "Мистер Уайт", 1962],
  ["ch_bond", 3, "Elektra King", "Электра Кинг", 1962],
  ["ch_bond", 3, "Nomi", "Номи", 1962],
]);
