/* Films — Disney/Pixar characters */
addWords("films", [
  ["ch_disney", 1, "Mickey Mouse", "Микки Маус", "draw", 1928],
  ["ch_disney", 1, "Donald Duck", "Дональд Дак", "draw", 1934],
  ["ch_disney", 1, "Simba", "Симба", "draw", 1994],
  ["ch_disney", 1, "Elsa", "Эльза", "draw", 2013],
  ["ch_disney", 1, "Anna", "Анна", "draw", 2013],
  ["ch_disney", 1, "Olaf", "Олаф", "draw", 2013],
  ["ch_disney", 1, "Woody", "Вуди", "draw", 1995],
  ["ch_disney", 1, "Buzz Lightyear", "Базз Лайтер", "draw", 1995],
  ["ch_disney", 1, "Nemo", "Немо", "draw", 2003],
  ["ch_disney", 1, "Dory", "Дори", "draw", 2003],
  ["ch_disney", 1, "Ariel", "Ариэль", "draw", 1989],
  ["ch_disney", 1, "Cinderella", "Золушка", "draw", 1950],
  ["ch_disney", 1, "Snow White", "Белоснежка", "draw", 1937],
  ["ch_disney", 1, "Aladdin", "Аладдин", "draw", 1992],
  ["ch_disney", 1, "Genie", "Джинн", "draw", 1992],
  ["ch_disney", 1, "Lightning McQueen", "Молния Маккуин", "draw", 2006],
  ["ch_disney", 1, "WALL-E", "ВАЛЛ-И", "draw", 2008],
  ["ch_disney", 1, "Stitch", "Стич", "draw", 2002],
  ["ch_disney", 1, "Moana", "Моана", "draw", 2016],
  ["ch_disney", 2, "Mike Wazowski", "Майк Вазовски", "draw", 2001],
  ["ch_disney", 2, "Sulley", "Салли", "draw", 2001],
  ["ch_disney", 2, "Belle", "Белль", "draw", 1991],
  ["ch_disney", 2, "Mulan", "Мулан", "draw", 1998],
  ["ch_disney", 2, "Maui", "Мауи", 2016],
  ["ch_disney", 2, "Mr. Incredible", "Мистер Исключительный", 2004],
  ["ch_disney", 2, "Remy", "Реми", "draw", 2007],
  ["ch_disney", 2, "Pinocchio", "Пиноккио", "draw", 1940],
  ["ch_disney", 2, "Peter Pan", "Питер Пэн", "draw", 1953],
  ["ch_disney", 2, "Scar", "Шрам", 1994],
  ["ch_disney", 2, "Ursula", "Урсула", 1989],
  ["ch_disney", 2, "Maleficent", "Малефисента", 1959],
  ["ch_disney", 2, "Jafar", "Джафар", 1992],
  ["ch_disney", 2, "Gaston", "Гастон", 1991],
  ["ch_disney", 3, "Hades", "Аид", 1997],
  ["ch_disney", 3, "Goofy", "Гуфи", "draw", 1932],
  ["ch_disney", 3, "Tinker Bell", "Динь-Динь", "draw", 1953],
  ["ch_disney", 3, "Dumbo", "Дамбо", "draw", 1941],
  ["ch_disney", 3, "Bambi", "Бэмби", "draw", 1942],
]);
