/* Films — Harry Potter characters */
addWords("films", [
  ["ch_harrypotter", 1, "Harry Potter", "Гарри Поттер", 2001],
  ["ch_harrypotter", 1, "Hermione Granger", "Гермиона Грейнджер", 2001],
  ["ch_harrypotter", 1, "Ron Weasley", "Рон Уизли", 2001],
  ["ch_harrypotter", 1, "Albus Dumbledore", "Альбус Дамблдор", 2001],
  ["ch_harrypotter", 1, "Voldemort", "Волдеморт", 2001],
  ["ch_harrypotter", 1, "Severus Snape", "Северус Снейп", 2001],
  ["ch_harrypotter", 1, "Rubeus Hagrid", "Рубеус Хагрид", 2001],
  ["ch_harrypotter", 1, "Draco Malfoy", "Драко Малфой", 2001],
  ["ch_harrypotter", 2, "Sirius Black", "Сириус Блэк", 2001],
  ["ch_harrypotter", 2, "Bellatrix Lestrange", "Беллатриса Лестрейндж", 2001],
  ["ch_harrypotter", 2, "Minerva McGonagall", "Минерва МакГонагалл", 2001],
  ["ch_harrypotter", 2, "Dobby", "Добби", 2001],
  ["ch_harrypotter", 2, "Luna Lovegood", "Полумна Лавгуд", 2001],
  ["ch_harrypotter", 2, "Neville Longbottom", "Невилл Долгопупс", 2001],
  ["ch_harrypotter", 2, "Ginny Weasley", "Джинни Уизли", 2001],
  ["ch_harrypotter", 2, "Fred Weasley", "Фред Уизли", 2001],
  ["ch_harrypotter", 2, "George Weasley", "Джордж Уизли", 2001],
  ["ch_harrypotter", 2, "Remus Lupin", "Римус Люпин", 2001],
  ["ch_harrypotter", 2, "Alastor Moody", "Аластор Грюм", 2001],
  ["ch_harrypotter", 2, "Dolores Umbridge", "Долорес Амбридж", 2001],
  ["ch_harrypotter", 2, "Cedric Diggory", "Седрик Диггори", 2001],
  ["ch_harrypotter", 2, "Cho Chang", "Чжоу Чанг", 2001],
  ["ch_harrypotter", 2, "Lucius Malfoy", "Люциус Малфой", 2001],
  ["ch_harrypotter", 2, "Peter Pettigrew", "Питер Петтигрю", 2001],
  ["ch_harrypotter", 2, "Nymphadora Tonks", "Нимфадора Тонкс", 2001],
  ["ch_harrypotter", 3, "Kingsley Shacklebolt", "Кингсли Бруствер", 2001],
  ["ch_harrypotter", 3, "Molly Weasley", "Молли Уизли", 2001],
  ["ch_harrypotter", 3, "Arthur Weasley", "Артур Уизли", 2001],
  ["ch_harrypotter", 3, "Fleur Delacour", "Флёр Делакур", 2001],
  ["ch_harrypotter", 3, "Quirinus Quirrell", "Квириний Квиррелл", 2001],
  ["ch_harrypotter", 3, "Gilderoy Lockhart", "Гилдерой Локонс", 2001],
  ["ch_harrypotter", 3, "Narcissa Malfoy", "Нарцисса Малфой", 2001],
  ["ch_harrypotter", 3, "Lavender Brown", "Лаванда Браун", 2001],
]);
