/* Films — Star Wars characters */
addWords("films", [
  ["ch_starwars", 1, "Darth Vader", "Дарт Вейдер", "draw", 1977],
  ["ch_starwars", 1, "Luke Skywalker", "Люк Скайуокер", "draw", 1977],
  ["ch_starwars", 1, "Princess Leia", "Принцесса Лея", "draw", 1977],
  ["ch_starwars", 1, "Han Solo", "Хан Соло", 1977],
  ["ch_starwars", 1, "Chewbacca", "Чубакка", "draw", 1977],
  ["ch_starwars", 1, "Yoda", "Йода", "draw", 1977],
  ["ch_starwars", 1, "Obi-Wan Kenobi", "Оби-Ван Кеноби", 1977],
  ["ch_starwars", 1, "R2-D2", "Р2-Д2", "draw", 1977],
  ["ch_starwars", 1, "C-3PO", "Си-Трипио", "draw", 1977],
  ["ch_starwars", 1, "Stormtrooper", "Штурмовик", "draw", 1977],
  ["ch_starwars", 1, "Emperor Palpatine", "Император Палпатин", 1977],
  ["ch_starwars", 1, "Boba Fett", "Боба Фетт", "draw", 1977],
  ["ch_starwars", 1, "Jabba the Hutt", "Джабба Хатт", "draw", 1977],
  ["ch_starwars", 1, "Grogu", "Грогу", "draw", 1977],
  ["ch_starwars", 1, "Kylo Ren", "Кайло Рен", "draw", 1977],
  ["ch_starwars", 1, "Rey", "Рей", 1977],
  ["ch_starwars", 2, "Darth Maul", "Дарт Мол", "draw", 1977],
  ["ch_starwars", 2, "Lando Calrissian", "Лэндо Калриссиан", 1977],
  ["ch_starwars", 2, "Anakin Skywalker", "Энакин Скайуокер", 1977],
  ["ch_starwars", 2, "Padmé Amidala", "Падме Амидала", 1977],
  ["ch_starwars", 2, "Mace Windu", "Мейс Винду", 1977],
  ["ch_starwars", 2, "Count Dooku", "Граф Дуку", 1977],
  ["ch_starwars", 2, "General Grievous", "Генерал Grievous", "draw", 1977],
  ["ch_starwars", 2, "Jango Fett", "Джанго Фетт", 1977],
  ["ch_starwars", 2, "BB-8", "ББ-8", "draw", 1977],
  ["ch_starwars", 2, "Finn", "Финн", 1977],
  ["ch_starwars", 2, "Poe Dameron", "По Дамерон", 1977],
  ["ch_starwars", 2, "The Mandalorian", "Мандалорец", "draw", 1977],
  ["ch_starwars", 2, "Ahsoka Tano", "Асока Тано", 1977],
  ["ch_starwars", 3, "Qui-Gon Jinn", "Куай-Гон Джинн", 1977],
  ["ch_starwars", 3, "Jar Jar Binks", "Джа-Джа Бинкс", "draw", 1977],
  ["ch_starwars", 3, "Grand Moff Tarkin", "Гранд Мофф Таркин", 1977],
  ["ch_starwars", 3, "Admiral Ackbar", "Адмирал Акбар", "draw", 1977],
  ["ch_starwars", 3, "IG-11", "ИГ-11", "draw", 1977],
]);
