/* Football — La Liga Now */
addWords("football", [
  ["cur_laliga", 1, "Jude Bellingham", "Джуд Беллингем"],
  ["cur_laliga", 1, "Vinícius Júnior", "Винисиус Жуниор"],
  ["cur_laliga", 1, "Kylian Mbappé", "Килиан Мбаппе"],
  ["cur_laliga", 1, "Lamine Yamal", "Ламин Ямаль"],
  ["cur_laliga", 1, "Pedri", "Педри"],
  ["cur_laliga", 1, "Robert Lewandowski", "Роберт Левандовски"],
  ["cur_laliga", 1, "Antoine Griezmann", "Антуан Гризманн"],
  ["cur_laliga", 1, "Raphinha", "Рафинья"],
  ["cur_laliga", 1, "Rodrygo", "Родриго"],
  ["cur_laliga", 1, "Gavi", "Гави"],
  ["cur_laliga", 2, "Thibaut Courtois", "Тибо Куртуа"],
  ["cur_laliga", 2, "Federico Valverde", "Федерико Вальверде"],
  ["cur_laliga", 2, "Aurélien Tchouaméni", "Орельен Чуамени"],
  ["cur_laliga", 2, "Eduardo Camavinga", "Эдуардо Камавинга"],
  ["cur_laliga", 2, "Antonio Rüdiger", "Антонио Рюдигер"],
  ["cur_laliga", 2, "Dani Carvajal", "Дани Карвахаль"],
  ["cur_laliga", 2, "Éder Militão", "Эдер Милитао"],
  ["cur_laliga", 2, "Luka Modrić", "Лука Модрич"],
  ["cur_laliga", 2, "Frenkie de Jong", "Френки де Йонг"],
  ["cur_laliga", 2, "Marc-André ter Stegen", "Марк-Андре тер Штеген"],
  ["cur_laliga", 2, "Jules Koundé", "Жюль Кунде"],
  ["cur_laliga", 2, "Ronald Araújo", "Рональд Араухо"],
  ["cur_laliga", 2, "Pau Cubarsí", "Пау Кубарси"],
  ["cur_laliga", 2, "Alejandro Balde", "Алехандро Бальде"],
  ["cur_laliga", 2, "Ferran Torres", "Ферран Торрес"],
  ["cur_laliga", 2, "Dani Olmo", "Дани Ольмо"],
  ["cur_laliga", 2, "Julián Álvarez", "Хулиан Альварес"],
  ["cur_laliga", 2, "Jan Oblak", "Ян Облак"],
  ["cur_laliga", 2, "Koke", "Коке"],
  ["cur_laliga", 2, "Marcos Llorente", "Маркос Льоренте"],
  ["cur_laliga", 2, "José Giménez", "Хосе Хименес"],
  ["cur_laliga", 2, "Nico Williams", "Нико Уильямс"],
  ["cur_laliga", 2, "Iñaki Williams", "Иньяки Уильямс"],
  ["cur_laliga", 2, "Mikel Oyarzabal", "Микель Оярсабаль"],
  ["cur_laliga", 2, "Takefusa Kubo", "Такэфуса Кубо"],
  ["cur_laliga", 2, "Álex Baena", "Алекс Баэна"],
  ["cur_laliga", 2, "Conor Gallagher", "Конор Гэллахер"],
  ["cur_laliga", 2, "Endrick", "Эндрик"],
  ["cur_laliga", 2, "Álvaro Morata", "Альваро Мората"],
  ["cur_laliga", 3, "Brahim Díaz", "Брахим Диас"],
  ["cur_laliga", 3, "Lucas Vázquez", "Лукас Васкес"],
  ["cur_laliga", 3, "Fran García", "Фран Гарсия"],
  ["cur_laliga", 3, "Andriy Lunin", "Андрей Лунин"],
  ["cur_laliga", 3, "Arda Güler", "Арда Гюлер"],
  ["cur_laliga", 3, "Dani Ceballos", "Дани Себальос"],
  ["cur_laliga", 3, "Iñigo Martínez", "Иньиго Мартинес"],
  ["cur_laliga", 3, "Andreas Christensen", "Андреас Кристенсен"],
  ["cur_laliga", 3, "Marc Casadó", "Марк Касадо"],
  ["cur_laliga", 3, "Fermín López", "Фермин Лопес"],
  ["cur_laliga", 3, "Iñaki Peña", "Иньяки Пенья"],
  ["cur_laliga", 3, "Pablo Barrios", "Пабло Барриос"],
  ["cur_laliga", 3, "Rodrigo De Paul", "Родриго Де Пауль"],
  ["cur_laliga", 3, "Ángel Correa", "Анхель Корреа"],
  ["cur_laliga", 3, "Thomas Lemar", "Тома Лемар"],
  ["cur_laliga", 3, "Robin Le Normand", "Робен Ле Норман"],
  ["cur_laliga", 3, "Samu Aghehowa", "Саму Агеова"],
  ["cur_laliga", 3, "Álex Remiro", "Алекс Ремиро"],
  ["cur_laliga", 3, "Martín Zubimendi", "Мартин Субименди"],
  ["cur_laliga", 3, "Brais Méndez", "Браис Мендес"],
  ["cur_laliga", 3, "Oihan Sancet", "Ойан Сансет"],
  ["cur_laliga", 3, "Unai Simón", "Унаи Симон"],
  ["cur_laliga", 3, "Mikel Merino", "Микель Мерино"],
  ["cur_laliga", 3, "Dani Vivian", "Дани Вивиан"],
  ["cur_laliga", 3, "Yangel Herrera", "Янхель Эррера"],
  ["cur_laliga", 3, "Isco", "Иско"],
  ["cur_laliga", 3, "Borja Iglesias", "Борха Иглесиас"],
  ["cur_laliga", 3, "Sergio Canales", "Серхио Каналес"],
  ["cur_laliga", 3, "Aitor Ruibal", "Айтор Руибаль"],
  ["cur_laliga", 3, "Hugo Duro", "Уго Дуро"],
  ["cur_laliga", 3, "Giorgi Mamardashvili", "Георгий Мамардашвили"],
  ["cur_laliga", 3, "Aleix García", "Алейш Гарсия"],
  ["cur_laliga", 3, "Cristhian Stuani", "Кристиан Стуани"],
  ["cur_laliga", 3, "Giovani Lo Celso", "Джовани Ло Чельсо"],
  ["cur_laliga", 3, "Ante Budimir", "Анте Будимир"],
  ["cur_laliga", 3, "Lucas Ocampos", "Лукас Окампос"],
  ["cur_laliga", 3, "Chimy Ávila", "Чими Авила"],
  ["cur_laliga", 3, "Bryan Gil", "Брайан Хиль"],
  ["cur_laliga", 3, "Sergi Darder", "Серхи Дардер"],
  ["cur_laliga", 3, "Gerard Moreno", "Херард Морено"],
  ["cur_laliga", 3, "Pau Torres", "Пау Торрес"],
  ["cur_laliga", 3, "Eric García", "Эрик Гарсия"],
]);
