/* Football — Serie A Now */
addWords("football", [
  // ── TIER 1: SUPERSTARS ──────────────────────────────────────────────────
  ["cur_seriea", 1, "Lautaro Martínez", "Лаутаро Мартинес"],
  ["cur_seriea", 1, "Rafael Leão", "Рафаэль Леан"],
  ["cur_seriea", 1, "Khvicha Kvaratskhelia", "Хвича Кварацхелия"],
  ["cur_seriea", 1, "Marcus Thuram", "Маркус Тюрам"],
  ["cur_seriea", 1, "Dušan Vlahović", "Душан Влахович"],
  ["cur_seriea", 1, "Nicolò Barella", "Николо Барелла"],
  ["cur_seriea", 1, "Theo Hernández", "Тео Эрнандес"],
  ["cur_seriea", 1, "Christian Pulisic", "Кристиан Пулишич"],
  ["cur_seriea", 1, "Ademola Lookman", "Аdemola Лукман"],
  ["cur_seriea", 1, "Mateo Retegui", "Матео Ретеги"],
  ["cur_seriea", 1, "Paulo Dybala", "Пауло Дибала"],
  ["cur_seriea", 1, "Romelu Lukaku", "Ромелу Лукаку"],
  ["cur_seriea", 1, "Hakan Çalhanoğlu", "Хакан Чалханоглу"],
  // ── TIER 2: WELL-KNOWN ──────────────────────────────────────────────────
  ["cur_seriea", 2, "Moise Kean", "Муазе Кин"],
  ["cur_seriea", 2, "Kenan Yıldız", "Кенан Йылдыз"],
  ["cur_seriea", 2, "Teun Koopmeiners", "Тёйн Копмейнерс"],
  ["cur_seriea", 2, "Tijjani Reijnders", "Тийяни Рейндерс"],
  ["cur_seriea", 2, "Scott McTominay", "Скотт МакТоминай"],
  ["cur_seriea", 2, "Artem Dovbyk", "Артём Довбик"],
  ["cur_seriea", 2, "Álvaro Morata", "Альваро Мората"],
  ["cur_seriea", 2, "Federico Dimarco", "Федерико Димарко"],
  ["cur_seriea", 2, "Alessandro Bastoni", "Алессандро Бастони"],
  ["cur_seriea", 2, "Davide Frattesi", "Давиде Фраттези"],
  ["cur_seriea", 2, "Ruben Loftus-Cheek", "Рубен Лофтус-Чик"],
  ["cur_seriea", 2, "Fikayo Tomori", "Фикайо Томори"],
  ["cur_seriea", 2, "Strahinja Pavlović", "Страхиня Павлович"],
  ["cur_seriea", 2, "Mattia Zaccagni", "Маттиа Дзаккани"],
  ["cur_seriea", 2, "Giovanni Di Lorenzo", "Джованни Ди Лоренцо"],
  ["cur_seriea", 2, "Gleison Bremer", "Глейсон Бремер"],
  ["cur_seriea", 2, "Andrea Cambiaso", "Андреа Камбьязо"],
  ["cur_seriea", 2, "Riccardo Orsolini", "Риккардо Орсолини"],
  ["cur_seriea", 2, "Lorenzo Pellegrini", "Лоренцо Пеллегрини"],
  ["cur_seriea", 2, "Mehdi Taremi", "Мехди Тареми"],
  ["cur_seriea", 2, "Yann Sommer", "Янн Зоммер"],
  ["cur_seriea", 2, "Mike Maignan", "Майк Меньян"],
  ["cur_seriea", 2, "Benjamin Pavard", "Бенжамен Павар"],
  ["cur_seriea", 2, "Gianluca Scamacca", "Джанлука Скамакка"],
  ["cur_seriea", 2, "Manuel Locatelli", "Мануэль Локателли"],
  ["cur_seriea", 2, "Ivan Provedel", "Иван Проведел"],
  ["cur_seriea", 2, "Alexis Saelemaekers", "Алексис Салемакерс"],
  ["cur_seriea", 2, "Lorenzo Lucca", "Лоренцо Лукка"],
  ["cur_seriea", 2, "Dan Ndoye", "Дан Ндойе"],
  ["cur_seriea", 2, "Santiago Castro", "Сантьяго Кастро"],
  ["cur_seriea", 2, "Charles De Ketelaere", "Шарль Де Кетелаер"],
  // ── TIER 3: SOLID / ROLE PLAYERS ────────────────────────────────────────
  ["cur_seriea", 3, "Alessandro Buongiorno", "Алессандро Буонджорно"],
  ["cur_seriea", 3, "Stanislav Lobotka", "Станислав Лоботка"],
  ["cur_seriea", 3, "André Zambo Anguissa", "Андре Замбо Ангисса"],
  ["cur_seriea", 3, "Alex Meret", "Алекс Мерет"],
  ["cur_seriea", 3, "David Neres", "Давид Нерес"],
  ["cur_seriea", 3, "Matías Olivera", "Матиас Оливера"],
  ["cur_seriea", 3, "Piotr Zieliński", "Пётр Зелиньский"],
  ["cur_seriea", 3, "Henrikh Mkhitaryan", "Генрих Мхитарян"],
  ["cur_seriea", 3, "Denzel Dumfries", "Дензел Дюмфрис"],
  ["cur_seriea", 3, "Stephan El Shaarawy", "Стефан Эль-Шаарауи"],
  ["cur_seriea", 3, "Nikola Krstović", "Никола Крстович"],
  ["cur_seriea", 3, "Marten de Roon", "Мартен де Роон"],
  ["cur_seriea", 3, "Éderson", "Эдерсон"],
  ["cur_seriea", 3, "Mario Pašalić", "Марио Пашалич"],
  ["cur_seriea", 3, "Matías Soulé", "Матиас Суле"],
  ["cur_seriea", 3, "Remo Freuler", "Ремо Фройлер"],
  ["cur_seriea", 3, "Juan Lucumí", "Хуан Лукуми"],
  ["cur_seriea", 3, "Stefan Posch", "Штефан Пош"],
  ["cur_seriea", 3, "Federico Gatti", "Федерико Гатти"],
  ["cur_seriea", 3, "Weston McKennie", "Уэстон МакКенни"],
  ["cur_seriea", 3, "Francisco Conceição", "Франсиско Консейсан"],
  ["cur_seriea", 3, "Mattia Gabbia", "Маттиа Габбия"],
  ["cur_seriea", 3, "Youssouf Fofana", "Юссуф Фофана"],
  ["cur_seriea", 3, "Yunus Musah", "Юнус Мусах"],
  ["cur_seriea", 3, "Valentin Castellanos", "Валентин Кастельянос"],
  ["cur_seriea", 3, "Andrea Colpani", "Андреа Колпани"],
  ["cur_seriea", 3, "Edoardo Bove", "Эдоардо Бове"],
  ["cur_seriea", 3, "Robin Gosens", "Робин Гозенс"],
  ["cur_seriea", 3, "Valentín Carboni", "Валентин Карбони"],
  ["cur_seriea", 3, "Amir Rrahmani", "Амир Ррахмани"],
  ["cur_seriea", 3, "Stefan de Vrij", "Стефан де Врай"],
  ["cur_seriea", 3, "Francesco Acerbi", "Франческо Ачерби"],
  ["cur_seriea", 3, "Yann Bisseck", "Янн Биссек"],
  ["cur_seriea", 3, "Samuel Chukwueze", "Самуэль Чуквуэзе"],
  ["cur_seriea", 3, "Matteo Guendouzi", "Маттео Гендузи"],
  ["cur_seriea", 3, "Boulaye Dia", "Буле Диа"],
]);
