// Current Ligue 1 players (2024–2026 seasons)
addWords("football", [
  ["cur_ligue1", 1, "Ousmane Dembélé", "Усман Дембеле"],
  ["cur_ligue1", 1, "Bradley Barcola", "Брэдли Барколя"],
  ["cur_ligue1", 1, "Jonathan David", "Джонатан Давид"],
  ["cur_ligue1", 1, "Marquinhos", "Маркиньос"],
  ["cur_ligue1", 1, "Achraf Hakimi", "Ашраф Хакими"],
  ["cur_ligue1", 1, "Vitinha", "Витинья"],
  ["cur_ligue1", 1, "João Neves", "Жоао Невеш"],
  ["cur_ligue1", 2, "Désiré Doué", "Дезире Дуэ"],
  ["cur_ligue1", 2, "Fabian Ruiz", "Фабиан Руис"],
  ["cur_ligue1", 2, "Warren Zaïre-Emery", "Уоррен Зер-Эмери"],
  ["cur_ligue1", 2, "Alexandre Lacazette", "Александр Лакасет"],
  ["cur_ligue1", 2, "Mason Greenwood", "Мейсон Гринвуд"],
  ["cur_ligue1", 2, "Khvicha Kvaratskhelia", "Хвича Кварацхелия"],
  ["cur_ligue1", 2, "Malik Akliouche", "Малик Аклюш"],
  ["cur_ligue1", 2, "Folarin Balogun", "Фолайн Балогун"],
  ["cur_ligue1", 2, "Randal Kolo Muani", "Рандаль Коло Муани"],
  ["cur_ligue1", 2, "Lucas Chevalier", "Люка Шевалье"],
  ["cur_ligue1", 2, "Leny Yoro", "Лени Йоро"],
  ["cur_ligue1", 2, "Pierre-Emerick Aubameyang", "Пьер-Эмерик Обамеянг"],
  ["cur_ligue1", 2, "Gerson", "Жерсон"],
  ["cur_ligue1", 2, "Samuel Gigot", "Самюэль Жиго"],
  ["cur_ligue1", 2, "Elye Wahi", "Эли Вахи"],
  ["cur_ligue1", 2, "Wissam Ben Yedder", "Виссам Бен Йеддер"],
  ["cur_ligue1", 2, "Breel Embolo", "Брил Эмболо"],
  ["cur_ligue1", 2, "Takumi Minamino", "Такуми Минамино"],
  ["cur_ligue1", 3, "Loïc Badé", "Луик Бадэ"],
  ["cur_ligue1", 3, "Arnaud Kalimuendo", "Арно Калимуендо"],
  ["cur_ligue1", 3, "Thilo Kehrer", "Тило Керер"],
  ["cur_ligue1", 3, "Benjamin Bourigeaud", "Бенжамен Буриго"],
  ["cur_ligue1", 3, "Hicham Boudaoui", "Хишам Будауи"],
  ["cur_ligue1", 3, "Denis Zakaria", "Дени Закариа"],
  ["cur_ligue1", 3, "Pau López", "Пау Лопес"],
  ["cur_ligue1", 3, "Milan Škrinijar", "Милан Шкриньяр"],
  ["cur_ligue1", 3, "Nicolas Pépé", "Николя Пепе"],
  ["cur_ligue1", 3, "Amine Gouiri", "Амин Гири"],
  ["cur_ligue1", 3, "Terem Moffi", "Терем Моффи"],
  ["cur_ligue1", 3, "Danilo Pereira", "Данилу Перейра"],
  ["cur_ligue1", 3, "Nuno Mendes", "Нуну Мендеш"],
  ["cur_ligue1", 3, "Lucas Paquetá", "Лукас Пакета"],
  ["cur_ligue1", 3, "Romain Faivre", "Ромен Февр"],
  ["cur_ligue1", 3, "Tanguy Ndombele", "Танги Ндомбеле"],
  ["cur_ligue1", 3, "Willian José", "Виллиан Жозе"],
  ["cur_ligue1", 3, "Sofiane Diop", "Суфьян Диоп"],
  ["cur_ligue1", 3, "Jordan Veretout", "Жордан Верету"],
  ["cur_ligue1", 3, "Youssouf Fofana", "Юссуф Фофана"],
  ["cur_ligue1", 3, "Alexis Saelemaekers", "Алексис Элемакерс"],
  ["cur_ligue1", 3, "Strahinja Pavlović", "Страхиня Павлович"],
  ["cur_ligue1", 3, "Mohamed Camara", "Мохамед Камара"],
  ["cur_ligue1", 3, "Eliesse Ben Seghir", "Элиес Бен Сгир"],
  ["cur_ligue1", 3, "Salim Ben Seghir", "Салим Бен Сгир"],
  ["cur_ligue1", 3, "Amine Harit", "Амин Харит"],
  ["cur_ligue1", 3, "Romain Del Castillo", "Ромен Дель Кастильо"],
  ["cur_ligue1", 3, "Ilan Kebbal", "Илан Кеббаль"],
  ["cur_ligue1", 3, "Wilfried Singo", "Вильфред Синго"],
]);
