/* Football — La Liga 2008-2020 */
addWords("football", [
  ["era_laliga", 1, "Lionel Messi", "Лионель Месси"],
  ["era_laliga", 1, "Cristiano Ronaldo", "Криштиану Роналду"],
  ["era_laliga", 1, "Andrés Iniesta", "Андрес Иньеста"],
  ["era_laliga", 1, "Xavi", "Хави"],
  ["era_laliga", 1, "Sergio Ramos", "Серхио Рамос"],
  ["era_laliga", 1, "Iker Casillas", "Икер Касильяс"],
  ["era_laliga", 1, "Luka Modrić", "Лука Модрич"],
  ["era_laliga", 1, "Toni Kroos", "Тони Кроос"],
  ["era_laliga", 1, "Gareth Bale", "Гарет Бэйл"],
  ["era_laliga", 1, "Luis Suárez", "Луис Суарес"],
  ["era_laliga", 1, "Neymar", "Неймар"],
  ["era_laliga", 1, "Antoine Griezmann", "Антуан Гризманн"],
  ["era_laliga", 1, "Karim Benzema", "Карим Бензема"],
  ["era_laliga", 1, "David Villa", "Давид Вилья"],
  ["era_laliga", 1, "Sergio Busquets", "Серхио Бускетс"],
  ["era_laliga", 1, "Gerard Piqué", "Жерар Пике"],
  ["era_laliga", 1, "Diego Costa", "Диего Коста"],
  ["era_laliga", 1, "Radamel Falcao", "Радамель Фалькао"],
  ["era_laliga", 1, "Samuel Eto'o", "Самюэль Это'о"],
  ["era_laliga", 1, "Ronaldinho", "Роналдиньо"],

  ["era_laliga", 2, "Thierry Henry", "Тьерри Анри"],
  ["era_laliga", 2, "David Silva", "Давид Сильва"],
  ["era_laliga", 2, "Juan Mata", "Хуан Мата"],
  ["era_laliga", 2, "Carles Puyol", "Карлес Пуйоль"],
  ["era_laliga", 2, "Dani Alves", "Дани Алвес"],
  ["era_laliga", 2, "Marcelo", "Марсело"],
  ["era_laliga", 2, "Mesut Özil", "Месут Озил"],
  ["era_laliga", 2, "Ángel Di María", "Анхель Ди Мария"],
  ["era_laliga", 2, "Xabi Alonso", "Хаби Алонсо"],
  ["era_laliga", 2, "Pepe", "Пепе"],
  ["era_laliga", 2, "Raúl", "Рауль"],
  ["era_laliga", 2, "Fernando Torres", "Фернандо Торрес"],
  ["era_laliga", 2, "Koke", "Коке"],
  ["era_laliga", 2, "Saúl Ñíguez", "Сауль Ньигес"],
  ["era_laliga", 2, "Jan Oblak", "Ян Облак"],
  ["era_laliga", 2, "Thibaut Courtois", "Тибо Куртуа"],
  ["era_laliga", 2, "Arda Turan", "Арда Туран"],
  ["era_laliga", 2, "Filipe Luís", "Филипе Луис"],
  ["era_laliga", 2, "Diego Godín", "Диего Годин"],
  ["era_laliga", 2, "Ivan Rakitić", "Иван Ракитич"],
  ["era_laliga", 2, "Ousmane Dembélé", "Усман Дембеле"],
  ["era_laliga", 2, "Philippe Coutinho", "Филипе Коутиньо"],
  ["era_laliga", 2, "Frenkie de Jong", "Френки де Йонг"],
  ["era_laliga", 2, "Casemiro", "Каземиро"],
  ["era_laliga", 2, "Raphaël Varane", "Рафаэль Варан"],
  ["era_laliga", 2, "Isco", "Иско"],
  ["era_laliga", 2, "Marco Asensio", "Марко Асенсио"],
  ["era_laliga", 2, "Dani Carvajal", "Дани Карвахаль"],
  ["era_laliga", 2, "Sergio Agüero", "Серхио Агуэро"],
  ["era_laliga", 2, "Wesley Sneijder", "Уэсли Снейдер"],
  ["era_laliga", 2, "Roberto Carlos", "Роберто Карлос"],
  ["era_laliga", 2, "Ruud van Nistelrooy", "Рууд ван Нистелрой"],
  ["era_laliga", 2, "Klaas-Jan Huntelaar", "Клас-Ян Хюнтелар"],
  ["era_laliga", 2, "Carlos Tévez", "Карлос Тевес"],
  ["era_laliga", 2, "Ezequiel Garay", "Эсекьель Гарай"],
  ["era_laliga", 2, "Aritz Aduriz", "Арица Адурис"],
  ["era_laliga", 2, "Iker Muniain", "Икер Муниайн"],
  ["era_laliga", 2, "Santi Cazorla", "Санти Касорла"],
  ["era_laliga", 2, "Cesc Fàbregas", "Сеск Фабрегас"],

  ["era_laliga", 3, "Joaquín", "Хоакин"],
  ["era_laliga", 3, "Pedro", "Педро"],
  ["era_laliga", 3, "Jordi Alba", "Жорди Альба"],
  ["era_laliga", 3, "Javier Mascherano", "Хавьер Маскерано"],
  ["era_laliga", 3, "Seydou Keita", "Сейду Кейта"],
  ["era_laliga", 3, "Yaya Touré", "Яя Туре"],
  ["era_laliga", 3, "Éver Banega", "Эвер Банега"],
  ["era_laliga", 3, "Grzegorz Krychowiak", "Гжегож Крыховяк"],
  ["era_laliga", 3, "Carlos Bacca", "Карлос Бакка"],
  ["era_laliga", 3, "Kévin Gameiro", "Кевин Гамейро"],
  ["era_laliga", 3, "Wissam Ben Yedder", "Виссам Бен Йеддер"],
  ["era_laliga", 3, "Maxi Rodríguez", "Макси Родригес"],
  ["era_laliga", 3, "Giuseppe Rossi", "Джузеппе Росси"],
  ["era_laliga", 3, "Santi Cardozo", "Санти Кардосо"],
  ["era_laliga", 3, "Diego Forlán", "Диего Форлан"],
  ["era_laliga", 3, "Sergio García", "Серхио Гарсия"],
  ["era_laliga", 3, "Bojan Krkić", "Боян Кркич"],
  ["era_laliga", 3, "Andrés Guardado", "Андрес Гуардадо"],
  ["era_laliga", 3, "Vicente Iborra", "Висенте Иборра"],
  ["era_laliga", 3, "Nabil Fekir", "Набиль Фекир"],
  ["era_laliga", 3, "Mikel San José", "Микель Сан Хосе"],
  ["era_laliga", 3, "Gabi", "Габи"],
  ["era_laliga", 3, "Mario Suárez", "Марио Суарес"],
  ["era_laliga", 3, "Cristian Tello", "Кристиан Тельо"],
]);
