/* Football — Ligue 1 2008-2020 */
addWords("football", [
  ["era_ligue1", 1, "Zlatan Ibrahimović", "Златан Ибрагимович"],
  ["era_ligue1", 1, "Edinson Cavani", "Эдинсон Кавани"],
  ["era_ligue1", 1, "Neymar", "Неймар"],
  ["era_ligue1", 1, "Kylian Mbappé", "Килиан Мбаппе"],
  ["era_ligue1", 1, "Thiago Silva", "Тиаго Силва"],
  ["era_ligue1", 1, "Ángel Di María", "Анхель Ди Мария"],
  ["era_ligue1", 1, "Marco Verratti", "Марко Верратти"],
  ["era_ligue1", 1, "Radamel Falcao", "Радамель Фалькао"],
  ["era_ligue1", 1, "Hugo Lloris", "Уго Льорис"],
  ["era_ligue1", 1, "Karim Benzema", "Карим Бензема"],
  ["era_ligue1", 1, "Eden Hazard", "Эден Азар"],
  ["era_ligue1", 1, "Dimitri Payet", "Дмитрий Пайе"],
  ["era_ligue1", 1, "Alexandre Lacazette", "Александр Ляказетт"],
  ["era_ligue1", 1, "Javier Pastore", "Хавьер Пасторе"],
  ["era_ligue1", 2, "Pierre-Emerick Aubameyang", "Пьер-Эмерик Обамеянг"],
  ["era_ligue1", 2, "Yoann Gourcuff", "Йоанн Гуркюфф"],
  ["era_ligue1", 2, "Nabil Fekir", "Набиль Фекир"],
  ["era_ligue1", 2, "Memphis Depay", "Мемфис Депай"],
  ["era_ligue1", 2, "Thiago Motta", "Тиаго Мотта"],
  ["era_ligue1", 2, "Ezequiel Lavezzi", "Эсекьель Лавесси"],
  ["era_ligue1", 2, "Lucas Moura", "Лукас Мора"],
  ["era_ligue1", 2, "Blaise Matuidi", "Блез Матюиди"],
  ["era_ligue1", 2, "Marquinhos", "Маркиньос"],
  ["era_ligue1", 2, "Layvin Kurzawa", "Лайвин Курзава"],
  ["era_ligue1", 2, "Bernardo Silva", "Бернарду Силва"],
  ["era_ligue1", 2, "João Moutinho", "Жоау Моутиньо"],
  ["era_ligue1", 2, "Anthony Martial", "Антони Марсьяль"],
  ["era_ligue1", 2, "Florian Thauvin", "Флориан Товен"],
  ["era_ligue1", 2, "André-Pierre Gignac", "Андре-Пьер Жиньяк"],
  ["era_ligue1", 2, "Mamadou Niang", "Мамаду Ньянг"],
  ["era_ligue1", 2, "Steve Mandanda", "Стив Манданда"],
  ["era_ligue1", 2, "Mathieu Valbuena", "Матьё Вальбуэна"],
  ["era_ligue1", 2, "Salomon Kalou", "Саломон Калу"],
  ["era_ligue1", 2, "Maxwell", "Максвелл"],
  ["era_ligue1", 2, "Gregory van der Wiel", "Грегори ван дер Вил"],
  ["era_ligue1", 2, "Adil Rami", "Адиль Рами"],
  ["era_ligue1", 2, "Jérémy Ménez", "Жереми Менез"],
  ["era_ligue1", 2, "Wissam Ben Yedder", "Виссам Бен Йеддер"],
  ["era_ligue1", 2, "Houssem Aouar", "Уссем Ауар"],
  ["era_ligue1", 2, "Tanguy Ndombélé", "Танги Ндомбеле"],
  ["era_ligue1", 2, "Nicolas Pépé", "Николя Пепе"],
  ["era_ligue1", 2, "Victor Osimhen", "Виктор Осимхен"],
  ["era_ligue1", 3, "Bafétimbi Gomis", "Бафетимби Гомис"],
  ["era_ligue1", 3, "Maxime Gonalons", "Максим Гональонс"],
  ["era_ligue1", 3, "Clément Grenier", "Клеман Гренье"],
  ["era_ligue1", 3, "Jimmy Briand", "Жимми Бриан"],
  ["era_ligue1", 3, "Loïc Rémy", "Лоик Реми"],
  ["era_ligue1", 3, "Rio Mavuba", "Рио Мавуба"],
  ["era_ligue1", 3, "Mathieu Debuchy", "Матьё Дебюши"],
  ["era_ligue1", 3, "Lucas Digne", "Люка Динь"],
  ["era_ligue1", 3, "Idrissa Gueye", "Идрисса Гейе"],
  ["era_ligue1", 3, "Vincent Enyeama", "Винсент Эньеама"],
  ["era_ligue1", 3, "Jean-Eudes Aholou", "Жан-Эд Аолу"],
  ["era_ligue1", 3, "Thomas Lemar", "Тома Лемар"],
  ["era_ligue1", 3, "Benjamin Mendy", "Бенжамен Менди"],
  ["era_ligue1", 3, "Fabinho", "Фабиньо"],
  ["era_ligue1", 3, "Geoffrey Kondogbia", "Жоффре Кондогбиа"],
  ["era_ligue1", 3, "Valère Germain", "Валер Жермен"],
  ["era_ligue1", 3, "Morgan Sanson", "Морган Сансон"],
  ["era_ligue1", 3, "Yohan Cabaye", "Йоан Кабай"],
]);
