/* Football — Serie A 2008-2020 */
addWords("football", [
  ["era_seriea", 1, "Francesco Totti", "Франческо Тотти"],
  ["era_seriea", 1, "Alessandro Del Piero", "Алессандро Дель Пьеро"],
  ["era_seriea", 1, "Andrea Pirlo", "Андреа Пирло"],
  ["era_seriea", 1, "Gianluigi Buffon", "Джанлуиджи Буффон"],
  ["era_seriea", 1, "Zlatan Ibrahimović", "Златан Ибрагимович"],
  ["era_seriea", 1, "Cristiano Ronaldo", "Криштиану Роналду"],
  ["era_seriea", 1, "Kaká", "Кака"],
  ["era_seriea", 1, "Ronaldinho", "Роналдиньо"],
  ["era_seriea", 1, "Samuel Eto'o", "Самюэль Это'о"],
  ["era_seriea", 1, "Wesley Sneijder", "Уэсли Снейдер"],
  ["era_seriea", 1, "Gonzalo Higuaín", "Гонсало Игуаин"],
  ["era_seriea", 1, "Paulo Dybala", "Пауло Дибала"],
  ["era_seriea", 1, "Mauro Icardi", "Мауро Икарди"],
  ["era_seriea", 1, "Arturo Vidal", "Артуро Видаль"],
  ["era_seriea", 1, "Paul Pogba", "Поль Погба"],
  ["era_seriea", 1, "Carlos Tevez", "Карлос Тевес"],
  ["era_seriea", 1, "Edinson Cavani", "Эдинсон Кавани"],
  ["era_seriea", 1, "Romelu Lukaku", "Ромелу Лукаку"],

  ["era_seriea", 2, "Antonio Di Natale", "Антонио Ди Натале"],
  ["era_seriea", 2, "Marek Hamšík", "Марек Гамшик"],
  ["era_seriea", 2, "Lorenzo Insigne", "Лоренцо Инсинье"],
  ["era_seriea", 2, "Dries Mertens", "Дрис Мертенс"],
  ["era_seriea", 2, "Diego Milito", "Диего Милито"],
  ["era_seriea", 2, "Javier Zanetti", "Хавьер Дзанетти"],
  ["era_seriea", 2, "Maicon", "Майкон"],
  ["era_seriea", 2, "Esteban Cambiasso", "Эстебан Камбьяссо"],
  ["era_seriea", 2, "Daniele De Rossi", "Даниеле Де Росси"],
  ["era_seriea", 2, "Giorgio Chiellini", "Джорджо Кьеллини"],
  ["era_seriea", 2, "Leonardo Bonucci", "Леонардо Бонуччи"],
  ["era_seriea", 2, "Andrea Barzagli", "Андреа Барцальи"],
  ["era_seriea", 2, "Claudio Marchisio", "Клаудио Маркизио"],
  ["era_seriea", 2, "Miralem Pjanić", "Миралем Пьянич"],
  ["era_seriea", 2, "Sami Khedira", "Сами Хедира"],
  ["era_seriea", 2, "Douglas Costa", "Дуглас Коста"],
  ["era_seriea", 2, "Sergej Milinković-Savić", "Сергей Милинкович-Савич"],
  ["era_seriea", 2, "Ciro Immobile", "Чиро Иммобиле"],
  ["era_seriea", 2, "Mohamed Salah", "Мохамед Салах"],
  ["era_seriea", 2, "Radja Nainggolan", "Раджа Наингголан"],
  ["era_seriea", 2, "Kalidou Koulibaly", "Калиду Кулибали"],
  ["era_seriea", 2, "Federico Bernardeschi", "Федерико Бернардески"],
  ["era_seriea", 2, "Stephan El Shaarawy", "Стефан Эль-Шаарави"],
  ["era_seriea", 2, "Mario Balotelli", "Марио Балотелли"],
  ["era_seriea", 2, "Robinho", "Робиньо"],
  ["era_seriea", 2, "Thiago Silva", "Тиаго Силва"],
  ["era_seriea", 2, "Alexandre Pato", "Александре Пато"],
  ["era_seriea", 2, "Clarence Seedorf", "Кларенс Зеедорф"],
  ["era_seriea", 2, "Gennaro Gattuso", "Дженнаро Гаттузо"],
  ["era_seriea", 2, "Fabio Cannavaro", "Фабио Каннаваро"],
  ["era_seriea", 2, "Adriano", "Адриано"],

  ["era_seriea", 3, "Andrea Ranocchia", "Андреа Раноккья"],
  ["era_seriea", 3, "Federico Chiesa", "Федерико Кьеза"],
  ["era_seriea", 3, "Nicolò Barella", "Николо Барелла"],
  ["era_seriea", 3, "Marcelo Brozović", "Марцело Брозович"],
  ["era_seriea", 3, "Milan Škriniar", "Милан Шкриньяр"],
  ["era_seriea", 3, "Ivan Perišić", "Иван Перишич"],
  ["era_seriea", 3, "Antonio Candreva", "Антонио Кандрева"],
  ["era_seriea", 3, "Marco Verratti", "Марко Веррати"],
  ["era_seriea", 3, "Allan", "Аллан"],
  ["era_seriea", 3, "Jorginho", "Жоржиньо"],
  ["era_seriea", 3, "Piotr Zieliński", "Пётр Зелиньский"],
  ["era_seriea", 3, "José Callejón", "Хосе Кальехон"],
  ["era_seriea", 3, "Gökhan Inler", "Гёкхан Инлер"],
  ["era_seriea", 3, "Edin Džeko", "Эдин Джеко"],
  ["era_seriea", 3, "Kostas Manolas", "Костас Манолас"],
  ["era_seriea", 3, "Alessandro Florenzi", "Алессандро Флоренци"],
  ["era_seriea", 3, "Borja Valero", "Борха Валеро"],
  ["era_seriea", 3, "Juan Cuadrado", "Хуан Куадрадо"],
  ["era_seriea", 3, "Keita Baldé", "Кейта Бальде"],
  ["era_seriea", 3, "Felipe Anderson", "Фелипе Андерсон"],
  ["era_seriea", 3, "Luis Alberto", "Луис Альберто"],
  ["era_seriea", 3, "Josip Iličić", "Йосип Иличич"],
  ["era_seriea", 3, "Papu Gómez", "Папу Гомес"],
  ["era_seriea", 3, "Duván Zapata", "Дуван Сапата"],
]);
