/* Football — Bundesliga 2008-2020 */
addWords("football", [
  ["era_bundesliga", 1, "Robert Lewandowski", "Роберт Левандовски"],
  ["era_bundesliga", 1, "Arjen Robben", "Арьен Роббен"],
  ["era_bundesliga", 1, "Franck Ribéry", "Франк Рибери"],
  ["era_bundesliga", 1, "Thomas Müller", "Томас Мюллер"],
  ["era_bundesliga", 1, "Manuel Neuer", "Мануэль Нойер"],
  ["era_bundesliga", 1, "Philipp Lahm", "Филипп Лам"],
  ["era_bundesliga", 1, "Bastian Schweinsteiger", "Бастиан Швайнштайгер"],
  ["era_bundesliga", 1, "Mario Götze", "Марио Гётце"],
  ["era_bundesliga", 1, "Marco Reus", "Марко Ройс"],
  ["era_bundesliga", 1, "Mats Hummels", "Матс Хуммельс"],
  ["era_bundesliga", 1, "İlkay Gündoğan", "Илкай Гюндоган"],
  ["era_bundesliga", 1, "Pierre-Emerick Aubameyang", "Пьер-Эмерик Обамеянг"],
  ["era_bundesliga", 1, "Erling Haaland", "Эрлинг Холанд"],
  ["era_bundesliga", 1, "Jadon Sancho", "Джейдон Санчо"],
  ["era_bundesliga", 1, "Toni Kroos", "Тони Кроос"],
  ["era_bundesliga", 1, "Miroslav Klose", "Мирослав Клозе"],

  ["era_bundesliga", 2, "Stefan Kießling", "Штефан Кисслинг"],
  ["era_bundesliga", 2, "Claudio Pizarro", "Клаудио Писарро"],
  ["era_bundesliga", 2, "Raúl", "Рауль"],
  ["era_bundesliga", 2, "Jérôme Boateng", "Жером Боатенг"],
  ["era_bundesliga", 2, "David Alaba", "Давид Алаба"],
  ["era_bundesliga", 2, "Javi Martínez", "Хави Мартинес"],
  ["era_bundesliga", 2, "Mario Gómez", "Марио Гомес"],
  ["era_bundesliga", 2, "Luca Toni", "Лука Тони"],
  ["era_bundesliga", 2, "Xherdan Shaqiri", "Шердан Шакири"],
  ["era_bundesliga", 2, "Henrikh Mkhitaryan", "Генрих Мхитарян"],
  ["era_bundesliga", 2, "Shinji Kagawa", "Синдзи Кагава"],
  ["era_bundesliga", 2, "Ousmane Dembélé", "Усман Дембеле"],
  ["era_bundesliga", 2, "Christian Pulisic", "Кристиан Пулишич"],
  ["era_bundesliga", 2, "Marco Fabián", "Марко Фабиан"],
  ["era_bundesliga", 2, "Kingsley Coman", "Кингсли Коман"],
  ["era_bundesliga", 2, "Leon Goretzka", "Леон Горецка"],
  ["era_bundesliga", 2, "Joshua Kimmich", "Йозуа Киммих"],
  ["era_bundesliga", 2, "Serge Gnabry", "Серж Гнабри"],
  ["era_bundesliga", 2, "Niklas Süle", "Никлас Зюле"],
  ["era_bundesliga", 2, "Thiago Alcântara", "Тьяго Алькантара"],
  ["era_bundesliga", 2, "Arturo Vidal", "Артуро Видаль"],
  ["era_bundesliga", 2, "Mario Mandžukić", "Марио Манджукич"],
  ["era_bundesliga", 2, "Dante", "Данте"],
  ["era_bundesliga", 2, "Roman Weidenfeller", "Роман Вайденфеллер"],
  ["era_bundesliga", 2, "Łukasz Piszczek", "Лукаш Пищек"],
  ["era_bundesliga", 2, "Nuri Şahin", "Нури Шахин"],
  ["era_bundesliga", 2, "Kevin Großkreutz", "Кевин Гросскройц"],
  ["era_bundesliga", 2, "Sven Bender", "Свен Бендер"],
  ["era_bundesliga", 2, "Julian Brandt", "Юлиан Брандт"],
  ["era_bundesliga", 2, "Kevin Volland", "Кевин Фолланд"],
  ["era_bundesliga", 2, "Karim Bellarabi", "Карим Беллараби"],
  ["era_bundesliga", 2, "Kevin-Prince Boateng", "Кевин-Принс Боатенг"],
  ["era_bundesliga", 2, "Naldo", "Налдо"],
  ["era_bundesliga", 2, "Klaas-Jan Huntelaar", "Клаас-Ян Хюнтелар"],
  ["era_bundesliga", 2, "Leon Bailey", "Леон Бэйли"],
  ["era_bundesliga", 2, "Timo Werner", "Тимо Вернер"],
  ["era_bundesliga", 2, "Yussuf Poulsen", "Юссуф Поульсен"],
  ["era_bundesliga", 2, "Naby Keïta", "Наби Кейта"],
  ["era_bundesliga", 2, "Roberto Firmino", "Роберто Фирмино"],
  ["era_bundesliga", 2, "Anthony Modeste", "Антони Модест"],
  ["era_bundesliga", 2, "Vedad Ibišević", "Ведад Ибишевич"],
  ["era_bundesliga", 2, "Roger Schmidt", "Роджер Шмидт"],

  ["era_bundesliga", 3, "Holger Badstuber", "Хольгер Бадштубер"],
  ["era_bundesliga", 3, "Sebastian Rode", "Себастьян Роде"],
  ["era_bundesliga", 3, "Sebastian Kehl", "Себастьян Кель"],
  ["era_bundesliga", 3, "Neven Subotić", "Невен Суботич"],
  ["era_bundesliga", 3, "Marcel Schmelzer", "Марсель Шмельцер"],
  ["era_bundesliga", 3, "Patrick Herrmann", "Патрик Херрманн"],
  ["era_bundesliga", 3, "Max Kruse", "Макс Крузе"],
  ["era_bundesliga", 3, "Florian Niederlechner", "Флориан Нидерлехнер"],
  ["era_bundesliga", 3, "Lars Stindl", "Ларс Штиндль"],
  ["era_bundesliga", 3, "André Schürrle", "Андре Шюррле"],
  ["era_bundesliga", 3, "Marc-André ter Stegen", "Марк-Андре тер Штеген"],
  ["era_bundesliga", 3, "Sami Khedira", "Сами Хедира"],
  ["era_bundesliga", 3, "Daniel Caligiuri", "Даниэль Калиджури"],
  ["era_bundesliga", 3, "Diego", "Диего"],
  ["era_bundesliga", 3, "Grafite", "Графите"]
]);
