/* Football — EPL 2008-2020 */
addWords("football", [
  // [ "era_epl", difficulty(1-3), "EN name", "RU name" ]

  // Tier 1 — superstars of the era
  ["era_epl", 1, "Wayne Rooney", "Уэйн Руни"],
  ["era_epl", 1, "Steven Gerrard", "Стивен Джеррард"],
  ["era_epl", 1, "Frank Lampard", "Фрэнк Лэмпард"],
  ["era_epl", 1, "Didier Drogba", "Дидье Дрогба"],
  ["era_epl", 1, "Fernando Torres", "Фернандо Торрес"],
  ["era_epl", 1, "Sergio Agüero", "Серхио Агуэро"],
  ["era_epl", 1, "David Silva", "Давид Сильва"],
  ["era_epl", 1, "Robin van Persie", "Робин ван Перси"],
  ["era_epl", 1, "Eden Hazard", "Эден Азар"],
  ["era_epl", 1, "Luis Suárez", "Луис Суарес"],
  ["era_epl", 1, "Mohamed Salah", "Мохамед Салах"],
  ["era_epl", 1, "Kevin De Bruyne", "Кевин Де Брёйне"],
  ["era_epl", 1, "Harry Kane", "Гарри Кейн"],
  ["era_epl", 1, "Mesut Özil", "Месут Озил"],
  ["era_epl", 1, "Cristiano Ronaldo", "Криштиану Роналду"],
  ["era_epl", 1, "Thierry Henry", "Тьерри Анри"],
  ["era_epl", 1, "Nemanja Vidić", "Неманья Видич"],
  ["era_epl", 1, "Vincent Kompany", "Венсан Компани"],
  ["era_epl", 1, "Petr Čech", "Петр Чех"],
  ["era_epl", 1, "John Terry", "Джон Терри"],
  ["era_epl", 1, "Virgil van Dijk", "Вирджил ван Дейк"],
  ["era_epl", 1, "Gareth Bale", "Гарет Бэйл"],

  // Tier 2 — well-known
  ["era_epl", 2, "Yaya Touré", "Яя Туре"],
  ["era_epl", 2, "Juan Mata", "Хуан Мата"],
  ["era_epl", 2, "Raheem Sterling", "Рахим Стерлинг"],
  ["era_epl", 2, "Alexis Sánchez", "Алексис Санчес"],
  ["era_epl", 2, "Jamie Vardy", "Джейми Варди"],
  ["era_epl", 2, "Riyad Mahrez", "Рияд Марез"],
  ["era_epl", 2, "N'Golo Kanté", "Нголо Канте"],
  ["era_epl", 2, "Roberto Firmino", "Роберто Фирмино"],
  ["era_epl", 2, "Sadio Mané", "Садио Мане"],
  ["era_epl", 2, "Paul Pogba", "Поль Погба"],
  ["era_epl", 2, "Cesc Fàbregas", "Сеск Фабрегас"],
  ["era_epl", 2, "Carlos Tévez", "Карлос Тевес"],
  ["era_epl", 2, "Dimitar Berbatov", "Димитар Бербатов"],
  ["era_epl", 2, "Michael Carrick", "Майкл Каррик"],
  ["era_epl", 2, "Rio Ferdinand", "Рио Фердинанд"],
  ["era_epl", 2, "Patrice Evra", "Патрис Эвра"],
  ["era_epl", 2, "Ashley Cole", "Эшли Коул"],
  ["era_epl", 2, "Luka Modrić", "Лука Модрич"],
  ["era_epl", 2, "Christian Eriksen", "Кристиан Эриксен"],
  ["era_epl", 2, "Son Heung-min", "Сон Хын Мин"],
  ["era_epl", 2, "Dele Alli", "Деле Алли"],
  ["era_epl", 2, "Hugo Lloris", "Уго Льорис"],
  ["era_epl", 2, "Branislav Ivanović", "Бранислав Иванович"],
  ["era_epl", 2, "Gylfi Sigurðsson", "Гилфи Сигурдссон"],
  ["era_epl", 2, "Pierre-Emerick Aubameyang", "Пьер-Эмерик Обамеянг"],
  ["era_epl", 2, "Anthony Martial", "Антони Марсьяль"],
  ["era_epl", 2, "Romelu Lukaku", "Ромелу Лукаку"],
  ["era_epl", 2, "Wilfried Zaha", "Уилфрид Заа"],
  ["era_epl", 2, "David de Gea", "Давид Де Хеа"],
  ["era_epl", 2, "Bernardo Silva", "Бернарду Силва"],
  ["era_epl", 2, "Leroy Sané", "Лерой Сане"],
  ["era_epl", 2, "Olivier Giroud", "Оливье Жиру"],
  ["era_epl", 2, "Mark Schwarzer", "Марк Шварцер"],

  // Tier 3 — solid / role players
  ["era_epl", 3, "Shane Long", "Шейн Лонг"],
  ["era_epl", 3, "Phil Jagielka", "Фил Джагелка"],
  ["era_epl", 3, "Leighton Baines", "Лейтон Бэйнс"],
  ["era_epl", 3, "Marouane Fellaini", "Маруан Феллайни"],
  ["era_epl", 3, "Shinji Kagawa", "Синдзи Кагава"],
  ["era_epl", 3, "Nemanja Matić", "Неманья Матич"],
  ["era_epl", 3, "Theo Walcott", "Тео Уолкотт"],
  ["era_epl", 3, "Aaron Ramsey", "Аарон Рэмзи"],
  ["era_epl", 3, "Jack Wilshere", "Джек Уилшир"],
  ["era_epl", 3, "James Milner", "Джеймс Милнер"],
  ["era_epl", 3, "Joe Hart", "Джо Харт"],
  ["era_epl", 3, "Gary Cahill", "Гари Кэхилл"],
  ["era_epl", 3, "Glenn Murray", "Гленн Мюррей"],
  ["era_epl", 3, "Charlie Adam", "Чарли Адам"],
  ["era_epl", 3, "Peter Crouch", "Питер Крауч"],
  ["era_epl", 3, "Darren Bent", "Даррен Бент"],
  ["era_epl", 3, "Andy Carroll", "Энди Кэрролл"],
  ["era_epl", 3, "Scott Parker", "Скотт Паркер"],
  ["era_epl", 3, "Jermain Defoe", "Джермейн Дефо"],
  ["era_epl", 3, "Seamus Coleman", "Шеймус Коулман"],
  ["era_epl", 3, "Ryan Bertrand", "Райан Бертранд"],
  ["era_epl", 3, "Nathaniel Clyne", "Натаниэль Клайн"],
  ["era_epl", 3, "Christian Benteke", "Кристиан Бентеке"],
]);
