/* Football — Legends */
addWords("football", [
  ["legends", 1, "Pelé", "Пеле"],
  ["legends", 1, "Diego Maradona", "Диего Марадона"],
  ["legends", 1, "Johan Cruyff", "Йохан Кройф"],
  ["legends", 1, "Franz Beckenbauer", "Франц Беккенбауэр"],
  ["legends", 1, "Zinedine Zidane", "Зинедин Зидан"],
  ["legends", 1, "Ronaldo Nazário", "Роналдо Назарио"],
  ["legends", 1, "Ronaldinho", "Роналдиньо"],
  ["legends", 1, "Gerd Müller", "Герд Мюллер"],
  ["legends", 1, "Eusébio", "Эйсебио"],
  ["legends", 1, "Alfredo Di Stéfano", "Альфредо Ди Стефано"],
  ["legends", 1, "Ferenc Puskás", "Ференц Пушкаш"],
  ["legends", 1, "Lev Yashin", "Лев Яшин"],
  ["legends", 1, "Roberto Baggio", "Роберто Баджо"],
  ["legends", 1, "George Best", "Джордж Бест"],
  ["legends", 1, "Michel Platini", "Мишель Платини"],
  ["legends", 1, "Bobby Charlton", "Бобби Чарлтон"],
  ["legends", 1, "Marco van Basten", "Марко ван Бастен"],
  ["legends", 1, "Ruud Gullit", "Рууд Гуллит"],
  ["legends", 1, "Paolo Maldini", "Паоло Мальдини"],
  ["legends", 1, "Kaká", "Кака"],
  ["legends", 2, "Fabio Cannavaro", "Фабио Каннаваро"],
  ["legends", 2, "Alessandro Nesta", "Алессандро Неста"],
  ["legends", 2, "Andrea Pirlo", "Андреа Пирло"],
  ["legends", 2, "Francesco Totti", "Франческо Тотти"],
  ["legends", 2, "Alessandro Del Piero", "Алессандро Дель Пьеро"],
  ["legends", 2, "Gianluigi Buffon", "Джанлуиджи Буффон"],
  ["legends", 2, "Franco Baresi", "Франко Барези"],
  ["legends", 2, "Dino Zoff", "Дино Дзофф"],
  ["legends", 2, "Paolo Rossi", "Паоло Росси"],
  ["legends", 2, "Thierry Henry", "Тьерри Анри"],
  ["legends", 2, "Patrick Vieira", "Патрик Вьейра"],
  ["legends", 2, "Didier Drogba", "Дидье Дрогба"],
  ["legends", 2, "Steven Gerrard", "Стивен Джеррард"],
  ["legends", 2, "Frank Lampard", "Фрэнк Лэмпард"],
  ["legends", 2, "Paul Scholes", "Пол Скоулз"],
  ["legends", 2, "David Beckham", "Дэвид Бекхэм"],
  ["legends", 2, "Alan Shearer", "Алан Ширер"],
  ["legends", 2, "Luis Figo", "Луиш Фигу"],
  ["legends", 2, "Raúl", "Рауль"],
  ["legends", 2, "Iker Casillas", "Икер Касильяс"],
  ["legends", 2, "Xavi", "Хави"],
  ["legends", 2, "Andrés Iniesta", "Андрес Иньеста"],
  ["legends", 2, "Carles Puyol", "Карлес Пуйоль"],
  ["legends", 2, "Andriy Shevchenko", "Андрей Шевченко"],
  ["legends", 2, "Pavel Nedvěd", "Павел Недвед"],
  ["legends", 2, "Gheorghe Hagi", "Георге Хаджи"],
  ["legends", 2, "Hristo Stoichkov", "Христо Стоичков"],
  ["legends", 2, "George Weah", "Джордж Веа"],
  ["legends", 2, "Jay-Jay Okocha", "Джей-Джей Окоча"],
  ["legends", 2, "Samuel Eto'o", "Самуэль Это'о"],
  ["legends", 2, "Juan Román Riquelme", "Хуан Роман Рикельме"],
  ["legends", 2, "Hernán Crespo", "Эрнан Креспо"],
  ["legends", 2, "Gabriel Batistuta", "Габриэль Батистута"],
  ["legends", 2, "Juan Sebastián Verón", "Хуан Себастьян Верон"],
  ["legends", 2, "Cafu", "Кафу"],
  ["legends", 2, "Roberto Carlos", "Роберто Карлос"],
  ["legends", 2, "Rivaldo", "Ривалдо"],
  ["legends", 2, "Romário", "Ромарио"],
  ["legends", 2, "Bebeto", "Бебето"],
  ["legends", 2, "Sócrates", "Сократес"],
  ["legends", 2, "Zico", "Зико"],
  ["legends", 2, "Falcão", "Фалькао"],
  ["legends", 2, "Frank Rijkaard", "Франк Райкард"],
  ["legends", 2, "Dennis Bergkamp", "Деннис Бергкамп"],
  ["legends", 2, "Clarence Seedorf", "Кларенс Зеедорф"],
  ["legends", 2, "Edgar Davids", "Эдгар Давидс"],
  ["legends", 2, "Patrick Kluivert", "Патрик Клюйверт"],
  ["legends", 2, "Jürgen Klinsmann", "Юрген Клинсманн"],
  ["legends", 2, "Lothar Matthäus", "Лотар Маттеус"],
  ["legends", 2, "Oliver Kahn", "Оливер Кан"],
  ["legends", 2, "Michael Ballack", "Михаэль Баллак"],
  ["legends", 2, "Karl-Heinz Rummenigge", "Карл-Хайнц Румменигге"],
  ["legends", 2, "Miroslav Klose", "Мирослав Клозе"],
  ["legends", 2, "Michael Owen", "Майкл Оуэн"],
  ["legends", 2, "Wayne Rooney", "Уэйн Руни"],
  ["legends", 2, "Gary Lineker", "Гэри Линекер"],
  ["legends", 2, "Ryan Giggs", "Райан Гиггз"],
  ["legends", 2, "Roy Keane", "Рой Кин"],
  ["legends", 2, "Peter Schmeichel", "Петер Шмейхель"],
  ["legends", 2, "Davor Šuker", "Давор Шукер"],
  ["legends", 2, "Zvonimir Boban", "Звонимир Бобан"],
  ["legends", 2, "Dejan Savićević", "Деян Савичевич"],
  ["legends", 2, "Eric Cantona", "Эрик Кантона"],
  ["legends", 2, "Didier Deschamps", "Дидье Дешам"],
  ["legends", 2, "Lilian Thuram", "Лилиан Тюрам"],
  ["legends", 2, "Marcel Desailly", "Марсель Десайи"],
  ["legends", 2, "David Trezeguet", "Давид Трезеге"],
  ["legends", 2, "Fabien Barthez", "Фабьен Бартез"],
  ["legends", 2, "Oleg Blokhin", "Олег Блохин"],
  ["legends", 2, "Andriy Arshavin", "Андрей Аршавин"],
  ["legends", 2, "Nwankwo Kanu", "Нванкво Кану"],
  ["legends", 2, "Yaya Touré", "Яя Туре"],
  ["legends", 2, "Abedi Pelé", "Абеди Пеле"],
  ["legends", 2, "Rui Costa", "Руи Кошта"],
  ["legends", 2, "Nuno Gomes", "Нуну Гомеш"],
  ["legends", 2, "Hugo Sánchez", "Уго Санчес"],
  ["legends", 2, "Carlos Valderrama", "Карлос Вальдеррама"],
  ["legends", 2, "Diego Forlán", "Диего Форлан"],
  ["legends", 2, "Hidetoshi Nakata", "Хидетоси Наката"],
  ["legends", 2, "Park Ji-sung", "Пак Чи Сон"],
  ["legends", 3, "Garrincha", "Гарринча"],
  ["legends", 3, "Carlos Alberto Torres", "Карлос Алберто Торрес"],
  ["legends", 3, "Jairzinho", "Жаирзиньо"],
  ["legends", 3, "Rivelino", "Ривелино"],
  ["legends", 3, "Tostão", "Тостао"],
  ["legends", 3, "Mário Kempes", "Марио Кемпес"],
  ["legends", 3, "Daniel Passarella", "Даниэль Пасарелья"],
  ["legends", 3, "Claudio Caniggia", "Клаудио Каниджа"],
  ["legends", 3, "Gianfranco Zola", "Джанфранко Дзола"],
  ["legends", 3, "Filippo Inzaghi", "Филиппо Индзаги"],
  ["legends", 3, "Gianluca Vialli", "Джанлука Виалли"],
  ["legends", 3, "Roberto Mancini", "Роберто Манчини"],
  ["legends", 3, "Totò Schillaci", "Тото Скиллачи"],
  ["legends", 3, "Sandro Mazzola", "Сандро Маццола"],
  ["legends", 3, "Giacinto Facchetti", "Джачинто Факкетти"],
  ["legends", 3, "Gianni Rivera", "Джанни Ривера"],
  ["legends", 3, "Gaetano Scirea", "Гаэтано Скирея"],
  ["legends", 3, "Marco Tardelli", "Марко Тардели"],
  ["legends", 3, "Emilio Butragueño", "Эмилио Бутрагеньо"],
  ["legends", 3, "Fernando Hierro", "Фернандо Йерро"],
  ["legends", 3, "Gaizka Mendieta", "Гайска Мендиета"],
  ["legends", 3, "Andoni Zubizarreta", "Андони Субисаррета"],
  ["legends", 3, "Sepp Maier", "Зепп Майер"],
  ["legends", 3, "Paul Breitner", "Пауль Брайтнер"],
  ["legends", 3, "Uwe Seeler", "Уве Зеелер"],
  ["legends", 3, "Berti Vogts", "Берти Фогтс"],
  ["legends", 3, "Andreas Brehme", "Андреас Бреме"],
  ["legends", 3, "Rudi Völler", "Руди Феллер"],
  ["legends", 3, "Bobby Moore", "Бобби Мур"],
  ["legends", 3, "Gordon Banks", "Гордон Бэнкс"],
  ["legends", 3, "Kevin Keegan", "Кевин Киган"],
  ["legends", 3, "Kenny Dalglish", "Кенни Далглиш"],
  ["legends", 3, "Bryan Robson", "Брайан Робсон"],
  ["legends", 3, "Paul Gascoigne", "Пол Гаскойн"],
  ["legends", 3, "Stuart Pearce", "Стюарт Пирс"],
  ["legends", 3, "Tony Adams", "Тони Адамс"],
  ["legends", 3, "Peter Shilton", "Питер Шилтон"],
  ["legends", 3, "Marc Overmars", "Марк Овермарс"],
  ["legends", 3, "Rob Rensenbrink", "Роб Ренсенбринк"],
  ["legends", 3, "Johan Neeskens", "Йохан Нескенс"],
  ["legends", 3, "Michael Laudrup", "Микаэль Лаудруп"],
  ["legends", 3, "Brian Laudrup", "Брайан Лаудруп"],
  ["legends", 3, "Preben Elkjær", "Пребен Элькьяр"],
  ["legends", 3, "Zbigniew Boniek", "Збигнев Бонек"],
  ["legends", 3, "Grzegorz Lato", "Гжегож Лато"],
  ["legends", 3, "Dragan Džajić", "Драган Джаич"],
  ["legends", 3, "Robert Prosinečki", "Роберт Просинечки"],
  ["legends", 3, "Predrag Mijatović", "Предраг Миятович"],
  ["legends", 3, "Antonín Panenka", "Антонин Паненка"],
  ["legends", 3, "Josef Masopust", "Йозеф Масопуст"],
  ["legends", 3, "Laurent Blanc", "Лоран Блан"],
  ["legends", 3, "Jean-Pierre Papin", "Жан-Пьер Папен"],
  ["legends", 3, "Youri Djorkaeff", "Юри Джоркаеф"],
  ["legends", 3, "Just Fontaine", "Жюст Фонтен"],
  ["legends", 3, "Raymond Kopa", "Раймон Копа"],
  ["legends", 3, "Igor Belanov", "Игорь Беланов"],
  ["legends", 3, "Rinat Dasayev", "Ринат Дасаев"],
  ["legends", 3, "Eduard Streltsov", "Эдуард Стрельцов"],
  ["legends", 3, "Igor Netto", "Игорь Нетто"],
  ["legends", 3, "Valentin Ivanov", "Валентин Иванов"],
  ["legends", 3, "Roger Milla", "Роже Милла"],
  ["legends", 3, "Hossam Hassan", "Хоссам Хасан"],
  ["legends", 3, "El-Hadji Diouf", "Эль-Хаджи Диуф"],
  ["legends", 3, "Nii Lamptey", "Ни Лэмпти"],
  ["legends", 3, "Vítor Baía", "Витор Байа"],
  ["legends", 3, "Fernando Couto", "Фернандо Коуто"],
  ["legends", 3, "Ossie Ardiles", "Осси Ардилес"],
  ["legends", 3, "Florian Albert", "Флориан Альберт"],
  ["legends", 3, "Wolfgang Overath", "Вольфганг Оверат"],
  ["legends", 3, "Dunga", "Дунга"],
  ["legends", 3, "Aldair", "Алдаир"],
]);
