/* Football — National Teams */
addWords("football", [
  ["national", 1, "Brazil", "Бразилия"],
  ["national", 1, "Argentina", "Аргентина"],
  ["national", 1, "France", "Франция"],
  ["national", 1, "Germany", "Германия"],
  ["national", 1, "Spain", "Испания"],
  ["national", 1, "England", "Англия"],
  ["national", 1, "Italy", "Италия"],
  ["national", 1, "Portugal", "Португалия"],
  ["national", 1, "Netherlands", "Нидерланды"],
  ["national", 1, "Belgium", "Бельгия"],
  ["national", 2, "Croatia", "Хорватия"],
  ["national", 2, "Uruguay", "Уругвай"],
  ["national", 2, "Mexico", "Мексика"],
  ["national", 2, "USA", "США"],
  ["national", 2, "Japan", "Япония"],
  ["national", 2, "Senegal", "Сенегал"],
  ["national", 2, "Morocco", "Марокко"],
  ["national", 2, "Colombia", "Колумбия"],
  ["national", 2, "Switzerland", "Швейцария"],
  ["national", 2, "Denmark", "Дания"],
  ["national", 2, "Poland", "Польша"],
  ["national", 2, "Sweden", "Швеция"],
  ["national", 2, "South Korea", "Южная Корея"],
  ["national", 2, "Nigeria", "Нигерия"],
  ["national", 2, "Ghana", "Гана"],
  ["national", 2, "Serbia", "Сербия"],
  ["national", 2, "Austria", "Австрия"],
  ["national", 2, "Ukraine", "Украина"],
  ["national", 2, "Turkey", "Турция"],
  ["national", 2, "Australia", "Австралия"],
  ["national", 2, "Egypt", "Египет"],
  ["national", 2, "Cameroon", "Камерун"],
  ["national", 2, "Ivory Coast", "Кот-д'Ивуар"],
  ["national", 2, "Chile", "Чили"],
  ["national", 2, "Peru", "Перу"],
  ["national", 2, "Ecuador", "Эквадор"],
  ["national", 3, "Iceland", "Исландия"],
  ["national", 3, "Wales", "Уэльс"],
  ["national", 3, "Scotland", "Шотландия"],
  ["national", 3, "Ireland", "Ирландия"],
  ["national", 3, "Norway", "Норвегия"],
  ["national", 3, "Greece", "Греция"],
  ["national", 3, "Czechia", "Чехия"],
  ["national", 3, "Slovakia", "Словакия"],
  ["national", 3, "Hungary", "Венгрия"],
  ["national", 3, "Romania", "Румыния"],
  ["national", 3, "Costa Rica", "Коста-Рика"],
  ["national", 3, "Saudi Arabia", "Саудовская Аравия"],
  ["national", 3, "Iran", "Иран"],
  ["national", 3, "Qatar", "Катар"],
  ["national", 3, "Canada", "Канада"],
  ["national", 3, "Panama", "Панама"],
  ["national", 3, "Honduras", "Гондурас"],
  ["national", 3, "Tunisia", "Тунис"],
  ["national", 3, "Algeria", "Алжир"],
  ["national", 3, "Mali", "Мали"],
  ["national", 3, "Burkina Faso", "Буркина-Фасо"],
  ["national", 3, "New Zealand", "Новая Зеландия"],
  ["national", 3, "Paraguay", "Парагвай"],
  ["national", 3, "Venezuela", "Венесуэла"],
  ["national", 3, "Bolivia", "Боливия"],
  ["national", 3, "Slovenia", "Словения"],
  ["national", 3, "Albania", "Албания"],
  ["national", 3, "North Macedonia", "Северная Македония"],
  ["national", 3, "Finland", "Финляндия"],
  ["national", 3, "Bosnia and Herzegovina", "Босния и Герцеговина"],
  ["national", 3, "Montenegro", "Черногория"],
  ["national", 3, "Jamaica", "Ямайка"],
  ["national", 3, "DR Congo", "ДР Конго"],
  ["national", 3, "South Africa", "ЮАР"],
  ["national", 3, "Iraq", "Ирак"],
  ["national", 3, "United Arab Emirates", "ОАЭ"],
  ["national", 3, "China", "Китай"],
  ["national", 3, "India", "Индия"],
  ["national", 3, "Israel", "Израиль"],
  ["national", 3, "Russia", "Россия"],
]);
