/* Attack on Titan */
addWords("anime", [
  ["aot", 1, "Eren Yeager", "Эрен Йегер"],
  ["aot", 1, "Mikasa Ackerman", "Микаса Аккерман"],
  ["aot", 1, "Armin Arlert", "Армин Арлерт"],
  ["aot", 1, "Levi Ackerman", "Леви Аккерман"],
  ["aot", 1, "Erwin Smith", "Эрвин Смит"],
  ["aot", 2, "Reiner Braun", "Райнер Браун"],
  ["aot", 2, "Bertholdt Hoover", "Бертольд Гувер"],
  ["aot", 2, "Annie Leonhart", "Энни Леонхарт"],
  ["aot", 2, "Zeke Yeager", "Зик Йегер"],
  ["aot", 2, "Historia Reiss", "Хистория Рейсс"],
  ["aot", 2, "Jean Kirstein", "Жан Кирштайн"],
  ["aot", 2, "Connie Springer", "Конни Спрингер"],
  ["aot", 2, "Sasha Blouse", "Саша Браус"],
  ["aot", 2, "Hange Zoe", "Ханджи Зоэ"],
  ["aot", 2, "Ymir", "Имир"],
  ["aot", 2, "Grisha Yeager", "Гриша Йегер"],
  ["aot", 2, "Kenny Ackerman", "Кенни Аккерман"],
  ["aot", 2, "Gabi Braun", "Габи Браун"],
  ["aot", 2, "Falco Grice", "Фалько Грайс"],
  ["aot", 2, "Pieck Finger", "Пик Фингер"],
  ["aot", 2, "Porco Galliard", "Порко Галлиард"],
  ["aot", 2, "Marco Bott", "Марко Ботт"],
  ["aot", 3, "Ymir Fritz", "Имир Фриц"],
  ["aot", 3, "Floch Forster", "Флок Форстер"],
  ["aot", 3, "Hitch Dreyse", "Хитч Дрейс"],
  ["aot", 3, "Petra Ral", "Петра Рал"],
  ["aot", 3, "Oluo Bozado", "Олуо Бозадо"],
  ["aot", 3, "Eld Jinn", "Эльд Джинн"],
  ["aot", 3, "Gunther Schultz", "Гюнтер Шульц"],
  ["aot", 3, "Moblit Berner", "Моблит Бернер"],
  ["aot", 3, "Dot Pixis", "Дот Пиксис"],
  ["aot", 3, "Nile Dok", "Найл Док"],
  ["aot", 3, "Keith Shadis", "Кит Шадис"],
  ["aot", 3, "Rod Reiss", "Род Рейсс"],
  ["aot", 3, "Kiyomi Azumabito", "Киёми Адзумабито"],
  ["aot", 3, "Theo Magath", "Тео Магат"],
  ["aot", 3, "Willy Tybur", "Вилли Тайбур"],
  ["aot", 3, "Marlowe Freudenberg", "Марло Фройденберг"],
  ["aot", 3, "Onyankopon", "Оньянкопон"],
  ["aot", 3, "Dina Fritz", "Дина Фриц"],
  ["aot", 3, "Carla Yeager", "Карла Йегер"],
  ["aot", 3, "Frieda Reiss", "Фрида Рейсс"],
]);
