// Black Clover characters
addWords("anime", [
  ["blackclover", 1, "Asta", "Аста"],
  ["blackclover", 1, "Yuno", "Юно"],
  ["blackclover", 1, "Noelle Silva", "Ноэль Сильва"],
  ["blackclover", 2, "Yami Sukehiro", "Ями Сукэхиро"],
  ["blackclover", 2, "Luck Voltia", "Лак Волтия"],
  ["blackclover", 2, "Magna Swing", "Магна Свинг"],
  ["blackclover", 2, "Julius Novachrono", "Юлиус Новахроно"],
  ["blackclover", 2, "Mereoleona Vermillion", "Мереолеона Вермиллион"],
  ["blackclover", 2, "Fuegoleon Vermillion", "Фуэголеон Вермиллион"],
  ["blackclover", 2, "Finral Roulacase", "Финрал Руласэ"],
  ["blackclover", 2, "Gordon Agrippa", "Гордон Агриппа"],
  ["blackclover", 2, "Charmy Pappitson", "Чарми Паппитсон"],
  ["blackclover", 2, "Gauche Adlai", "Гоше Адлай"],
  ["blackclover", 2, "Grey", "Грей"],
  ["blackclover", 2, "Vanessa Enoteca", "Ванесса Энотека"],
  ["blackclover", 2, "Henry Legolant", "Генри Леголант"],
  ["blackclover", 2, "Zora Ideale", "Зора Идеале"],
  ["blackclover", 2, "Mimosa Vermillion", "Мимоза Вермиллион"],
  ["blackclover", 2, "Dorothy Unsworth", "Дороти Унсворт"],
  ["blackclover", 2, "William Vangeance", "Уильям Вэнгенс"],
  ["blackclover", 2, "Nozel Silva", "Нозель Сильва"],
  ["blackclover", 2, "Jack the Ripper", "Джек Потрошитель"],
  ["blackclover", 2, "Charlotte Roselei", "Шарлотт Розелей"],
  ["blackclover", 2, "Rill Boismortier", "Рилл Буасмортье"],
  ["blackclover", 3, "Nacht Faust", "Нахт Фауст"],
  ["blackclover", 3, "Liebe", "Либе"],
  ["blackclover", 3, "Dante Zogratis", "Данте Зогратис"],
  ["blackclover", 3, "Zenon Zogratis", "Зенон Зогратис"],
  ["blackclover", 3, "Vanica Zogratis", "Вэника Зогратис"],
  ["blackclover", 3, "Lolopechka", "Лолопечка"],
  ["blackclover", 3, "Secre Swallowtail", "Секрэ Свэллоутейл"],
  ["blackclover", 3, "Mars", "Марс"],
  ["blackclover", 3, "Fana", "Фана"],
  ["blackclover", 3, "Rhya", "Рия"],
  ["blackclover", 3, "Vetto", "Ветто"],
  ["blackclover", 3, "Licht", "Лихт"],
]);
