// Bungo Stray Dogs — canon characters, tiered by prominence
addWords("anime", [
  ["bungostray", 1, "Atsushi Nakajima", "Ацуси Накадзима"],
  ["bungostray", 1, "Osamu Dazai", "Осаму Дазай"],
  ["bungostray", 1, "Ryunosuke Akutagawa", "Рюноскэ Акутагава"],
  ["bungostray", 2, "Chuya Nakahara", "Тюя Накахара"],
  ["bungostray", 2, "Doppo Kunikida", "Доппо Куникида"],
  ["bungostray", 2, "Ranpo Edogawa", "Рампо Эдогава"],
  ["bungostray", 2, "Kenji Miyazawa", "Кэндзи Миядзава"],
  ["bungostray", 2, "Fyodor Dostoevsky", "Фёдор Достоевский"],
  ["bungostray", 2, "Ogai Mori", "Огай Мори"],
  ["bungostray", 2, "Kouyou Ozaki", "Коё Одзаки"],
  ["bungostray", 2, "Yosano Akiko", "Ёсано Акико"],
  ["bungostray", 2, "Junichiro Tanizaki", "Дзюнъитиро Танидзаки"],
  ["bungostray", 2, "Naomi Tanizaki", "Наоми Танидзаки"],
  ["bungostray", 2, "Kyoka Izumi", "Кёка Идзуми"],
  ["bungostray", 2, "Nikolai Gogol", "Николай Гоголь"],
  ["bungostray", 3, "Sigma", "Сигма"],
  ["bungostray", 3, "Ivan Goncharov", "Иван Гончаров"],
  ["bungostray", 3, "Bram Stoker", "Брэм Стокер"],
  ["bungostray", 3, "Francis Scott Fitzgerald", "Фрэнсис Скотт Фицджеральд"],
  ["bungostray", 3, "Lucy Maud Montgomery", "Люси Мод Монтгомери"],
  ["bungostray", 3, "Mark Twain", "Марк Твен"],
  ["bungostray", 3, "Herman Melville", "Герман Мелвилл"],
  ["bungostray", 3, "Katai Tayama", "Катай Таяма"],
  ["bungostray", 3, "Kajii Motojiro", "Кадзии Мотодзиро"],
  ["bungostray", 3, "Michizo Tachihara", "Митидзо Татихара"],
]);
