/* Chainsaw Man */
addWords("anime", [
  ["chainsawman", 1, "Denji", "Дэндзи"],
  ["chainsawman", 1, "Power", "Пауэр"],
  ["chainsawman", 1, "Makima", "Макима"],
  ["chainsawman", 1, "Pochita", "Почита"],
  ["chainsawman", 1, "Aki Hayakawa", "Аки Хаякава"],
  ["chainsawman", 2, "Himeno", "Химено"],
  ["chainsawman", 2, "Kobeni Higashiyama", "Кобэни Хигасияма"],
  ["chainsawman", 2, "Kishibe", "Кишибэ"],
  ["chainsawman", 2, "Angel Devil", "Демон Ангела"],
  ["chainsawman", 2, "Beam", "Бим"],
  ["chainsawman", 2, "Reze", "Рэзэ"],
  ["chainsawman", 2, "Katana Man", "Человек-Катана"],
  ["chainsawman", 2, "Quanxi", "Гуаньси"],
  ["chainsawman", 2, "Santa Claus", "Санта-Клаус"],
  ["chainsawman", 2, "Gun Devil", "Демон Оружия"],
  ["chainsawman", 2, "Darkness Devil", "Демон Тьмы"],
  ["chainsawman", 2, "Asa Mitaka", "Аса Митака"],
  ["chainsawman", 2, "Yoru", "Йор"],
  ["chainsawman", 2, "Fami", "Фами"],
  ["chainsawman", 2, "Nayuta", "Наюта"],
  ["chainsawman", 2, "Barem Bridge", "Барем Бридж"],
  ["chainsawman", 2, "Yoshida", "Ёшида"],
  ["chainsawman", 3, "Hirokazu Arai", "Хирокадзу Арай"],
  ["chainsawman", 3, "Violence Fiend", "Фиенд Насилия"],
  ["chainsawman", 3, "Princi", "Принци"],
  ["chainsawman", 3, "Akane Sawatari", "Акане Саватари"],
  ["chainsawman", 3, "Eternity Devil", "Демон Вечности"],
  ["chainsawman", 3, "Future Devil", "Демон Будущего"],
  ["chainsawman", 3, "Bomb Devil", "Демон Бомбы"],
  ["chainsawman", 3, "Doll Devil", "Демон Кукол"],
  ["chainsawman", 3, "Spider Devil", "Демон Паука"],
  ["chainsawman", 3, "Zombie Devil", "Демон Зомби"],
  ["chainsawman", 3, "Bat Devil", "Демон Летучей Мыши"],
  ["chainsawman", 3, "Falling Devil", "Демон Падения"],
  ["chainsawman", 3, "Aging Devil", "Демон Старения"],
  ["chainsawman", 3, "Death Devil", "Демон Смерти"],
  ["chainsawman", 3, "Miri Sugo", "Мири Суго"],
  ["chainsawman", 3, "Fumiko Mifune", "Фумико Мифунэ"],
  ["chainsawman", 3, "Yuko", "Юко"],
  ["chainsawman", 3, "Haruka Iseumi", "Харука Исэуми"],
  ["chainsawman", 3, "Nobana Higashiyama", "Нобана Хигасияма"],
  ["chainsawman", 3, "Bucky", "Бакки"],
  ["chainsawman", 3, "Meowy", "Мяули"],
  ["chainsawman", 3, "Galgali", "Галгали"],
  ["chainsawman", 3, "Long", "Лонг"],
  ["chainsawman", 3, "Tsugihagi", "Цугихаги"],
  ["chainsawman", 3, "Aldo", "Альдо"],
  ["chainsawman", 3, "Ghost Devil", "Демон Призрака"],
  ["chainsawman", 3, "Fox Devil", "Демон Лисы"],
]);
