// Code Geass — canon characters, tiered by prominence
addWords("anime", [
  ["codegeass", 1, "Lelouch Lamperouge", "Лелуш Ламперуж"],
  ["codegeass", 1, "C.C.", "Си Си"],
  ["codegeass", 1, "Kallen Stadtfeld", "Каллен Штадтфельд"],
  ["codegeass", 1, "Suzaku Kururugi", "Сузаку Куруруги"],
  ["codegeass", 2, "Nunnally Lamperouge", "Нунналли Ламперуж"],
  ["codegeass", 2, "Charles zi Britannia", "Чарльз зи Британия"],
  ["codegeass", 2, "Schneizel el Britannia", "Шнайзель эль Британия"],
  ["codegeass", 2, "Cornelia li Britannia", "Корнелия ли Британия"],
  ["codegeass", 2, "Euphemia li Britannia", "Эуфемия ли Британия"],
  ["codegeass", 2, "Lloyd Asplund", "Ллойд Асплунд"],
  ["codegeass", 2, "Shirley Fenette", "Ширли Фенетт"],
  ["codegeass", 2, "Jeremiah Gottwald", "Джеремия Готтвальд"],
  ["codegeass", 2, "Villetta Nu", "Виллетта Ну"],
  ["codegeass", 2, "Ohgi Kaname", "Оги Канаме"],
  ["codegeass", 3, "Milly Ashford", "Милли Эшфорд"],
  ["codegeass", 3, "Rivalz Cardemonde", "Риваль Кардемонд"],
  ["codegeass", 3, "Nina Einstein", "Нина Эйнштейн"],
  ["codegeass", 3, "Rolo Lamperouge", "Роло Ламперуж"],
  ["codegeass", 3, "V.V.", "Ви Ви"],
  ["codegeass", 3, "Anya Alstreim", "Аня Альштрейм"],
  ["codegeass", 3, "Gino Weinberg", "Джино Вайнберг"],
  ["codegeass", 3, "Diethard Reid", "Дитхард Рид"],
  ["codegeass", 3, "Tohdoh Kyoshiro", "Тодо Кёширо"],
]);
