/* Demon Slayer */
addWords("anime", [
  ["demonslayer", 1, "Tanjiro Kamado", "Тандзиро Камадо"],
  ["demonslayer", 1, "Nezuko Kamado", "Нэдзуко Камадо"],
  ["demonslayer", 1, "Zenitsu Agatsuma", "Дзэнъицу Агацума"],
  ["demonslayer", 1, "Inosuke Hashibira", "Иноскэ Хашибира"],
  ["demonslayer", 1, "Muzan Kibutsuji", "Мудзан Кибуцудзи"],
  ["demonslayer", 1, "Giyu Tomioka", "Гию Томиока"],
  ["demonslayer", 1, "Shinobu Kocho", "Синобу Кочо"],
  ["demonslayer", 1, "Kanao Tsuyuri", "Канао Цуюри"],

  ["demonslayer", 2, "Kyojuro Rengoku", "Кёджуро Ренгоку"],
  ["demonslayer", 2, "Gyomei Himejima", "Гёмэй Химэдзима"],
  ["demonslayer", 2, "Tengen Uzui", "Тэнгэн Удзуи"],
  ["demonslayer", 2, "Mitsuri Kanroji", "Мицури Канродзи"],
  ["demonslayer", 2, "Obanai Iguro", "Обанай Игуро"],
  ["demonslayer", 2, "Sanemi Shinazugawa", "Санэми Шинадзугава"],
  ["demonslayer", 2, "Muichiro Tokito", "Муичиро Токито"],
  ["demonslayer", 2, "Kokushibo", "Кокушибо"],
  ["demonslayer", 2, "Doma", "Дома"],
  ["demonslayer", 2, "Akaza", "Акадза"],
  ["demonslayer", 2, "Nakime", "Накимэ"],
  ["demonslayer", 2, "Hantengu", "Хантэнгу"],
  ["demonslayer", 2, "Gyokko", "Гёкко"],
  ["demonslayer", 2, "Gyutaro", "Гютаро"],
  ["demonslayer", 2, "Daki", "Даки"],
  ["demonslayer", 2, "Enmu", "Энму"],
  ["demonslayer", 2, "Rui", "Руи"],

  ["demonslayer", 3, "Sakonji Urokodaki", "Сакондзи Урокодаки"],
  ["demonslayer", 3, "Kanae Kocho", "Канаэ Кочо"],
  ["demonslayer", 3, "Genya Shinazugawa", "Гэнъя Шинадзугава"],
  ["demonslayer", 3, "Kagaya Ubuyashiki", "Кагая Убуяшики"],
  ["demonslayer", 3, "Tamayo", "Тамаё"],
  ["demonslayer", 3, "Yushiro", "Юширо"],
  ["demonslayer", 3, "Aoi Kanzaki", "Аои Кандзаки"],
  ["demonslayer", 3, "Murata", "Мурата"],
  ["demonslayer", 3, "Kaigaku", "Кайгаку"],
  ["demonslayer", 3, "Yoriichi Tsugikuni", "Ёриичи Цугикуни"],
  ["demonslayer", 3, "Susamaru", "Сусамару"],
  ["demonslayer", 3, "Yahaba", "Яхаба"],
  ["demonslayer", 3, "Makomo", "Макомо"],
  ["demonslayer", 3, "Sabito", "Сабито"],
  ["demonslayer", 3, "Suma", "Сума"],
  ["demonslayer", 3, "Makio", "Макио"],
  ["demonslayer", 3, "Hinatsuru", "Хинацуру"],
]);
