/* Dragon Ball */
addWords("anime", [
  // Tier 1 — main characters
  ["dragonball", 1, "Goku", "Гоку"],
  ["dragonball", 1, "Vegeta", "Вегета"],
  ["dragonball", 1, "Gohan", "Гохан"],
  ["dragonball", 1, "Piccolo", "Пикколо"],
  ["dragonball", 1, "Bulma", "Булма"],
  ["dragonball", 1, "Trunks", "Транкс"],
  ["dragonball", 1, "Goten", "Готэн"],
  ["dragonball", 1, "Krillin", "Криллин"],

  // Tier 2 — Z-fighters & major villains
  ["dragonball", 2, "Frieza", "Фриза"],
  ["dragonball", 2, "Cell", "Селл"],
  ["dragonball", 2, "Majin Buu", "Маджин Буу"],
  ["dragonball", 2, "Master Roshi", "Мастер Роши"],
  ["dragonball", 2, "Yamcha", "Ямча"],
  ["dragonball", 2, "Tien Shinhan", "Тэн Шинхан"],
  ["dragonball", 2, "Chiaotzu", "Чаоцзу"],
  ["dragonball", 2, "Android 18", "Андроид 18"],
  ["dragonball", 2, "Android 17", "Андроид 17"],
  ["dragonball", 2, "Android 16", "Андроид 16"],
  ["dragonball", 2, "Chi-Chi", "Чичи"],
  ["dragonball", 2, "Beerus", "Бирус"],
  ["dragonball", 2, "Whis", "Вис"],
  ["dragonball", 2, "Broly", "Броли"],
  ["dragonball", 2, "Mr. Satan", "Мистер Сатан"],
  ["dragonball", 2, "Videl", "Видэл"],
  ["dragonball", 2, "Dr. Gero", "Доктор Геро"],

  // Tier 3 — deeper cuts
  ["dragonball", 3, "Bardock", "Бардок"],
  ["dragonball", 3, "Raditz", "Радиц"],
  ["dragonball", 3, "Nappa", "Наппа"],
  ["dragonball", 3, "Dende", "Дэндэ"],
  ["dragonball", 3, "Kami", "Ками"],
  ["dragonball", 3, "King Kai", "Кинг Кай"],
  ["dragonball", 3, "Shenron", "Шэнрон"],
  ["dragonball", 3, "Cooler", "Кулер"],
  ["dragonball", 3, "Pan", "Пан"],
  ["dragonball", 3, "Mr. Popo", "Мистер Попо"],
  ["dragonball", 3, "Hercule", "Геркулес"],
  ["dragonball", 3, "Zarbon", "Зарбон"],
  ["dragonball", 3, "Dodoria", "Додория"],
  ["dragonball", 3, "Captain Ginyu", "Капитан Гинью"],
  ["dragonball", 3, "Vegito", "Веджито"],
  ["dragonball", 3, "Gotenks", "Готэнкс"],
  ["dragonball", 3, "Hit", "Хит"],
  ["dragonball", 3, "Jiren", "Джирен"],
  ["dragonball", 3, "Zamasu", "Замасу"],
  ["dragonball", 3, "Goku Black", "Гоку Блэк"],
  ["dragonball", 3, "Caulifla", "Колифла"],
  ["dragonball", 3, "Kale", "Кейл"],
  ["dragonball", 3, "Frost", "Фрост"],
  ["dragonball", 3, "Tarble", "Тарбл"],
  ["dragonball", 3, "Mr. Shu", "Мистер Шу"],
]);
