// Dr. Stone characters
addWords("anime", [
  ["drstone", 1, "Senku Ishigami", "Сэнку Исигами"],
  ["drstone", 1, "Taiju Oki", "Тайдзю Оки"],
  ["drstone", 1, "Yuzuriha Ogawa", "Юдзурихи Огава"],
  ["drstone", 1, "Chrome", "Хром"],
  ["drstone", 2, "Kohaku", "Кохаку"],
  ["drstone", 2, "Gen Asagiri", "Дзэн Асагири"],
  ["drstone", 2, "Tsukasa Shishio", "Цукаса Сисио"],
  ["drstone", 2, "Ryusui Nanami", "Рюсуй Нанами"],
  ["drstone", 2, "Suika", "Суйка"],
  ["drstone", 2, "Kaseki", "Касэки"],
  ["drstone", 2, "Ruri", "Рури"],
  ["drstone", 2, "Kinro", "Кинро"],
  ["drstone", 2, "Ginro", "Гинро"],
  ["drstone", 2, "Francois", "Франсуа"],
  ["drstone", 2, "Hyoga", "Хёга"],
  ["drstone", 3, "Nikki Hanada", "Никки Ханада"],
  ["drstone", 3, "Magma", "Магма"],
  ["drstone", 3, "Ukyo Saionji", "Укё Саиондзи"],
  ["drstone", 3, "Yo Uei", "Ё Уэи"],
  ["drstone", 3, "Mozu", "Модзу"],
  ["drstone", 3, "Homura Momiji", "Хомура Момидзи"],
  ["drstone", 3, "Ishigami Byakuya", "Бякуя Исигами"],
  ["drstone", 3, "Lillian Weinberg", "Лиллиан Вайнберг"],
  ["drstone", 3, "Stanley Snyder", "Стэнли Снайдер"],
  ["drstone", 3, "Chelsea", "Челси"],
  ["drstone", 3, "Matsukaze", "Мацукадзэ"],
]);
