// Fairy Tail characters — tiered by prominence
addWords("anime", [
  ["fairytail", 1, "Natsu Dragneel", "Нацу Драгнил"],
  ["fairytail", 1, "Lucy Heartfilia", "Люси Хартфилия"],
  ["fairytail", 1, "Gray Fullbuster", "Грэй Фулбастер"],
  ["fairytail", 1, "Erza Scarlet", "Эрза Скарлет"],
  ["fairytail", 1, "Happy", "Хэппи"],
  ["fairytail", 2, "Wendy Marvell", "Венди Марвелл"],
  ["fairytail", 2, "Gajeel Redfox", "Газил Редфокс"],
  ["fairytail", 2, "Laxus Dreyar", "Лаксус Дрейар"],
  ["fairytail", 2, "Mirajane Strauss", "Миражейн Штраус"],
  ["fairytail", 2, "Juvia Lockser", "Джувия Локсер"],
  ["fairytail", 2, "Gildarts Clive", "Гилдартс Клайв"],
  ["fairytail", 2, "Elfman Strauss", "Эльфман Штраус"],
  ["fairytail", 2, "Cana Alberona", "Кана Альберона"],
  ["fairytail", 2, "Levy McGarden", "Леви МакГарден"],
  ["fairytail", 2, "Makarov Dreyar", "Макаров Дрейар"],
  ["fairytail", 2, "Jellal Fernandes", "Джеллал Фернандес"],
  ["fairytail", 2, "Pantherlily", "Пантерлили"],
  ["fairytail", 2, "Carla", "Шарль"],
  ["fairytail", 3, "Mystogan", "Мистоган"],
  ["fairytail", 3, "Freed Justine", "Фрид Жюстин"],
  ["fairytail", 3, "Bickslow", "Биксло"],
  ["fairytail", 3, "Evergreen", "Эвергрин"],
  ["fairytail", 3, "Lisanna Strauss", "Лисанна Штраус"],
  ["fairytail", 3, "Zeref Dragneel", "Зереф Драгнил"],
  ["fairytail", 3, "Mavis Vermillion", "Мэвис Вермильон"],
  ["fairytail", 3, "Ultear Milkovich", "Алтеар Милкович"],
  ["fairytail", 3, "Minerva Orland", "Минерва Орланд"],
  ["fairytail", 3, "Kagura Mikazuchi", "Кагура Миказучи"],
  ["fairytail", 3, "Sting Eucliffe", "Стинг Юклифф"],
  ["fairytail", 3, "Rogue Cheney", "Рог Чени"],
  ["fairytail", 3, "Hades", "Аид"],
  ["fairytail", 3, "Acnologia", "Акнология"],
  ["fairytail", 3, "August", "Август"],
  ["fairytail", 3, "Irene Belserion", "Айрин Бельзерион"],
]);
