// Fire Force (Enen no Shouboutai) characters
addWords("anime", [
  ["fireforce", 1, "Shinra Kusakabe", "Синра Кусакабэ"],
  ["fireforce", 1, "Arthur Boyle", "Артур Бойл"],
  ["fireforce", 1, "Tamaki Kotatsu", "Тамаки Котацу"],
  ["fireforce", 1, "Maki Oze", "Маки Одзэ"],
  ["fireforce", 1, "Akitaru Obi", "Акитару Оби"],
  ["fireforce", 2, "Hibana", "Хибана"],
  ["fireforce", 2, "Joker", "Джокер"],
  ["fireforce", 2, "Benimaru Shinmon", "Бэнимару Синмон"],
  ["fireforce", 2, "Sho Kusakabe", "Сё Кусакабэ"],
  ["fireforce", 2, "Inca Kasugatani", "Инка Касугатани"],
  ["fireforce", 2, "Vulcan Joseph", "Вулкан Джозеф"],
  ["fireforce", 2, "Rekka Hoshimiya", "Рэкка Хосимия"],
  ["fireforce", 2, "Takeru Noto", "Такэру Ното"],
  ["fireforce", 2, "Iris", "Ирис"],
  ["fireforce", 3, "Karim Flam", "Карим Флам"],
  ["fireforce", 3, "Foien Li", "Фоиэн Ли"],
  ["fireforce", 3, "Pan Ko Paat", "Пан Ко Паат"],
  ["fireforce", 3, "Konro Sagamiya", "Конро Сагамия"],
  ["fireforce", 3, "Licht", "Лихт"],
  ["fireforce", 3, "Assault", "Ассолт"],
  ["fireforce", 3, "Ritsu", "Рицу"],
  ["fireforce", 3, "Haumea", "Хаумэа"],
  ["fireforce", 3, "Arrow", "Эрроу"],
  ["fireforce", 3, "Giovanni", "Джованни"],
  ["fireforce", 3, "Nataku Son", "Натаку Сон"],
  ["fireforce", 3, "Charon", "Харон"],
]);
