// Fullmetal Alchemist: Brotherhood characters
addWords("anime", [
  ["fma", 1, "Edward Elric", "Эдвард Элрик"],
  ["fma", 1, "Alphonse Elric", "Альфонс Элрик"],
  ["fma", 1, "Roy Mustang", "Рой Мустанг"],
  ["fma", 1, "Winry Rockbell", "Винри Рокбелл"],
  ["fma", 2, "Riza Hawkeye", "Риза Хокай"],
  ["fma", 2, "Scar", "Шрам"],
  ["fma", 2, "Father", "Отец"],
  ["fma", 2, "Envy", "Зависть"],
  ["fma", 2, "Lust", "Похоть"],
  ["fma", 2, "Greed", "Жадность"],
  ["fma", 2, "Gluttony", "Чревоугодие"],
  ["fma", 2, "Wrath", "Гнев"],
  ["fma", 2, "Sloth", "Лень"],
  ["fma", 2, "Pride", "Гордыня"],
  ["fma", 2, "Alex Louis Armstrong", "Алекс Луи Армстронг"],
  ["fma", 2, "Maes Hughes", "Маэс Хьюз"],
  ["fma", 2, "Ling Yao", "Лин Яо"],
  ["fma", 2, "Olivier Armstrong", "Оливье Армстронг"],
  ["fma", 2, "Van Hohenheim", "Ван Хоэнхайм"],
  ["fma", 3, "Izumi Curtis", "Идзуми Кёртис"],
  ["fma", 3, "Sig Curtis", "Сиг Кёртис"],
  ["fma", 3, "Lan Fan", "Лань Фань"],
  ["fma", 3, "May Chang", "Мэй Чан"],
  ["fma", 3, "Führer King Bradley", "Король Брэдли"],
  ["fma", 3, "Tim Marcoh", "Тим Марко"],
  ["fma", 3, "Mei Xiao-Mei", "Сяо Мэй"],
  ["fma", 3, "Pinako Rockbell", "Пинако Рокбелл"],
  ["fma", 3, "Gracia Hughes", "Грейсия Хьюз"],
  ["fma", 3, "Selim Bradley", "Сэлим Брэдли"],
  ["fma", 3, "Jean Havoc", "Жан Гавок"],
  ["fma", 3, "Vato Falman", "Вато Фалман"],
  ["fma", 3, "Kain Fuery", "Кейн Фьюри"],
  ["fma", 3, "Heymans Breda", "Хеймэнс Бреда"],
  ["fma", 3, "Yoki", "Ёки"],
]);
