/* Frieren */
addWords("anime", [
  ["frieren", 1, "Frieren", "Фрирен"],
  ["frieren", 1, "Fern", "Ферн"],
  ["frieren", 1, "Stark", "Штарк"],
  ["frieren", 1, "Himmel", "Химмель"],
  ["frieren", 2, "Heiter", "Хайтер"],
  ["frieren", 2, "Eisen", "Айзен"],
  ["frieren", 2, "Sein", "Зайн"],
  ["frieren", 2, "Flamme", "Фламме"],
  ["frieren", 2, "Serie", "Серие"],
  ["frieren", 2, "Aura", "Аура"],
  ["frieren", 2, "Lügner", "Люгнер"],
  ["frieren", 2, "Denken", "Денкен"],
  ["frieren", 2, "Übel", "Юбель"],
  ["frieren", 2, "Wirbel", "Вирбель"],
  ["frieren", 3, "Lawine", "Лавин"],
  ["frieren", 3, "Kanne", "Канне"],
  ["frieren", 3, "Methode", "Метода"],
  ["frieren", 3, "Land", "Ланд"],
  ["frieren", 3, "Genau", "Генау"],
  ["frieren", 3, "Linie", "Линие"],
  ["frieren", 3, "Sense", "Зензе"],
]);
