// Haikyuu!! characters — tier 1=main, 2=major, 3=deep cuts
addWords("anime", [
  ["haikyu", 1, "Shoyo Hinata", "Сёё Хината"],
  ["haikyu", 1, "Tobio Kageyama", "Тобио Кагэяма"],
  ["haikyu", 1, "Kei Tsukishima", "Кэй Цукисима"],
  ["haikyu", 1, "Yu Nishinoya", "Ю Нисиноя"],
  ["haikyu", 1, "Daichi Sawamura", "Дайти Савамура"],
  ["haikyu", 1, "Tadashi Yamaguchi", "Тадаси Ямагути"],
  ["haikyu", 1, "Asahi Azumane", "Асахи Адзумане"],
  ["haikyu", 1, "Koushi Sugawara", "Коси Сугавара"],
  ["haikyu", 2, "Tooru Oikawa", "Тоору Ойкава"],
  ["haikyu", 2, "Wakatoshi Ushijima", "Вакатоси Усидзима"],
  ["haikyu", 2, "Kotaro Bokuto", "Котаро Бокуто"],
  ["haikyu", 2, "Kenma Kozume", "Кэнма Кодзумэ"],
  ["haikyu", 2, "Tetsurou Kuroo", "Тэцуро Куроо"],
  ["haikyu", 2, "Koutarou Aran", "Коутаро Аран"],
  ["haikyu", 2, "Hajime Iwaizumi", "Хадзимэ Ивайдзуми"],
  ["haikyu", 2, "Ryunosuke Tanaka", "Рюноскэ Танака"],
  ["haikyu", 2, "Keiji Akaashi", "Кэйдзи Акааси"],
  ["haikyu", 2, "Atsumu Miya", "Ацуму Мия"],
  ["haikyu", 2, "Osamu Miya", "Осаму Мия"],
  ["haikyu", 2, "Kiyoomi Sakusa", "Киёоми Сакуса"],
  ["haikyu", 2, "Shouhei Fukunaga", "Сёхэй Фукунага"],
  ["haikyu", 3, "Lev Haiba", "Лев Хайба"],
  ["haikyu", 3, "Morisuke Yaku", "Морисукэ Яку"],
  ["haikyu", 3, "Nobuyuki Kai", "Нобуюки Каи"],
  ["haikyu", 3, "Satori Tendou", "Сатори Тэндо"],
  ["haikyu", 3, "Eita Semi", "Эйта Сэми"],
  ["haikyu", 3, "Taichi Kawanishi", "Таити Каванаси"],
  ["haikyu", 3, "Akira Kunimi", "Акира Кунимэ"],
  ["haikyu", 3, "Issei Matsukawa", "Иссэй Мацукава"],
  ["haikyu", 3, "Takahiro Hanamaki", "Такахиро Ханамаки"],
  ["haikyu", 3, "Yuji Terushima", "Юдзи Тэрусима"],
  ["haikyu", 3, "Shinji Watari", "Синдзи Ватари"],
  ["haikyu", 3, "Haruki Komi", "Харуки Коми"],
  ["haikyu", 3, "Tsutomu Goshiki", "Цутому Госики"],
  ["haikyu", 3, "Rintarou Suna", "Ринтаро Суна"],
]);
