// Hunter × Hunter characters — tiers: 1=main, 2=major, 3=deep cut
addWords("anime", [
  ["hunterxhunter", 1, "Gon Freecss", "Гон Фрикс"],
  ["hunterxhunter", 1, "Killua Zoldyck", "Киллуа Золдик"],
  ["hunterxhunter", 1, "Kurapika", "Курапика"],
  ["hunterxhunter", 1, "Leorio Paradinight", "Леорио Парадинайт"],
  ["hunterxhunter", 2, "Hisoka Morow", "Хисока Моро"],
  ["hunterxhunter", 2, "Chrollo Lucilfer", "Кролло Люцифер"],
  ["hunterxhunter", 2, "Isaac Netero", "Айзек Нетеро"],
  ["hunterxhunter", 2, "Meruem", "Меруэм"],
  ["hunterxhunter", 2, "Illumi Zoldyck", "Иллуми Золдик"],
  ["hunterxhunter", 2, "Feitan Portor", "Фейтан Портор"],
  ["hunterxhunter", 2, "Phinks Magcub", "Финкс Магкаб"],
  ["hunterxhunter", 2, "Machi Komacine", "Мачи Комасин"],
  ["hunterxhunter", 2, "Nobunaga Hazama", "Нобунага Хазама"],
  ["hunterxhunter", 2, "Shalnark", "Шалнарк"],
  ["hunterxhunter", 2, "Uvogin", "Увогин"],
  ["hunterxhunter", 2, "Neferpitou", "Нефарпиту"],
  ["hunterxhunter", 2, "Shaiapouf", "Шайапуф"],
  ["hunterxhunter", 2, "Menthuthuyoupi", "Ментхутхуюпи"],
  ["hunterxhunter", 2, "Ging Freecss", "Гинг Фрикс"],
  ["hunterxhunter", 2, "Biscuit Krueger", "Бисквит Кругер"],
  ["hunterxhunter", 2, "Knuckle Bine", "Накл Байн"],
  ["hunterxhunter", 2, "Shoot McMahon", "Шут МакМэхон"],
  ["hunterxhunter", 3, "Silva Zoldyck", "Сильва Золдик"],
  ["hunterxhunter", 3, "Zeno Zoldyck", "Зено Золдик"],
  ["hunterxhunter", 3, "Kikyo Zoldyck", "Кикё Золдик"],
  ["hunterxhunter", 3, "Alluka Zoldyck", "Аллюка Золдик"],
  ["hunterxhunter", 3, "Kalluto Zoldyck", "Каллуто Золдик"],
  ["hunterxhunter", 3, "Morel Mackernasey", "Морел Макернейси"],
  ["hunterxhunter", 3, "Knov", "Кнов"],
  ["hunterxhunter", 3, "Goreinu", "Горейну"],
  ["hunterxhunter", 3, "Tsezguerra", "Цезгерра"],
  ["hunterxhunter", 3, "Palm Siberia", "Палм Сибериа"],
  ["hunterxhunter", 3, "Ikalgo", "Икалго"],
  ["hunterxhunter", 3, "Meleoron", "Мелеорон"],
  ["hunterxhunter", 3, "Bonolenov Ndongo", "Бонолёнов Ндонго"],
  ["hunterxhunter", 3, "Shizuku Murasaki", "Сидзуку Мурасаки"],
  ["hunterxhunter", 3, "Franklin Bordeau", "Франклин Бордо"],
  ["hunterxhunter", 3, "Kortopi", "Корторпи"],
  ["hunterxhunter", 3, "Pakunoda", "Пакунода"],
  ["hunterxhunter", 3, "Kite", "Кайто"],
]);
