// Inuyasha — canon characters
addWords("anime", [
  ["inuyasha", 1, "Inuyasha", "Инуяша"],
  ["inuyasha", 1, "Kagome Higurashi", "Кагомэ Хигураси"],
  ["inuyasha", 1, "Miroku", "Мироку"],
  ["inuyasha", 1, "Sango", "Санго"],
  ["inuyasha", 1, "Shippo", "Сиппо"],
  ["inuyasha", 2, "Sesshomaru", "Сэссёмару"],
  ["inuyasha", 2, "Naraku", "Нараку"],
  ["inuyasha", 2, "Kikyo", "Кикё"],
  ["inuyasha", 2, "Kagura", "Кагура"],
  ["inuyasha", 2, "Kohaku", "Кохаку"],
  ["inuyasha", 2, "Koga", "Кога"],
  ["inuyasha", 2, "Rin", "Рин"],
  ["inuyasha", 2, "Jaken", "Дзякэн"],
  ["inuyasha", 2, "Myoga", "Мёга"],
  ["inuyasha", 3, "Kaede", "Каэдэ"],
  ["inuyasha", 3, "Hakudoshi", "Хакудоси"],
  ["inuyasha", 3, "Suikotsu", "Суйкоцу"],
  ["inuyasha", 3, "Ginkotsu", "Гинкоцу"],
  ["inuyasha", 3, "Bankotsu", "Банкоцу"],
  ["inuyasha", 3, "Kanna", "Канна"],
  ["inuyasha", 3, "Totosai", "Тотосай"],
  ["inuyasha", 3, "Mushin", "Мусин"],
]);
