/* Jujutsu Kaisen */
addWords("anime", [
  ["jjk", 1, "Yuji Itadori", "Юдзи Итадори"],
  ["jjk", 1, "Satoru Gojo", "Сатору Годзё"],
  ["jjk", 1, "Megumi Fushiguro", "Мэгуми Фусигуро"],
  ["jjk", 1, "Nobara Kugisaki", "Нобара Кугисаки"],
  ["jjk", 1, "Sukuna", "Сукуна"],
  ["jjk", 2, "Kento Nanami", "Кэнто Нанами"],
  ["jjk", 2, "Maki Zenin", "Маки Дзэнин"],
  ["jjk", 2, "Toge Inumaki", "Тогэ Инумаки"],
  ["jjk", 2, "Panda", "Панда"],
  ["jjk", 2, "Yuta Okkotsu", "Юта Оккоцу"],
  ["jjk", 2, "Aoi Todo", "Аой Тодо"],
  ["jjk", 2, "Kiyotaka Ijichi", "Киётака Идзити"],
  ["jjk", 2, "Masamichi Yaga", "Масамити Яга"],
  ["jjk", 2, "Mahito", "Махито"],
  ["jjk", 2, "Suguru Geto", "Сугуру Гэто"],
  ["jjk", 2, "Jogo", "Дзёго"],
  ["jjk", 2, "Hanami", "Ханами"],
  ["jjk", 2, "Choso", "Тёсо"],
  ["jjk", 2, "Kokichi Muta", "Кокити Мута"],
  ["jjk", 2, "Junpei Yoshino", "Дзюмпэй Ёсино"],
  ["jjk", 3, "Kasumi Miwa", "Касуми Мива"],
  ["jjk", 3, "Mai Zenin", "Май Дзэнин"],
  ["jjk", 3, "Momo Nishimiya", "Момо Нисимия"],
  ["jjk", 3, "Noritoshi Kamo", "Норитоси Камо"],
  ["jjk", 3, "Mechamaru", "Мехамару"],
  ["jjk", 3, "Atsuya Kusakabe", "Ацуя Кусакабэ"],
  ["jjk", 3, "Shoko Ieiri", "Сёко Иэйри"],
  ["jjk", 3, "Yuki Tsukumo", "Юки Цукумо"],
  ["jjk", 3, "Hajime Kashimo", "Хадзимэ Касимо"],
  ["jjk", 3, "Naoya Zenin", "Наоя Дзэнин"],
  ["jjk", 3, "Toji Fushiguro", "Тодзи Фусигуро"],
  ["jjk", 3, "Hiromi Higuruma", "Хироми Хигурума"],
  ["jjk", 3, "Kinji Hakari", "Киндзи Хакари"],
  ["jjk", 3, "Mei Mei", "Мэй Мэй"],
  ["jjk", 3, "Uraume", "Ураумэ"],
  ["jjk", 3, "Dagon", "Дагон"],
  ["jjk", 3, "Eso", "Эсо"],
  ["jjk", 3, "Kechizu", "Кэтидзу"],
  ["jjk", 3, "Yoshinobu Gakuganji", "Ёсинобу Гакугандзи"],
  ["jjk", 3, "Takuma Ino", "Такума Ино"],
  ["jjk", 3, "Nanako Hasaba", "Нанако Хасаба"],
  ["jjk", 3, "Mimiko Hasaba", "Мимико Хасаба"],
]);
