// JoJo's Bizarre Adventure — Parts 1–8, ~44 canon characters
addWords("anime", [
  // Tier 1 — Iconic protagonists & Dio
  ["jojo", 1, "Jotaro Kujo", "Дзётаро Кудзё"],
  ["jojo", 1, "Dio Brando", "Дио Брандо"],
  ["jojo", 1, "Joseph Joestar", "Джозеф Джостар"],
  ["jojo", 1, "Giorno Giovanna", "Джорно Джованна"],
  ["jojo", 1, "Jonathan Joestar", "Джонатан Джостар"],
  ["jojo", 1, "Josuke Higashikata", "Дзёсукэ Хигасиката"],

  // Tier 2 — Major JoJos, villains & key allies
  ["jojo", 2, "Jolyne Cujoh", "Джолин Кудзё"],
  ["jojo", 2, "Yoshikage Kira", "Ёсикагэ Кира"],
  ["jojo", 2, "Diavolo", "Диаволо"],
  ["jojo", 2, "Kars", "Карс"],
  ["jojo", 2, "Jean Pierre Polnareff", "Жан Пьер Польнарефф"],
  ["jojo", 2, "Noriaki Kakyoin", "Норияки Какёин"],
  ["jojo", 2, "Caesar Anthonio Zeppeli", "Цезарь Антонио Цепели"],
  ["jojo", 2, "Wamuu", "Вамуу"],
  ["jojo", 2, "Esidisi", "Эсидиси"],
  ["jojo", 2, "Risotto Nero", "Ризотто Неро"],
  ["jojo", 2, "Bruno Bucciarati", "Бруно Буччеллати"],
  ["jojo", 2, "Guido Mista", "Гвидо Миста"],
  ["jojo", 2, "Robert E. O. Speedwagon", "Роберт Э. О. Спидвагон"],

  // Tier 3 — Deep cuts
  ["jojo", 3, "Iggy", "Игги"],
  ["jojo", 3, "Muhammad Avdol", "Мухаммад Авдол"],
  ["jojo", 3, "Abbacchio Leone", "Аббаккьо Леоне"],
  ["jojo", 3, "Narancia Ghirga", "Нараньча Гирга"],
  ["jojo", 3, "Pannacotta Fugo", "Паннакота Фуго"],
  ["jojo", 3, "Trish Una", "Триш Уна"],
  ["jojo", 3, "Koichi Hirose", "Коити Хиросэ"],
  ["jojo", 3, "Okuyasu Nijimura", "Окуясу Ниджимура"],
  ["jojo", 3, "Rohan Kishibe", "Рохан Кисибэ"],
  ["jojo", 3, "Shigekiyo Yangu", "Сигэкиё Янгу"],
  ["jojo", 3, "Akira Otoishi", "Акира Отоиси"],
  ["jojo", 3, "Yukako Yamagishi", "Юкако Ямагиси"],
  ["jojo", 3, "Weather Report", "Уэзер Репорт"],
  ["jojo", 3, "Narciso Anasui", "Нарцисо Анасуи"],
  ["jojo", 3, "Ermes Costello", "Эрмэс Костелло"],
  ["jojo", 3, "Enrico Pucci", "Энрико Пуччи"],
  ["jojo", 3, "Emporio Alniño", "Эмпорио Альниньо"],
  ["jojo", 3, "Funny Valentine", "Фанни Валентайн"],
  ["jojo", 3, "Johnny Joestar", "Джонни Джостар"],
  ["jojo", 3, "Gyro Zeppeli", "Дьиро Цепели"],
  ["jojo", 3, "Hol Horse", "Хол Хорс"],
  ["jojo", 3, "Vanilla Ice", "Ванилла Айс"],
  ["jojo", 3, "Stroheim", "Штрохайм"],
  ["jojo", 3, "Will A. Zeppeli", "Уилл А. Цепели"],
  ["jojo", 3, "Sandman", "Сэндмэн"],
]);
