/* My Hero Academia */
addWords("anime", [
  ["mha", 1, "Izuku Midoriya", "Идзуку Мидория"],
  ["mha", 1, "Katsuki Bakugo", "Кацуки Бакуго"],
  ["mha", 1, "All Might", "Всемогущий"],
  ["mha", 1, "Shoto Todoroki", "Сёто Тодороки"],
  ["mha", 1, "Ochaco Uraraka", "Очако Урарака"],
  ["mha", 1, "Tenya Iida", "Тэнья Иида"],
  ["mha", 1, "Tomura Shigaraki", "Томура Сигараки"],
  ["mha", 1, "All For One", "Один за всех"],
  ["mha", 2, "Eijiro Kirishima", "Эйдзиро Кириcима"],
  ["mha", 2, "Denki Kaminari", "Дэнки Каминари"],
  ["mha", 2, "Fumikage Tokoyami", "Фумикагэ Токоями"],
  ["mha", 2, "Tsuyu Asui", "Цую Асуи"],
  ["mha", 2, "Momo Yaoyorozu", "Момо Яоёрозу"],
  ["mha", 2, "Kyoka Jiro", "Кёка Дзиро"],
  ["mha", 2, "Mina Ashido", "Мина Ашидо"],
  ["mha", 2, "Hanta Sero", "Ханта Сэро"],
  ["mha", 2, "Mashirao Ojiro", "Маширао Одзиро"],
  ["mha", 2, "Mezo Shoji", "Мэдзо Сёдзи"],
  ["mha", 2, "Koji Koda", "Кодзи Кода"],
  ["mha", 2, "Rikido Sato", "Рикидо Сато"],
  ["mha", 2, "Yuga Aoyama", "Юга Аояма"],
  ["mha", 2, "Toru Hagakure", "Тору Хагакурэ"],
  ["mha", 2, "Minoru Mineta", "Минору Минэта"],
  ["mha", 2, "Shota Aizawa", "Сёта Айдзава"],
  ["mha", 2, "Hizashi Yamada", "Хидзаси Ямада"],
  ["mha", 2, "Endeavor", "Эндевор"],
  ["mha", 2, "Hawks", "Хоукс"],
  ["mha", 2, "Dabi", "Даби"],
  ["mha", 2, "Himiko Toga", "Химико Тога"],
  ["mha", 2, "Kurogiri", "Курогири"],
  ["mha", 2, "Eraser Head", "Эрейзерхэд"],
  ["mha", 3, "Nezu", "Нэдзу"],
  ["mha", 3, "Nemuri Kayama", "Нэмури Каяма"],
  ["mha", 3, "Mirio Togata", "Мирио Тогата"],
  ["mha", 3, "Tamaki Amajiki", "Тамаки Амадзики"],
  ["mha", 3, "Nejire Hado", "Нэдзирэ Хадо"],
  ["mha", 3, "Mei Hatsume", "Мэй Хацумэ"],
  ["mha", 3, "Hitoshi Shinso", "Хитоси Синсо"],
  ["mha", 3, "Neito Monoma", "Нэйто Монома"],
  ["mha", 3, "Itsuka Kendo", "Ицука Кэндо"],
  ["mha", 3, "Stain", "Стейн"],
  ["mha", 3, "Overhaul", "Овэрхол"],
  ["mha", 3, "Eri", "Эри"],
  ["mha", 3, "Gran Torino", "Гран Торино"],
  ["mha", 3, "Best Jeanist", "Бест Джинист"],
  ["mha", 3, "Mt. Lady", "Маунт Леди"],
  ["mha", 3, "Kota Izumi", "Кота Идзуми"],
  ["mha", 3, "Inasa Yoarashi", "Инаса Ёараси"],
]);
