/* Naruto */
addWords("anime", [
  // [ "naruto", difficulty(1-3), "EN name", "RU name" ]

  // Tier 1 — everyone knows
  ["naruto", 1, "Naruto Uzumaki", "Наруто Удзумаки"],
  ["naruto", 1, "Sasuke Uchiha", "Саскэ Учиха"],
  ["naruto", 1, "Sakura Haruno", "Сакура Харуно"],
  ["naruto", 1, "Kakashi Hatake", "Какаси Хатакэ"],

  // Tier 2 — major supporting (Konoha 11, sannin, kage, Akatsuki leads)
  ["naruto", 2, "Itachi Uchiha", "Итачи Учиха"],
  ["naruto", 2, "Hinata Hyuga", "Хината Хьюга"],
  ["naruto", 2, "Gaara", "Гаара"],
  ["naruto", 2, "Jiraiya", "Джирайя"],
  ["naruto", 2, "Tsunade", "Цунадэ"],
  ["naruto", 2, "Orochimaru", "Орочимару"],
  ["naruto", 2, "Shikamaru Nara", "Шикамару Нара"],
  ["naruto", 2, "Rock Lee", "Рок Ли"],
  ["naruto", 2, "Neji Hyuga", "Нэдзи Хьюга"],
  ["naruto", 2, "Kiba Inuzuka", "Киба Инудзука"],
  ["naruto", 2, "Ino Yamanaka", "Ино Яманака"],
  ["naruto", 2, "Choji Akimichi", "Чоджи Акимичи"],
  ["naruto", 2, "Shino Aburame", "Сино Абурамэ"],
  ["naruto", 2, "Tenten", "Тэнтэн"],
  ["naruto", 2, "Pain", "Пейн"],
  ["naruto", 2, "Madara Uchiha", "Мадара Учиха"],
  ["naruto", 2, "Obito Uchiha", "Обито Учиха"],
  ["naruto", 2, "Kisame Hoshigaki", "Кисамэ Хошигаки"],
  ["naruto", 2, "Deidara", "Дейдара"],
  ["naruto", 2, "Minato Namikaze", "Минато Намикадзэ"],
  ["naruto", 2, "Killer Bee", "Киллер Би"],
  ["naruto", 2, "Might Guy", "Майто Гай"],
  ["naruto", 2, "Iruka Umino", "Ирука Умино"],

  // Tier 3 — deeper cuts (minor ninja, villains, canon side characters)
  ["naruto", 3, "Kabuto Yakushi", "Кабуто Якуси"],
  ["naruto", 3, "Konan", "Конан"],
  ["naruto", 3, "Sasori", "Сасори"],
  ["naruto", 3, "Hidan", "Хидан"],
  ["naruto", 3, "Kakuzu", "Какудзу"],
  ["naruto", 3, "Zetsu", "Дзэцу"],
  ["naruto", 3, "Tobi", "Тоби"],
  ["naruto", 3, "Sai", "Сай"],
  ["naruto", 3, "Yamato", "Ямато"],
  ["naruto", 3, "Asuma Sarutobi", "Асума Сарутоби"],
  ["naruto", 3, "Kurenai Yuhi", "Курэнай Юхи"],
  ["naruto", 3, "Hiruzen Sarutobi", "Хирудзэн Сарутоби"],
  ["naruto", 3, "Hashirama Senju", "Хаширама Сэндзю"],
  ["naruto", 3, "Tobirama Senju", "Тобирама Сэндзю"],
  ["naruto", 3, "Kushina Uzumaki", "Кушина Удзумаки"],
  ["naruto", 3, "Konohamaru Sarutobi", "Конохамару Сарутоби"],
  ["naruto", 3, "Shizune", "Сидзунэ"],
  ["naruto", 3, "Temari", "Тэмари"],
  ["naruto", 3, "Kankuro", "Канкуро"],
  ["naruto", 3, "Zabuza Momochi", "Дзабудза Момочи"],
  ["naruto", 3, "Haku", "Хаку"],
  ["naruto", 3, "Onoki", "Оноки"],
  ["naruto", 3, "Mei Terumi", "Мэй Тэруми"],
  ["naruto", 3, "Nagato", "Нагато"],
  ["naruto", 3, "Kurama", "Курама"],
]);
