/* One Piece */
addWords("anime", [
  // [ "onepiece", difficulty(1-3), "EN name", "RU name" ]

  // Tier 1 — Straw Hats core & most famous
  ["onepiece", 1, "Monkey D. Luffy", "Манки Д. Луффи"],
  ["onepiece", 1, "Roronoa Zoro", "Ророноа Зоро"],
  ["onepiece", 1, "Nami", "Нами"],
  ["onepiece", 1, "Sanji", "Санджи"],
  ["onepiece", 1, "Tony Tony Chopper", "Тони Тони Чоппер"],
  ["onepiece", 1, "Usopp", "Усопп"],
  ["onepiece", 1, "Portgas D. Ace", "Портгас Д. Эйс"],
  ["onepiece", 1, "Trafalgar Law", "Трафальгар Ло"],
  ["onepiece", 1, "Shanks", "Шанкс"],
  ["onepiece", 1, "Gol D. Roger", "Гол Д. Роджер"],

  // Tier 2 — rest of crew, Warlords, Admirals, Yonko
  ["onepiece", 2, "Nico Robin", "Нико Робин"],
  ["onepiece", 2, "Franky", "Фрэнки"],
  ["onepiece", 2, "Brook", "Брук"],
  ["onepiece", 2, "Jinbe", "Джинбэй"],
  ["onepiece", 2, "Vinsmoke Sanji", "Винсмок Санджи"],
  ["onepiece", 2, "Boa Hancock", "Боа Хэнкок"],
  ["onepiece", 2, "Dracule Mihawk", "Дракуль Михок"],
  ["onepiece", 2, "Crocodile", "Крокодайл"],
  ["onepiece", 2, "Donquixote Doflamingo", "Донкихот Дофламинго"],
  ["onepiece", 2, "Gecko Moria", "Гекко Мория"],
  ["onepiece", 2, "Bartholomew Kuma", "Бартоломью Кума"],
  ["onepiece", 2, "Buggy", "Багги"],
  ["onepiece", 2, "Monkey D. Garp", "Манки Д. Гарп"],
  ["onepiece", 2, "Monkey D. Dragon", "Манки Д. Драгон"],
  ["onepiece", 2, "Sakazuki", "Сакадзуки"],
  ["onepiece", 2, "Borsalino", "Борсалино"],
  ["onepiece", 2, "Kuzan", "Кудзан"],
  ["onepiece", 2, "Sengoku", "Сэнгоку"],
  ["onepiece", 2, "Smoker", "Смокер"],
  ["onepiece", 2, "Edward Newgate", "Эдвард Ньюгейт"],
  ["onepiece", 2, "Kaido", "Кайдо"],
  ["onepiece", 2, "Charlotte Linlin", "Шарлотта Линлин"],
  ["onepiece", 2, "Marshall D. Teach", "Маршалл Д. Тич"],
  ["onepiece", 2, "Eustass Kid", "Юстасс Кид"],
  ["onepiece", 2, "Sabo", "Сабо"],

  // Tier 3 — deeper cuts: minor pirates, marines, supernovas, side characters
  ["onepiece", 3, "Nefertari Vivi", "Нефертари Виви"],
  ["onepiece", 3, "Vinsmoke Reiju", "Винсмок Рэйджу"],
  ["onepiece", 3, "Koby", "Коби"],
  ["onepiece", 3, "Helmeppo", "Хельмеппо"],
  ["onepiece", 3, "Tashigi", "Тасиги"],
  ["onepiece", 3, "Rob Lucci", "Роб Луччи"],
  ["onepiece", 3, "Spandam", "Спандам"],
  ["onepiece", 3, "Bon Clay", "Бон Клей"],
  ["onepiece", 3, "Enel", "Энел"],
  ["onepiece", 3, "Arlong", "Арлонг"],
  ["onepiece", 3, "Capone Bege", "Капоне Беге"],
  ["onepiece", 3, "Basil Hawkins", "Бэзил Хокинс"],
  ["onepiece", 3, "Scratchmen Apoo", "Скретчмен Апу"],
  ["onepiece", 3, "X Drake", "Икс Дрейк"],
  ["onepiece", 3, "Jewelry Bonney", "Джевелри Бонни"],
  ["onepiece", 3, "Killer", "Киллер"],
  ["onepiece", 3, "Cavendish", "Кавендиш"],
  ["onepiece", 3, "Bartolomeo", "Бартоломео"],
  ["onepiece", 3, "Kozuki Oden", "Кодзуки Одэн"],
  ["onepiece", 3, "Yamato", "Ямато"],
  ["onepiece", 3, "Charlotte Katakuri", "Шарлотта Катакури"],
  ["onepiece", 3, "Carrot", "Кэррот"],
  ["onepiece", 3, "Silvers Rayleigh", "Сильверс Рэйли"],
  ["onepiece", 3, "Shimotsuki Kozaburo", "Симоцуки Кодзабуро"],
  ["onepiece", 3, "Perona", "Перона"],
]);
