// One-Punch Man characters
addWords("anime", [
  ["onepunchman", 1, "Saitama", "Сайтама"],
  ["onepunchman", 1, "Genos", "Генос"],
  ["onepunchman", 2, "Garou", "Гароу"],
  ["onepunchman", 2, "Tatsumaki", "Тацумаки"],
  ["onepunchman", 2, "King", "Кинг"],
  ["onepunchman", 2, "Bang", "Банг"],
  ["onepunchman", 2, "Mumen Rider", "Безлицензионный Гонщик"],
  ["onepunchman", 2, "Boros", "Борос"],
  ["onepunchman", 2, "Fubuki", "Фубуки"],
  ["onepunchman", 2, "Atomic Samurai", "Атомный Самурай"],
  ["onepunchman", 2, "Metal Bat", "Металлическая Бита"],
  ["onepunchman", 2, "Child Emperor", "Дитя Император"],
  ["onepunchman", 2, "Pig God", "Бог-Свин"],
  ["onepunchman", 2, "Tornado of Terror", "Торнадо Террора"],
  ["onepunchman", 3, "Speed-o'-Sound Sonic", "Соник Звуковой Скорости"],
  ["onepunchman", 3, "Flashy Flash", "Яркая Вспышка"],
  ["onepunchman", 3, "Zombie Man", "Зомби-Мен"],
  ["onepunchman", 3, "Drive Knight", "Рыцарь Привода"],
  ["onepunchman", 3, "Superalloy Darkshine", "Суперсплав Тёмный Блеск"],
  ["onepunchman", 3, "Puri-Puri Prisoner", "Пури-Пури Узник"],
  ["onepunchman", 3, "Metal Knight", "Металлический Рыцарь"],
  ["onepunchman", 3, "Tank-Top Master", "Мастер Майки"],
  ["onepunchman", 3, "Silverfang", "Серебряный Клык"],
  ["onepunchman", 3, "Sweet Mask", "Сладкая Маска"],
  ["onepunchman", 3, "Melzargard", "Мельзагард"],
  ["onepunchman", 3, "Mosquito Girl", "Комариная Девушка"],
  ["onepunchman", 3, "Carnage Kabuto", "Резня Кабуто"],
  ["onepunchman", 3, "Gouketsu", "Гокэцу"],
  ["onepunchman", 3, "Watchdog Man", "Пёс-Страж"],
  ["onepunchman", 3, "Tareo", "Тарэо"],
]);
