// Sword Art Online characters
addWords("anime", [
  ["sao", 1, "Kirito", "Кирито"],
  ["sao", 1, "Asuna", "Асуна"],
  ["sao", 2, "Sinon", "Синон"],
  ["sao", 2, "Leafa", "Лифа"],
  ["sao", 2, "Klein", "Кляйн"],
  ["sao", 2, "Yui", "Юи"],
  ["sao", 2, "Eugeo", "Юджио"],
  ["sao", 2, "Alice", "Алиса"],
  ["sao", 2, "Heathcliff", "Хитклиф"],
  ["sao", 2, "Agil", "Эджил"],
  ["sao", 2, "Lisbeth", "Лисбет"],
  ["sao", 2, "Silica", "Силика"],
  ["sao", 3, "Suguha", "Сугуха"],
  ["sao", 3, "Kayaba Akihiko", "Каяба Акихико"],
  ["sao", 3, "Yuna", "Юна"],
  ["sao", 3, "Quinella", "Куинелла"],
  ["sao", 3, "Administrator", "Администратор"],
  ["sao", 3, "Cardinal", "Кардинал"],
  ["sao", 3, "Bercouli", "Беркули"],
  ["sao", 3, "Fanatio", "Фанатио"],
  ["sao", 3, "Eugeo's Alice", "Алиса Зубереа"],
  ["sao", 3, "PoH", "PoH"],
  ["sao", 3, "Oberon", "Оберон"],
  ["sao", 3, "Sachi", "Сати"],
  ["sao", 3, "Diabel", "Диабель"],
]);
