/* Solo Leveling */
addWords("anime", [
  ["sololeveling", 1, "Sung Jinwoo", "Сон Джину"],
  ["sololeveling", 2, "Igris", "Игрис"],
  ["sololeveling", 2, "Beru", "Беру"],
  ["sololeveling", 2, "Cha Hae-In", "Ча Хэин"],
  ["sololeveling", 2, "Bellion", "Беллион"],
  ["sololeveling", 2, "Kaisel", "Кайсель"],
  ["sololeveling", 2, "Antares", "Антарес"],
  ["sololeveling", 2, "Go Gunhee", "Ко Гонхи"],
  ["sololeveling", 2, "Yoo Jinho", "Ю Джинхо"],
  ["sololeveling", 2, "Thomas Andre", "Томас Андре"],
  ["sololeveling", 2, "Ashborn", "Эшборн"],
  ["sololeveling", 3, "Choi Jong-In", "Чхве Джонин"],
  ["sololeveling", 3, "Baek Yoonho", "Пэк Юно"],
  ["sololeveling", 3, "Sung Ilhwan", "Сон Ирхван"],
  ["sololeveling", 3, "Sung Jinah", "Сон Джина"],
  ["sololeveling", 3, "Tusk", "Таск"],
  ["sololeveling", 3, "Iron", "Айрон"],
  ["sololeveling", 3, "Tank", "Танк"],
  ["sololeveling", 3, "Lim Taekyung", "Им Тхэгён"],
  ["sololeveling", 3, "Ahn Sangmin", "Ан Сангмин"],
  ["sololeveling", 3, "Hwang Dongsuk", "Хван Дончок"],
  ["sololeveling", 3, "Esil Radiru", "Эсиль Радиру"],
  ["sololeveling", 3, "Baran", "Баран"],
  ["sololeveling", 3, "Querehsha", "Квэрэша"],
  ["sololeveling", 3, "Lennart Niermann", "Леннарт Нирманн"],
  ["sololeveling", 3, "Liu Zhigang", "Лю Чжиган"],
  ["sololeveling", 3, "Christopher Reed", "Кристофер Рид"],
  ["sololeveling", 3, "The Architect", "Архитектор"],
  ["sololeveling", 3, "Kamish", "Камиш"],
]);
