// That Time I Got Reincarnated as a Slime (Tensei shitara Slime Datta Ken)
addWords("anime", [
  ["tensura", 1, "Rimuru Tempest", "Римуру Темпест"],
  ["tensura", 1, "Veldora Tempest", "Велдора Темпест"],
  ["tensura", 1, "Milim Nava", "Милим Нава"],
  ["tensura", 2, "Benimaru", "Бэнимару"],
  ["tensura", 2, "Shion", "Шион"],
  ["tensura", 2, "Shuna", "Шуна"],
  ["tensura", 2, "Souei", "Соуэй"],
  ["tensura", 2, "Diablo", "Дьябло"],
  ["tensura", 2, "Gabiru", "Габиру"],
  ["tensura", 2, "Gobta", "Гобта"],
  ["tensura", 2, "Hakurou", "Хакуро"],
  ["tensura", 2, "Ranga", "Ранга"],
  ["tensura", 2, "Rigurd", "Ригурд"],
  ["tensura", 2, "Treyni", "Трейни"],
  ["tensura", 3, "Veldomon", "Велдомон"],
  ["tensura", 3, "Hinata Sakaguchi", "Хината Сакагути"],
  ["tensura", 3, "Clayman", "Клэйман"],
  ["tensura", 3, "Mjurran", "Мьюлан"],
  ["tensura", 3, "Geld", "Гелд"],
  ["tensura", 3, "Kumara", "Кумара"],
  ["tensura", 3, "Adalman", "Адалман"],
  ["tensura", 3, "Guy Crimson", "Гай Кримсон"],
  ["tensura", 3, "Ramiris", "Рамирис"],
  ["tensura", 3, "Beretta", "Беретта"],
  ["tensura", 3, "Gabil", "Габил"],
]);
