// Tokyo Revengers characters
addWords("anime", [
  ["tokyorevengers", 1, "Takemichi Hanagaki", "Такэмити Ханагаки"],
  ["tokyorevengers", 1, "Manjiro Sano (Mikey)", "Мандзиро Сано (Майки)"],
  ["tokyorevengers", 1, "Ken Ryuguji (Draken)", "Кэн Рюгудзи (Дракен)"],
  ["tokyorevengers", 2, "Keisuke Baji", "Кэйсукэ Бадзи"],
  ["tokyorevengers", 2, "Chifuyu Matsuno", "Тифую Мацуно"],
  ["tokyorevengers", 2, "Kazutora Hanemiya", "Кадзутора Ханэмия"],
  ["tokyorevengers", 2, "Tetta Kisaki", "Тэтта Кисаки"],
  ["tokyorevengers", 2, "Hinata Tachibana", "Хината Татибана"],
  ["tokyorevengers", 2, "Naoto Tachibana", "Наото Татибана"],
  ["tokyorevengers", 2, "Haruki Hayashida (Pah-chin)", "Харуки Хаясида (Па-тян)"],
  ["tokyorevengers", 2, "Ryohei Hayashi (Peh-yan)", "Рёхэй Хаяси (Пэ-ян)"],
  ["tokyorevengers", 2, "Makoto Suzuki (Makku)", "Макото Судзуки (Макку)"],
  ["tokyorevengers", 2, "Takuya Yamamoto (Yamagishi)", "Такуя Ямамото (Ямагиси)"],
  ["tokyorevengers", 2, "Shuji Hanma", "Сюдзи Ханма"],
  ["tokyorevengers", 2, "Izana Kurokawa", "Идзана Курокава"],
  ["tokyorevengers", 2, "Kakucho", "Какутё"],
  ["tokyorevengers", 3, "Seishu Inui", "Сэйсю Инуи"],
  ["tokyorevengers", 3, "Hajime Kokonoi", "Хадзимэ Кокóнои"],
  ["tokyorevengers", 3, "Ran Haitani", "Ран Хайтани"],
  ["tokyorevengers", 3, "Rindo Haitani", "Риндо Хайтани"],
  ["tokyorevengers", 3, "Takeomi Akashi", "Такэоми Акаси"],
  ["tokyorevengers", 3, "Senju Kawaragi", "Сэндзю Каварагии"],
  ["tokyorevengers", 3, "Haruchiyo Sanzu", "Харутиё Санзу"],
  ["tokyorevengers", 3, "Yasuhiro Muto (Mucho)", "Ясухиро Муто (Мутё)"],
  ["tokyorevengers", 3, "Kanji Mochizuki (Mocchi)", "Кандзи Мотидзуки (Мотти)"],
  ["tokyorevengers", 3, "Nobutaka Osanai", "Нобутака Осанаи"],
  ["tokyorevengers", 3, "Masataka Kiyomizu (Koko)", "Масатака Киёмидзу (Коко)"],
  ["tokyorevengers", 3, "Toman's Mitsuya Takashi", "Митсуя Такаси"],
]);
