// Tokyo Ghoul characters
addWords("anime", [
  ["tokyoghoul", 1, "Ken Kaneki", "Кэн Канэки"],
  ["tokyoghoul", 1, "Touka Kirishima", "Тока Киришима"],
  ["tokyoghoul", 1, "Rize Kamishiro", "Ризэ Камиширо"],
  ["tokyoghoul", 1, "Hideyoshi Nagachika", "Хидэёси Нагачика"],
  ["tokyoghoul", 2, "Shu Tsukiyama", "Шу Цукияма"],
  ["tokyoghoul", 2, "Juuzou Suzuya", "Дзюдзо Судзуя"],
  ["tokyoghoul", 2, "Kotaro Amon", "Котаро Амон"],
  ["tokyoghoul", 2, "Kishou Arima", "Кишо Арима"],
  ["tokyoghoul", 2, "Uta", "Ута"],
  ["tokyoghoul", 2, "Renji Yomo", "Рэндзи Йомо"],
  ["tokyoghoul", 2, "Hinami Fueguchi", "Хинами Фуэгути"],
  ["tokyoghoul", 2, "Nishiki Nishio", "Нишики Нишио"],
  ["tokyoghoul", 2, "Kaya Irimi", "Кая Ирими"],
  ["tokyoghoul", 2, "Enji Koma", "Энджи Кома"],
  ["tokyoghoul", 2, "Yoshimura", "Ёшимура"],
  ["tokyoghoul", 2, "Akira Mado", "Акира Мадо"],
  ["tokyoghoul", 2, "Kureo Mado", "Курэо Мадо"],
  ["tokyoghoul", 3, "Ayato Kirishima", "Аято Киришима"],
  ["tokyoghoul", 3, "Tatara", "Татара"],
  ["tokyoghoul", 3, "Noro", "Норо"],
  ["tokyoghoul", 3, "Eto Yoshimura", "Это Ёшимура"],
  ["tokyoghoul", 3, "Roma Hoito", "Рома Хоито"],
  ["tokyoghoul", 3, "Hooguro", "Хоогуро"],
  ["tokyoghoul", 3, "Kuki Urie", "Куки Урие"],
  ["tokyoghoul", 3, "Saiko Yonebayashi", "Сайко Ёнэбаяши"],
  ["tokyoghoul", 3, "Shinsanpei Aura", "Шинсанпэй Аура"],
  ["tokyoghoul", 3, "Ui Koori", "Уи Коори"],
  ["tokyoghoul", 3, "Hairu Ihei", "Хайру Ихэй"],
]);
