// Vinland Saga characters
addWords("anime", [
  ["vinlandsaga", 1, "Thorfinn", "Торфинн"],
  ["vinlandsaga", 1, "Askeladd", "Аскеладд"],
  ["vinlandsaga", 1, "Thors", "Торс"],
  ["vinlandsaga", 1, "Canute", "Кнут"],
  ["vinlandsaga", 2, "Thorkell", "Торкель"],
  ["vinlandsaga", 2, "Einar", "Эйнар"],
  ["vinlandsaga", 2, "Bjorn", "Бьёрн"],
  ["vinlandsaga", 2, "Leif Erikson", "Лейф Эрикссон"],
  ["vinlandsaga", 2, "Ketil", "Кетиль"],
  ["vinlandsaga", 2, "Ylva", "Ильва"],
  ["vinlandsaga", 2, "Snake", "Змей"],
  ["vinlandsaga", 2, "Helga", "Хельга"],
  ["vinlandsaga", 3, "Floki", "Флоки"],
  ["vinlandsaga", 3, "Ragnar", "Рагнар"],
  ["vinlandsaga", 3, "Willibald", "Виллибальд"],
  ["vinlandsaga", 3, "Gratianus", "Грациан"],
  ["vinlandsaga", 3, "Ari", "Ари"],
  ["vinlandsaga", 3, "Sigurd", "Сигурд"],
  ["vinlandsaga", 3, "Sverkel", "Сверкель"],
  ["vinlandsaga", 3, "Anne", "Анна"],
  ["vinlandsaga", 3, "Pater", "Патер"],
  ["vinlandsaga", 3, "Halfdan", "Хальфдан"],
  ["vinlandsaga", 3, "Atli", "Атли"],
  ["vinlandsaga", 3, "Gardar", "Гардар"],
]);
